### ISSUE TITLE
[PM-942] pegasus-statistics gives a SQL alchemy error when monitord does not populate the database

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1059]
I tried running pegasus-statistics, but I got errors on every directory.  Here's an example:

[cybershk@shock pegasus-statistics]$ pegasus-statistics -s all -o /home/scec-02/cybershk/utils/Study_15_4/pegasus-statistics/3861 /home/scec-02/cybershk/runs/WNGC_PP_dax/run_3861/dags/cybershk/pegasus/CyberShake_WNGC/20150317T123530-0700
Deleting existing directory. Deleting... /home/scec-02/cybershk/utils/Study_15_4/pegasus-statistics/3861
2015-05-22 17:14:04,367:Pegasus.tools.utils:197: WARNING: Deleting existing directory. Deleting... /home/scec-02/cybershk/utils/Study_15_4/pegasus-statistics/3861
No results found for wf_uuid: 6ee73655-a760-4290-ae57-ae720042767b
2015-05-22 17:14:04,566:Pegasus.db.workflow.stampede_statistics.StampedeStatistics:211: ERROR: No results found for wf_uuid: 6ee73655-a760-4290-ae57-ae720042767b
No results found for wf_uuid: 6ee73655-a760-4290-ae57-ae720042767b
2015-05-22 17:14:04,785:Pegasus.db.workflow.stampede_statistics.StampedeStatistics:211: ERROR: No results found for wf_uuid: 6ee73655-a760-4290-ae57-ae720042767b
/opt/pegasus/pegasus-4.5.0rc1/lib64/pegasus/externals/python/sqlalchemy/sql/expression.py:1980: SAWarning: The IN-predicate on "workflow.wf_id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
  return o[0](self, self.expr, op, *(other + o[1:]), **kwargs)
Traceback (most recent call last):
  File "/opt/pegasus/default/bin/pegasus-statistics", line 1215, in <module>
    main()
  File "/opt/pegasus/default/bin/pegasus-statistics", line 1212, in main
    print_workflow_details(output_db_url, wf_uuid, output_dir, multiple_wf=multiple_wf)
  File "/opt/pegasus/default/bin/pegasus-statistics", line 424, in print_workflow_details
    wf_det = individual_workflow_stats.get_workflow_details()[0]
IndexError: list index out of range

**Reporter:** @scallag
**Resolution:** Fixed
**Watchers:**
@mayani
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

This is a side affect of the pegasus-db-admin tool, where it always ends up creating and initializing an empty database in the workflow submit directory.

In Scott's case, the monitord population was turned on. 

We should modify the query in pegasus-statistics to print out an helpful message that information about workflow is not in the database. make sure monitord population is turned on.

**Comment by mayani** [comment]
**Author:** @mayani

Added error message to say wf `wf_uuid` was not found in database `db`
