### ISSUE TITLE
[PM-1022] dynamic hierarchy tests failed randomly

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1137]
Our 028-dynamic-hiearchy tests fail randomly on the subdax job, where the planner fails with cannot find inner.dax that is supposed to be generated by generate_dax job

8.607 PST: [CONFIG]  pegasus.home.sysconfdir=/lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT45-T28A/pegasus/etc 
11-Dec-2015 14:51:41	2015.12.11 14:50:38.608 PST: [CONFIG]  pegasus.log.*=/lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT45-T28A/test/core/028-dynamic-hierarchy/work/bamboo/pegasus/local-hierarchy/run0001/subdax_inner_ID0000002.pre.log 
11-Dec-2015 14:51:41	2015.12.11 14:50:38.608 PST: [CONFIG]  pegasus.workflow.root.uuid=e69ba852-fc3d-48de-a0f4-222ca8b21170 
11-Dec-2015 14:51:41	2015.12.11 14:50:39.349 PST: [DEBUG]  Retrieving Metadata from the DAX file /lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT45-T28A/test/core/028-dynamic-hierarchy/work/local-site/scratch/bamboo/pegasus/local-hierarchy/run0001/inner.dax 
11-Dec-2015 14:51:41	2015.12.11 14:50:39.535 PST: [ERROR]  Problem while determining the version of dax class java.lang.RuntimeException: java.io.FileNotFoundException: The file (/lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT45-T28A/test/core/028-dynamic-hierarchy/work/local-site/scratch/bamboo/pegasus/local-hierarchy/run0001/inner.dax ) specified does not exist 
11-Dec-2015 14:51:41	2015.12.11 14:50:39.535 PST: [CONFIG]  DAX Parser Class to be loaded is DAXParser3 
11-Dec-2015 14:51:41	2015.12.11 14:50:39.569 PST: [CONFIG]  Picking schema /lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT45-T28A/pegasus/share/pegasus/schema/dax-3.5.xsd 
11-Dec-2015 14:51:41	2015.12.11 14:50:39.570 PST: [INFO] event.pegasus.parse.dax dax.id /lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT45-T28A/test/core/028-dynamic-hierarchy/work/local-site/scratch/bamboo/pegasus/local-hierarchy/run0001/inner.dax  - STARTED 
11-Dec-2015 14:51:41	2015.12.11 14:50:39.571 PST: [ERROR]  IO Error :The file (/lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT45-T28A/test/core/028-dynamic-hierarchy/work/local-site/scratch/bamboo/pegasus/local-hierarchy/run0001/inner.dax ) specified does not exist 
11-Dec-2015 14:51:41	2015.12.11 14:50:39.571 PST: [INFO] event.pegasus.parse.dax dax.id /lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT45-T28A/test/core/028-dynamic-hierarchy/work/local-site/scratch/bamboo/pegasus/local-hierarchy/run0001/inner.dax  (0.001 seconds) - FINISHED 
11-Dec-2015 14:51:41	2015.12.11 14:50:39.591 PST: [FATAL ERROR]  java.lang.RuntimeException: Method called before the abstract dag  for the partition was fully generated
11-Dec-2015 14:51:41	        at edu.isi.pegasus.planner.parser.dax.DAX2CDAG.getConstructedObject(DAX2CDAG.java:284)
11-Dec-2015 14:51:41	        at edu.isi.pegasus.planner.client.CPlanner.parseDAX(CPlanner.java:1855)
11-Dec-2015 14:51:41	        at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:496)
11-Dec-2015 14:51:41	        at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:363)

**Reporter:** @rynge
**Resolution:** Fixed
**Watchers:**
@vahi
**Attachments:**

**Comment by mayani** [comment]
**Author:** @vahi

clean_up_local_hierarchy_5_ job cleans up the dax and we can see that the subdax_ job is not a parent to the cleanup job.

that is why it is failing randomly.

**Comment by mayani** [comment]
**Author:** @vahi

corbusier:run0012 vahi$ grep clean_up_local_level_5_0 *dag
JOB clean_up_local_level_5_0 clean_up_local_level_5_0.sub
SCRIPT POST clean_up_local_level_5_0 /lfs1/devel/Pegasus/git/pegasus/bin/pegasus-exitcode   /Volumes/Work/lfs1/work/pegasus-features/bugs/#1137/dags/vahi/pegasus/local-hierarchy/run0012/clean_up_local_level_5_0.out
RETRY clean_up_local_level_5_0 1
CATEGORY clean_up_local_level_5_0 cleanup
PARENT  stage_out_local_local_0_0 CHILD clean_up_local_level_5_0
PARENT  clean_up_local_level_5_0 CHILD cleanup_local-hierarchy_0_local
PARENT  subdax_inner_ID0000002 CHILD clean_up_local_level_5_0

this is now fixed

**Comment by mayani** [comment]
**Author:** @vahi

fixed with a clean up job dependent on the DAX job
