### ISSUE TITLE
[PM-1035] pegasus-analyzer fails when workflow db has no entries

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1149]
Reported by Ben Mayer. His workflow did not start because of #1089, but pegasus-analyzer gave this output:

-bash-4.1$ pegasus-analyzer 
2016-01-15 09:15:41,285:ERROR:Pegasus.db.workflow.stampede_statistics.StampedeStatistics(211): No results found for wf_uuid: 86e1ab00-367a-4698-b941-94224589c7f1
Traceback (most recent call last):
  File "/sw/redhat6/pegasus/4.5.0/rhel6.6_gnu4.4.7/pegasus-4.5.0/bin/pegasus-analyzer", line 1529, in <module>
    analyze_db(options.config_properties)
  File "/sw/redhat6/pegasus/4.5.0/rhel6.6_gnu4.4.7/pegasus-4.5.0/bin/pegasus-analyzer", line 1007, in analyze_db
    total = workflow_stats.get_total_jobs_status()
  File "/autofs/nccs-svm1_sw/redhat6/pegasus/4.5.0/rhel6.6_gnu4.4.7/pegasus-4.5.0/lib64/python2.6/site-packages/Pegasus/db/workflow/stampede_statistics.py", line 392, in get_total_jobs_status
    q = q.filter(Workflow.wf_id == self._wfs[0])
IndexError: list index out of range​

It should probably give a more user-friendly output.

**Reporter:** @juve
**Resolution:** Fixed
**Watchers:**
@juve
@mayani

**Comment by mayani** [comment]
**Author:** @mayani

Raise exception instead of returning False
