### ISSUE TITLE
[PM-1039] pegasus-analyzer fails with: TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1153]
This happens when the workflow fails due to DAGMAN_LOG_ON_NFS_IS_ERROR when the submit dir is on NFS. It looks like this may have been triggered by an RPM update and a changed Condor default. The dag.dagman.out log contains:

ERROR: log file /path/to/workflow-0.dag.nodes.log is on NFS.

The workflow starts, and some tables in the DB get populated, but no jobs are submitted. In particular, the job_instance, jobstate, and invocation tables are all empty.

pegasus-analyzer 
Traceback (most recent call last):
 File "/sw/redhat6/pegasus/4.5.3/bin/pegasus-analyzer", line 1572, in <module>
   analyze_db(options.config_properties)
 File "/sw/redhat6/pegasus/4.5.3/bin/pegasus-analyzer", line 1021, in analyze_db
   unsubmitted = total - success - failed
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

**Reporter:** @juve
**Resolution:** Fixed
**Watchers:**
@juve
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

In addition, we do check for the NFS error condition. 

Sample message

************************************Summary*************************************

 Submit Directory   : /lfs1/work/monitord/bugs/#1153/20160125T152725-0800/
 Total jobs         :     16 (100.00%)
 # jobs succeeded   :      0 (0.00%)
 # jobs failed      :      0 (0.00%)
 # jobs unsubmitted :     16 (100.00%)

 Looks like workflow did not start
 HTCondor DAGMan NFS ERROR condition detected in /lfs1/work/monitord/bugs/#1153/20160125T152725-0800//*dagman.out
 01/25/16 15:27:27 Error: log file /nfs/asd2/vahi/Pegasus/git/pegasus/local-blackdiamond/work/dags/vahi/pegasus/blackdiamond/20160125T152725-0800/./blackdiamond-0.dag.nodes.log on NFS

 HTCondor DAGMan expects submit directories to be NOT NFS mounted.
 Set your submit directory to a directory on the local filesystem OR set HTCondor configuration DAGMAN_LOG_ON_NFS_IS_ERROR to False

**Comment by mayani** [comment]
**Author:** @juve

I'm not sure we should recommend that they set DAGMAN_LOG_ON_NFS_IS_ERROR=False. The documentation says that you can also solve this problem by setting CREATE_LOCKS_ON_LOCAL_DISK=True and ENABLE_USERLOG_LOCKING=True. That might be a safer solution. Maybe we should ask Kent?
