### ISSUE TITLE
[PM-1069] Dashboard invocation page gives an error if the task has no invocation record

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1183]
When I click on the invocation details view in the dashboard for auxiliary jobs, that I get the Unknown Error page. I think it is because these jobs don't have an invocation record. The exception is below.

2016-03-02 06:25:11,911:ERROR:Pegasus.service.dashboard.views(577): No row was found for one()
Traceback (most recent call last):
  File "/Users/juve/Workspace/pegasus/dist/pegasus-4.7.0dev/lib/pegasus/externals/python/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/juve/Workspace/pegasus/dist/pegasus-4.7.0dev/lib/pegasus/externals/python/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/juve/Workspace/pegasus/dist/pegasus-4.7.0dev/lib/pegasus/python/Pegasus/service/dashboard/views.py", line 291, in invocation
    invocation = dashboard.get_invocation_information(wf_id, job_id, job_instance_id, invocation_id)
  File "/Users/juve/Workspace/pegasus/dist/pegasus-4.7.0dev/lib/pegasus/python/Pegasus/service/dashboard/dashboard.py", line 491, in get_invocation_information
    invocation = workflow.get_invocation_information(job_id, job_instance_id, invocation_id)
  File "/Users/juve/Workspace/pegasus/dist/pegasus-4.7.0dev/lib/pegasus/python/Pegasus/service/dashboard/queries.py", line 738, in get_invocation_information
    return q.one()
  File "/Users/juve/Workspace/pegasus/dist/pegasus-4.7.0dev/lib/pegasus/externals/python/sqlalchemy/orm/query.py", line 2215, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
2016-03-02 06:25:11,925:INFO:werkzeug(87): 127.0.0.1 - - [02/Mar/2016 06:25:11] "GET /u/juve/r/80/w/1/j/3/ji/1/i/1 HTTP/1.1" 200 -

**Reporter:** @juve
**Resolution:** Fixed
**Watchers:**
@juve
@mayani
**Attachments:**

**Comment by mayani** [comment]
**Author:** @juve

The dashboard should probably display an error message indicating that no invocation record exists for the task. It isn't clear whether we should try to create an invocation record for it in the monitord loader.

**Comment by mayani** [comment]
**Author:** @mayani

Used outerjoin between Job, and Task to resolve the issue.
