### ISSUE TITLE
[PM-1070] monitord should handle case where jobs have missing JOB_FAILURE/JOB_TERMINATED events

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1184]
in the case where a job has missing job terminated and job failure events, but has post script terminated and failure event, monitord fails with non null integrity constraint when populating the invocation end event for the task making up the job. 

2016-03-02 07:04:30,348:ERROR:Pegasus.db.modules.stampede_loader.Analyzer(426): (IntegrityError) NOT NULL constraint failed: invocation.exitcode u'INSERT INTO invocation (job_instance_id, task_submit_seq, start_time, remote_duration, remote_cpu_time, exitcode, transformation, executable, argv, abs_task_id, wf_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' (182208, 1, 1455253988.0, 957.0, None, None, 'inspiral-BBH02_INJ-H1_ID156', '/usr1/amber.lenon/pycbc-tmp.cqBQirspEl/work/./main_ID0000001.000/inspiral-BBH02_INJ-H1_ID156_ID0030745.sh', None, 'ID0030745', 1)
Traceback (most recent call last):
  File "/Volumes/Work/lfs1/devel/Pegasus/git/pegasus/lib/pegasus/python/Pegasus/db/modules/stampede_loader.py", line 423, in individual_commit
    event.commit_to_db(self.session)
  File "/Volumes/Work/lfs1/devel/Pegasus/git/pegasus/lib/pegasus/python/Pegasus/db/schema.py", line 113, in commit_to_db
    self._commit(session, batch)
  File "/Volumes/Work/lfs1/devel/Pegasus/git/pegasus/lib/pegasus/python/Pegasus/db/schema.py", line 103, in _commit
    session.flush()
  File "/Volumes/Work/lfs1/devel/Pegasus/git/pegasus/lib/pegasus/externals/python/sqlalchemy/orm/scoping.py", line 149, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Volumes/Work/lfs1/devel/Pegasus/git/pegasus/lib/pegasus/externals/python/sqlalchemy/orm/session.py", line 1814, in flush
    self._flush(objects)
  File "/Volumes/Work/lfs1/devel/Pegasus/git/pegasus/lib/pegasus/externals/python/sqlalchemy/orm/session.py", line 1896, in _flush
    flush_context.execute()
  File "/Volumes/Work/lfs1/devel/Pegasus/git/pegasus/lib/pegasus/externals/python/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/Volumes/Work/lfs1/devel/Pegasus/git/pegasus/lib/pegasus/externals/python/sqlalchemy/orm/unitofwork.py", line 525, in execute
    uow
  File "/Volumes/Work/lfs1/devel/Pegasus/git/pegasus/lib/pegasus/externals/python/sqlalchemy/orm/persistence.py", line 63, in save_obj
    table, insert)
  File "/Volumes/Work/lfs1/devel/Pegasus/git/pegasus/lib/pegasus/externals/python/sqlalchemy/orm/persistence.py", line 565, in _emit_insert_statements
    execute(statement, params)
  File "/Volumes/Work/lfs1/devel/Pegasus/git/pegasus/lib/pegasus/externals/python/sqlalchemy/engine/base.py", line 664, in execute
    params)
  File "/Volumes/Work/lfs1/devel/Pegasus/git/pegasus/lib/pegasus/externals/python/sqlalchemy/engine/base.py", line 764, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Volumes/Work/lfs1/devel/Pegasus/git/pegasus/lib/pegasus/externals/python/sqlalchemy/engine/base.py", line 878, in _execute_context
    context)
  File "/Volumes/Work/lfs1/devel/Pegasus/git/pegasus/lib/pegasus/externals/python/sqlalchemy/engine/base.py", line 871, in _execute_context
    context)
  File "/Volumes/Work/lfs1/devel/Pegasus/git/pegasus/lib/pegasus/externals/python/sqlalchemy/engine/default.py", line 320, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (IntegrityError) NOT NULL constraint failed: invocation.exitcode u'INSERT INTO invocation (job_instance_id, task_submit_seq, start_time, remote_duration, remote_cpu_time, exitcode, transformation, executable, argv, abs_task_id, wf_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' (182208, 1, 1455253988.0, 957.0, None, None, 'inspiral-BBH02_INJ-H1_ID156', '/usr1/amber.lenon/pycbc-tmp.cqBQirspEl/work/./main_ID0000001.000/inspiral-BBH02_INJ-H1_ID156_ID0030745.sh', None, 'ID0030745', 1)
2016-03-02 07:04:30,349:ERROR:Pegasus.db.modules.stampede_loader.Analyzer(427): Insert failed for event <class 'Pegasus.db.schema.Invocation'>:
  * wf_id : 1
  * job_instance_id : 182208
  * executable : /usr1/amber.lenon/pycbc-tmp.cqBQirspEl/work/./main_ID0000001.000/inspiral-BBH02_INJ-H1_ID156_ID0030745.sh
  * job_submit_seq : 182208
  * abs_task_id : ID0030745
  * wf_uuid : ec1f3107-74d1-40cb-b4d9-4653aabf0591
  * start_time : 1455253988.0
  * ts : 1455254945.0
  * event : stampede.inv.end
  * task_submit_seq : 1
  * remote_duration : 957
  * invocation_id : None
  * exec_job_id : inspiral-BBH02_INJ-H1_ID156_ID0030745
  * transformation : inspiral-BBH02_INJ-H1_ID156

**Reporter:** @duncan-brown
**Resolution:** Fixed
**Watchers:**
@vahi
**Attachments:**

**Comment by mayani** [comment]
**Author:** @vahi

corbusier:main_ID0000001.000 vahi$ grep inspiral-BBH02_INJ-L1_ID157_ID0042136 jobstate.log
1455117586 inspiral-BBH02_INJ-L1_ID157_ID0042136 SUBMIT 2718190.0 osg - 52479
1455117821 inspiral-BBH02_INJ-L1_ID157_ID0042136 EXECUTE 2718190.0 osg - 52479
1455118225 inspiral-BBH02_INJ-L1_ID157_ID0042136 JOB_TERMINATED 2718190.0 osg - 52479
1455118225 inspiral-BBH02_INJ-L1_ID157_ID0042136 JOB_FAILURE 255 osg - 52479
1455118225 inspiral-BBH02_INJ-L1_ID157_ID0042136 POST_SCRIPT_STARTED 2718190.0 osg - 52479
1455118230 inspiral-BBH02_INJ-L1_ID157_ID0042136 POST_SCRIPT_TERMINATED 2718190.0 osg - 52479
1455118230 inspiral-BBH02_INJ-L1_ID157_ID0042136 POST_SCRIPT_FAILURE 1 osg - 52479
1455206395 inspiral-BBH02_INJ-L1_ID157_ID0042136 SUBMIT 2837217.0 osg - 130087
1455206940 inspiral-BBH02_INJ-L1_ID157_ID0042136 EXECUTE 2837217.0 osg - 130087
1455209733 inspiral-BBH02_INJ-L1_ID157_ID0042136 JOB_RECONNECT_FAILED 2837217.0 osg - 130087
1455209838 inspiral-BBH02_INJ-L1_ID157_ID0042136 EXECUTE 2837217.0 osg - 130087
1455211080 inspiral-BBH02_INJ-L1_ID157_ID0042136 JOB_TERMINATED 2837217.0 osg - 130087
1455211080 inspiral-BBH02_INJ-L1_ID157_ID0042136 JOB_FAILURE 1 osg - 130087
1455211080 inspiral-BBH02_INJ-L1_ID157_ID0042136 POST_SCRIPT_STARTED 2837217.0 osg - 130087
1455211085 inspiral-BBH02_INJ-L1_ID157_ID0042136 POST_SCRIPT_TERMINATED 2837217.0 osg - 130087
1455211085 inspiral-BBH02_INJ-L1_ID157_ID0042136 POST_SCRIPT_FAILURE 1 osg - 130087
1455254395 inspiral-BBH02_INJ-L1_ID157_ID0042136 SUBMIT 2907357.0 osg - 183767
1455254648 inspiral-BBH02_INJ-L1_ID157_ID0042136 EXECUTE 2907357.0 osg - 183767
1455254945 inspiral-BBH02_INJ-L1_ID157_ID0042136 POST_SCRIPT_TERMINATED 2907357.0 osg - 183767
1455254945 inspiral-BBH02_INJ-L1_ID157_ID0042136 POST_SCRIPT_FAILURE 1 osg - 183767
1455257296 inspiral-BBH02_INJ-L1_ID157_ID0042136 SUBMIT 2910181.0 osg - 185489
1455258513 inspiral-BBH02_INJ-L1_ID157_ID0042136 EXECUTE 2910181.0 osg - 185489
1455259894 inspiral-BBH02_INJ-L1_ID157_ID0042136 JOB_TERMINATED 2910181.0 osg - 185489
1455259894 inspiral-BBH02_INJ-L1_ID157_ID0042136 JOB_SUCCESS 0 osg - 185489
1455259894 inspiral-BBH02_INJ-L1_ID157_ID0042136 POST_SCRIPT_STARTED 2910181.0 osg - 185489
1455259899 inspiral-BBH02_INJ-L1_ID157_ID0042136 POST_SCRIPT_TERMINATED 2910181.0 osg - 185489
1455259899 inspiral-BBH02_INJ-L1_ID157_ID0042136 POST_SCRIPT_SUCCESS 0 osg - 185489


In between for one of the job retries we have 
455254395 inspiral-BBH02_INJ-L1_ID157_ID0042136 SUBMIT 2907357.0 osg - 183767
1455254648 inspiral-BBH02_INJ-L1_ID157_ID0042136 EXECUTE 2907357.0 osg - 183767
1455254945 inspiral-BBH02_INJ-L1_ID157_ID0042136 POST_SCRIPT_TERMINATED 2907357.0 osg - 183767
1455254945 inspiral-BBH02_INJ-L1_ID157_ID0042136 POST_SCRIPT_FAILURE 1 osg - 183767

with the missing events

**Comment by mayani** [comment]
**Author:** @vahi

We set the main exitcode to the postscript exitcode before parsing the kickstart output file. This takes care of the case where there are missing JOB_TERMINATED| JOB_SUCCESS|JOB_FAILURE events for the job instance, and the kickstart record is empty.

**Comment by mayani** [comment]
**Author:** @vahi

the attached file, has a pared down dagman.out and relevant files, that exhibit this symptom.
