### ISSUE TITLE
[PM-1114] pegasus-plan issue

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1228]
could please let me know what does the following error mean :
 pegasus-plan  --conf pegasus.properties  --dax ihope.dax --dir /scratch/jayanti/ihope/log/H1L1V1-ihope-931035296-100000.qKOiv_ --relative-dir . -s local --nocleanup -f --submit 
2016.07.26 10:39:51.847 IST: [WARNING]  --nocleanup option is deprecated. Use --cleanup none   
Job ligolw_cbc_hardware_inj_page_ID000050 Change in level to 3
execution sites size -> 1 local-->0,
2016.07.26 10:39:52.405 IST: [FATAL ERROR]  
 [1] java.lang.RuntimeException: Unable to generate code at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:679)
 [2] java.lang.RuntimeException: Unparsed component  of the command line argument string:  --dir datafind --output-dir datafind -Dpegasus.dagman.datafind.maxjobs=20 -Dpegasus.dagman.thinca.maxjobs=30 -Dpegasus.dagman.trigbank.maxjobs=30 -Dpegasus.dagman.coire.maxjobs=30 -Dpegasus.dagman.sire.maxjobs=30 --cluster horizontal  --force  --cache /home/jayanti/LIGO/ihope/931035296-931135296/pegasus-pfn-cache-931035296-931135296.cache --output-site local -vvvvvv --dax /home/jayanti/LIGO/ihope/931035296-931135296/datafind/inspiral_hipe_datafind.dax  at edu.isi.pegasus.planner.client.CPlanner.parseCommandLineArguments(CPlanner.java:1019)

**Reporter:** @jayanti-prasad
**Resolution:** Won't Fix
**Watchers:**
@duncan-brown
@jayanti-prasad
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

In ihope.dax there will be dax jobs in there.
in the arguments there, it looks that you -Dpegasus.dagman.datafind.maxjobs=20 -Dpegasus.dagman.thinca.maxjobs=30 -Dpegasus.dagman.trigbank.maxjobs=30 -Dpegasus.dagman.coire.maxjobs=30 -Dpegasus.dagman.sire.maxjobs=30  after the other arguments.

All the arguments -Dkey=value should go first .
So right order would be 
 -Dpegasus.dagman.datafind.maxjobs=20 -Dpegasus.dagman.thinca.maxjobs=30 -Dpegasus.dagman.trigbank.maxjobs=30 -Dpegasus.dagman.coire.maxjobs=30 -Dpegasus.dagman.sire.maxjobs=30 --dir datafind --output-dir datafind--cluster horizontal --force --cache /home/jayanti/LIGO/ihope/931035296-931135296/pegasus-pfn-cache-931035296-931135296.cache --output-site local -vvvvvv --dax /home/jayanti/LIGO/ihope/931035296-931135296/datafind/inspiral_hipe_datafind.dax

**Comment by mayani** [comment]
**Author:** @vahi

@jayanti-prasadwas this resolved for you?

**Comment by mayani** [comment]
**Author:** @jayanti-prasad

1. since that ordering is there at multiple places and I could not figure out where to make changes such that 
it comes automatically.
2. another issue I have found is that somehow If I manage to set up pegasus workdir  I do not get 'braindump'
  file which is quite strange.

**Comment by mayani** [comment]
**Author:** @vahi

you can modify the dax'es by hand before submitting. LIGO does not generate DAX'es as part of workflow execution

**Comment by mayani** [comment]
**Author:** @duncan-brown

lalapps_ihope is depricated and workflow support is likely broken by now.

**Comment by mayani** [comment]
**Author:** @vahi

lalapps_ihope is deprecated. pycbc needs to be used

**Comment by mayani** [comment]
**Author:** @jayanti-prasad

yes.. I know that so I am mostly focusing on pycbc although I am getting issues with that 
also but those are not related to pegasus. thanks.
