### ISSUE TITLE
[PM-1115] Pegasus to check for cyclic dependencies in the DAG

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1229]
One of our new users has tripped over an error that was triggered because of cyclic dependencies in the DAG.   Because of the cyclic dependency, the planner does not assign a site to all jobs in the SiteSelector. As a result the planning fails with an error that is not related to the fact that there is a cyclic dependency.

**Reporter:** @vahi
**Resolution:** Fixed
**Watchers:**
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

On Jul 26, 2016, at 8:13 PM, Karan Vahi <vahi@isi.edu> wrote:

Looks like that in your workflow structure there is a cyclical dependency somewhere

[DEBUG]  Adding Data Dependency edge Normalize_RigidMean_PROJECT-Project_i2_Normalize_RigidMean -> Normalize_RigidWarp_ID-100307_i3_Normalize_RigidWarp 

Pegasus added the above dependency based on inputs and outputs you specified. Is the above correct?

Karan

On Jul 26, 2016, at 3:27 PM, Andrew Schoen <schoen.andrewj@gmail.com> wrote:

Submit directory should be the same:
`/home/schoen/Scripts/Testing/working/condorsubmit`

I added the new executables to the tc.text file, following the examples you had, and placed them in the executables directory (/home/schoen/Scripts/dipa-workflow/executables/).

Thanks for all your help!
Andy

On Tue, Jul 26, 2016 at 5:01 PM, Karan Vahi <vahi@isi.edu> wrote:
What is the submit directory for the workflow?

Karan


On Jul 26, 2016, at 2:09 PM, Andrew Schoen <notifications@github.com> wrote:

Looks like we can't map Normalize_RigidWarp. Everything seems to be similar to the previous steps in tc.text, so I'm not quite sure what is breaking it. Possibly that multiple steps re-use it?

2016.07.26 15:56:57.616 CDT: [ERROR]  Site Selector (Random Site Selection) could not map job dipa::Normalize_RigidWarp to any site 
2016.07.26 15:56:57.617 CDT: [FATAL ERROR]  java.lang.RuntimeException: Site Selector (Random Site Selection) could not map job dipa::Normalize_RigidWarp to any site
    at edu.isi.pegasus.planner.refiner.InterPoolEngine.scheduleJobs(InterPoolEngine.java:306)
    at edu.isi.pegasus.planner.refiner.InterPoolEngine.determineSites(InterPoolEngine.java:215)
    at edu.isi.pegasus.planner.refiner.MainEngine.runPlanner(MainEngine.java:179)
    at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:643)
    at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:364)
    at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:245)
