### ISSUE TITLE
[PM-1124] Hashed Output Mappers throw unable to instantiate error

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1238]
[8:41 AM] Mats Rynge: #pegasus.dir.storage.mapper = Flat
#pegasus.dir.storage.deep = True
pegasus.dir.storage.mapper = Hashed
[8:41 AM] Mats Rynge: He gets:
[8:41 AM] Mats Rynge: 2016-09-20 10:35:24,031 fsurfer.log  INFO    : Pegasus output: 2016.09.20 10:35:23.839 CDT: [FATAL ERROR]
[1]: Instantiating Output Mapper at edu.isi.pegasus.planner.transfer.mapper.OutputMapperFactory.loadInstance(OutputMapperFactory.java:161)
[2]: Invalid static initializer method name for edu.isi.pegasus.planner.transfer.mapper.impl.Hashed at java.io.File.<init>(File.java:317)
[8:41 AM] Mats Rynge: So slightly different error, but pretty much the same

**Reporter:** @rynge
**Resolution:** Fixed
**Watchers:**
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

If pegasus.dir.storage.deep is set to true, then the relative submit|execution directory is also replaced on the output side before the mappers are applied. 
By default, internally planner now sets the relative-submit always, the site store needs to fall back on the relative-submit if relative-dir is not specified. 

the output mappers documentation has been updated to reflect the logic
https://pegasus.isi.edu/docs/4.6.3dev/ref_output_mapper.php

**Comment by mayani** [comment]
**Author:** @vahi

was triggered by fix for #1227
