### ISSUE TITLE
[PM-1225] hierarchal workflows planning in sharedfs fails with worker package staging set

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1339]
2017.11.01 10:42:43.288 PDT: [FATAL ERROR]  
[1] java.lang.RuntimeException: Unable to generate code at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:673)
[2] java.lang.RuntimeException: Unable to figure out worker package location for job subdax_000001_ID0000001.pre at edu.isi.pegasus.planner.code.gridstart.PegasusLite.enableForWorkerNodeExecution(PegasusLite.java:543)

**Reporter:** @rynge
**Resolution:** Fixed
**Watchers:**
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

Resolved on November 3, 2017
