### ISSUE TITLE
[PM-1261] PMC .in files are not generated into the 00/00 pattern folder

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1375]
Currently, when planning a workflow that has a job defined to use PMC, the .in files are generated in the workflow folder not into the 00/00 pattern folder.

**Reporter:** @rafaelfsilva
**Resolution:** Fixed
**Watchers:**
@rafaelfsilva
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

@rafaelfsilvacan you confirm if it works now for you.

**Comment by mayani** [comment]
**Author:** @vahi

our nightly tests failed
Planning the workflow...
04-Apr-2018 18:47:07	2018.04.04 18:47:07.506 PDT: [FATAL ERROR] 
04-Apr-2018 18:47:07	[1] java.lang.RuntimeException: Unable to generate code at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:673)
04-Apr-2018 18:47:07	[2] java.lang.ClassCastException: edu.isi.pegasus.planner.classes.ADag cannot be cast to edu.isi.pegasus.planner.classes.AggregatedJob at edu.isi.pegasus.planner.cluster.aggregator.MPIExec.generatePMCInputFile(MPIExec.java:164)
04-Apr-2018 18:47:07	Planning failed
04-Apr-2018 18:47:07	Fai

**Comment by mayani** [comment]
**Author:** @vahi

the fix is also breaking a test where we are using the pegasus-lite-local wrapper for running things locally and using condor file transfer

**Comment by mayani** [comment]
**Author:** @vahi

@rafaelfsilvaplease try and see if it works now.
