### ISSUE TITLE
[PM-19] pegasus-plan fails on workflow with no input files

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#140]
I have a workflow without any input files. When I try to plan it I get this error:

2007.11.19 18:03:03.206 PST: [ERROR] Problem while connecting with the Replica Catalog: null
2007.11.19 18:03:03.207 PST: [FATAL ERROR] 
 [1] java.lang.RuntimeException: Problem while connecting with the Replica Catalog:  at org.griphyn.cPlanner.engine.ReplicaCatalogBridge.initialize(ReplicaCatalogBridge.java:249)
 [2] java.lang.NullPointerException: null at org.griphyn.cPlanner.engine.ReplicaCatalogBridge.initialize(ReplicaCatalogBridge.java:237)
2007.11.19 18:03:03.207 PST: [WARNING] Non-zero exit-code 1

I am using the SimpleFile replica catalog with the -force option. The problem seems to be in ReplicaCatalogBridge. It looks like it doesn't create a replica catalog object if there are no lfns to look up, but then it tries to look up the lfns by referencing the null replica catalog.

**Reporter:** @juve
**Resolution:** Fixed
**Watchers:**
Gaurang Mehta (gmehta)
@scallag

**Comment by mayani** [comment]
**Author:** @vahi

**Comment by mayani** [comment]
**Author:** @vahi

Scott also tripped on this.

**Comment by mayani** [comment]
**Author:** @vahi

I fixed this and have checked the code in.
