### ISSUE TITLE
[PM-1300] Planning error when image is of type singularity and source is docker hub

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1414]
Pegasus fails to plan a workflow that has a container of type singularity and the image url points to docker hub.

Example TC:
cont hic_hq_image {
	type "singularity"
	image "docker:///papajim/hic_hq:latest"
}

Error Message:
2018.09.13 15:55:24.219 PDT: [FATAL ERROR]  
 [1]:  Unable to instantiate Transformation Catalog  at edu.isi.pegasus.planner.catalog.transformation.TransformationFactory.loadInstance(TransformationFactory.java:172)
 [2]: edu.isi.pegasus.planner.catalog.transformation.impl.Text caught edu.isi.pegasus.planner.parser.ScannerException line 8:  at edu.isi.pegasus.planner.parser.TransformationCatalogTextParser.parse(TransformationCatalogTextParser.java:236)
 [3]: Unable to compute singularity extension from url url -> docker:///papajim/hic_hq:latest , protocol -> docker , host ->  , path -> /papajim/hic_hq:latest , url-prefix -> docker:// at edu.isi.pegasus.planner.catalog.transformation.classes.Container.computeLFN(Container.java:184) 
ERROR while logging metrics The metrics file location is not yet initialized

Planning the workflow is successful when I I change the container specification in the transformation catalog to type "docker" :
cont hic_hq_image {
	type "docker"
	image "docker:///papajim/hic_hq:latest"
}

I have attached a verbose output from the planner. I've tested this with 4.8.4, but the output is from 4.8.2. Still the same error though.

**Reporter:** @papajim
**Resolution:** Fixed
**Watchers:**
@papajim
@vahi
**Attachments:**

**Comment by mayani** [comment]
**Author:** @vahi

i pushed a planner fix. please try and see if pegasus-transfer still works with docker hub url and does not get confused.

**Comment by mayani** [comment]
**Author:** @papajim

Planning works as expected !!!
We need to change pegasus-transfer though. It uses docker pull and docker save, instead of singularity pull. Because of that, singularity cannot recognize the container format and job fails.

pegasus-transfer log:
2018-09-13 16:59:43,845    INFO:  /usr/bin/docker pull "papajim/hic_hq:latest" && /usr/bin/docker save -o "/home/georgepap/GitHub/papajim/HIC-HQ-Workflow/workflow/scratch/georgepap/pegasus/hic_wf/run0001/./hic_hq_image.simg" "papajim/hic_hq:latest"

**Comment by mayani** [comment]
**Author:** @vahi

planner now generates an attribute type on the destination url to indicate what container to create
 { "type": "transfer",
   "linkage": "input",
   "lfn": "centos-pegasus.simg",
   "id": 1,
   "src_urls": [
     { "site_label": "local", "url": "file:///Volumes/Work/lfs1/work/pegasus-features/#1273/work/vahi/pegasus/blackdiamond/run0018/00/00/centos-pegasus.simg", "checkpoint": "false" }
   ],
   "dest_urls": [
     { "site_label": "local", "url": "symlink://$PWD/centos-pegasus.simg" "type": "cont.singularity" }
   ] }

**Comment by mayani** [comment]
**Author:** @vahi

@papajim please update master and try . we have pushed the changes

**Comment by mayani** [comment]
**Author:** @papajim

@vahi The changes seem to be working fine with the test workflow I have !
You can mark this as resolved.
