### ISSUE TITLE
[PM-1301] Python exception raised when using MySQL for stampede DB

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1415]
[2:52 PM] Rajiv Mayani: 2018-09-20 14:51:43,425:ERROR:pegasus-monitord(970): Traceback (most recent call last):
  File "/data/workspace/pegasus/pegasus/dist/pegasus-4.9.0dev/bin/pegasus-monitord", line 967, in <module>
    props=props, db_type=connection.DBType.WORKFLOW, backup = backup)
  File "/data/workspace/pegasus/pegasus/dist/pegasus-4.9.0dev/lib/pegasus/python/Pegasus/monitoring/event_output.py", line 430, in create_wf_event_sink
    del sink_props["url"]
AttributeError: Properties instance has no attribute '__delitem__'

Happens when pegasus.catalog.workflow.url = mysql://root:pegasus123@localhost

**Reporter:** @mayani
**Resolution:** Fixed
**Watchers:**
@mayani
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

@mayanican you check please if the fix works for you. if so resolve and close. thanks
