### ISSUE TITLE
[PM-1304] pegasus-transfer should support docker->singularity pulls

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1418]
the passed type attribute on destination url will be 
- cont.docker OR
  cont.singularity

here is the same format
 { "type": "transfer",
   "linkage": "input",
   "lfn": "centos-pegasus.simg",
   "id": 1,
   "src_urls": [
     { "site_label": "local", "url": "file:///Volumes/Work/lfs1/work/pegasus-features/#1273/work/vahi/pegasus/blackdiamond/run0018/00/00/centos-pegasus.simg", "checkpoint": "false" }
   ],
   "dest_urls": [
     { "site_label": "local", "url": "symlink://$PWD/centos-pegasus.simg" "type": "cont.singularity" }
   ] }

**Reporter:** @vahi
**Resolution:** Fixed
**Watchers:**
@rynge
@vahi

**Comment by mayani** [comment]
**Author:** @rynge

This has been implemented, and a unit test has been added. Please use "type": "singularity". Example:

 { "type": "transfer",
   "lfn": "singularity-docker-image.tar.gz",
   "id": 3,
   "src_urls": [
     { "site_label": "computesite", "url": "docker://hello-world", "priority": 100 }
   ],
   "dest_urls": [
     { "site_label": "computesite", "url": "file://$PWD/singularity-docker-image.tar.gz", "type": "singularity" }
   ] }

Reassigning to Karan to he can update the planner.

**Comment by mayani** [comment]
**Author:** @vahi

type can now be container or docker when transferring containers

**Comment by mayani** [comment]
**Author:** @vahi

our tests are failing because of mismatched handlers??

example
https://bamboo.isi.edu/browse/PEGASUS-WT49-T044E-331/log 

dir : /lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT49-T044E/test/core/044-singularity-nonsharedfs-hub/montage-workflow-v2/work/1538073570
27-Sep-2018 11:42:16	
27-Sep-2018 11:42:16	------------------Task #1 - pegasus::transfer - None - stdout-------------------
27-Sep-2018 11:42:16	
27-Sep-2018 11:42:16	2018-09-27 11:41:27,123    INFO:  Reading URL pairs from stdin
27-Sep-2018 11:42:16	2018-09-27 11:41:27,124    INFO:  8 transfers loaded
27-Sep-2018 11:42:16	2018-09-27 11:41:27,124    INFO:  PATH=/usr/bin:/bin
27-Sep-2018 11:42:16	2018-09-27 11:41:27,124    INFO:  LD_LIBRARY_PATH=
27-Sep-2018 11:42:16	2018-09-27 11:41:27,174    INFO:  --------------------------------------------------------------------------------
27-Sep-2018 11:42:16	2018-09-27 11:41:27,174    INFO:  Starting transfers - attempt 1
27-Sep-2018 11:42:16	Traceback (most recent call last):
27-Sep-2018 11:42:16	  File "/lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT49-T044E/pegasus/bin/../bin/pegasus-transfer", line 4470, in <module>
27-Sep-2018 11:42:16	    main()
27-Sep-2018 11:42:16	  File "/lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT49-T044E/pegasus/bin/../bin/pegasus-transfer", line 4394, in main
27-Sep-2018 11:42:16	    ts = SimilarWorkSet(t_list, completed_q, failed_q)
27-Sep-2018 11:42:16	  File "/lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT49-T044E/pegasus/bin/../bin/pegasus-transfer", line 3565, in __init__
27-Sep-2018 11:42:16	    %(src_proto, dst_proto))
