### ISSUE TITLE
[PM-1315] Exception when data reuse removes all jobs.

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1429]
Planner raises exception in scenarios where data reuse deletes all jobs from the workflow.

java.lang.ArrayIndexOutOfBoundsException: 1
	at edu.isi.pegasus.planner.refiner.cleanup.InPlace.addCleanUpJobs(InPlace.java:109)
	at edu.isi.pegasus.planner.refiner.cleanup.InPlace.addCleanupJobs(InPlace.java:67)
	at edu.isi.pegasus.planner.refiner.CleanupEngine.addCleanupJobs(CleanupEngine.java:62)
	at edu.isi.pegasus.planner.refiner.MainEngine.runPlanner(MainEngine.java:262)
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:644)
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:365)
	at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:246)

**Reporter:** @mayani
**Resolution:** Fixed
**Watchers:**
@mayani
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

@mayani i pushed out a fix for the stage out job to not be created for canonical file url matches
however, i am unable to recreate this case, where cleanup fails for this case.

**Comment by mayani** [comment]
**Author:** @mayani

URL fix works. stage_out job was not created. No exception is raised now either. Issue can be closed.
