### ISSUE TITLE
[PM-22] ReplicaCatalogBuilder throws a NPE when running a workflow without any input file when using --force option

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#143]
If a workflow is being planned that does not have any defined input files. The ReplicaCatalogBuilder factory throws a NPE if the --force flag was passed. It works correctly when reduction is enabled.

**Reporter:** Gaurang Mehta (gmehta)
**Resolution:** Duplicate
**Watchers:**
Gaurang Mehta (gmehta)
@scallag

**Comment by mayani** [comment]
**Author:** @vahi

**Comment by mayani** [comment]
**Author:** @scallag

2008.01.28 14:20:08.962 PST: [ERROR] Problem while connecting with the Replica Catalog: null
2008.01.28 14:20:08.963 PST: [FATAL ERROR] 
 [1] java.lang.RuntimeException: Problem while connecting with the Replica Catalog:  at org.griphyn.cPlanner.engine.ReplicaCatalogBridge.initialize(ReplicaCatalogBridge.java:249)
 [2] java.lang.NullPointerException: null at org.griphyn.cPlanner.engine.ReplicaCatalogBridge.initialize(ReplicaCatalogBridge.java:237)
2008.01.28 14:20:08.963 PST: [WARNING] Non-zero exit-code 1
