### ISSUE TITLE
[PM-1316] Transformation that uses a regular file, but defines it in RC raises an exception, unlike in older versions

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1430]
If transformation is like below,
<transformation name="getSortedWords">
   <uses name="getSortedWords" executable="true"/>
   <uses name="io.sh" executable="true"/>
   <uses name="test.txt"/>
</transformation>

File test.txt is defined in RC like below,
<file name="test.txt">
   <pfn url="file:///.../test.txt"/>
</file>

I get an exception like, 
[FATAL ERROR]  java.lang.RuntimeException: There are no entries for the transformation "test.txt" in the TC
	at edu.isi.pegasus.planner.catalog.transformation.mapper.All.getSiteMap(All.java:106)
	at edu.isi.pegasus.planner.catalog.transformation.Mapper.getTCList(Mapper.java:175)
	at edu.isi.pegasus.planner.refiner.InterPoolEngine.handleFileTransfersForDependantExecutables(InterPoolEngine.java:633)
	at edu.isi.pegasus.planner.refiner.InterPoolEngine.handleExecutableFileTransfers(InterPoolEngine.java:506)
	at edu.isi.pegasus.planner.refiner.InterPoolEngine.scheduleJobs(InterPoolEngine.java:323)
	at edu.isi.pegasus.planner.refiner.InterPoolEngine.determineSites(InterPoolEngine.java:213)
	at edu.isi.pegasus.planner.refiner.MainEngine.runPlanner(MainEngine.java:187)
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:644)
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:365)
	at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:246)

**Reporter:** @mayani
**Resolution:** Fixed
**Watchers:**
@mayani
@vahi
**Attachments:**

**Comment by mayani** [comment]
**Author:** @vahi

the earlier behavior was an oversight

**Comment by mayani** [comment]
**Author:** @vahi

can you try putting explicitly executable = false for test.txt in the uses section of the compound transformation

**Comment by mayani** [comment]
**Author:** @vahi

this is because in the xml schema https://pegasus.isi.edu/documentation/schemas/dax-3.6/dax-3.6.html#element_uses_Link030BE9F0  the uses tag in compound element has a default value as true for executable attribute

**Comment by mayani** [comment]
**Author:** @vahi

the JAVA dax api should be fixed to generate uses with executable attribute always.

**Comment by mayani** [comment]
**Author:** @vahi

have updated the JAVA DAX API to generate executable = false for cases, when uses is encoded in a  transformation element and the file is a data file
