### ISSUE TITLE
[PM-1317] Pegasus plan fails on container task clustering

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1431]
Pegasus plan fails when I try to cluster container tasks based on label.
Same thing happens with docker and singularity.

Error msg:
2018.10.25 16:40:23.276 PDT: [FATAL ERROR]  
 [1] java.lang.RuntimeException: null at edu.isi.pegasus.planner.refiner.MainEngine.runPlanner(MainEngine.java:207)
 [2] java.lang.RuntimeException: Cannot cluster jobs with different types of containers associated. Container for job pointalert_ID0000012 - cont casa_image{
	type     	docker
	image    	file:///nfs/v5/georgpap/scratch/CASA-Workflow/bin/casa-app.tar
	image_site 	condorpool
}
does not match with job mvt_ID0000011 - cont casa_image{
	type     	docker
	image    	file:///nfs/v5/georgpap/scratch/CASA-Workflow/bin/casa-app.tar
	image_site 	condorpool
}
 at edu.isi.pegasus.planner.cluster.aggregator.Abstract.constructAbstractAggregatedJob(Abstract.java:317)

A version of this workflow can be found at workflow.isi.edu, in the following folder: /nfs/v5/georgpap/scratch/CASA-Workflow

**Reporter:** @papajim
**Resolution:** Fixed
**Watchers:**
@papajim
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

this is because i was doing a equals check on reference equality . however for jira item #1412 I had to implement the clone method and this broke as result

**Comment by mayani** [comment]
**Author:** @papajim

Pulled and tested the changes.
Planning now succeeds with the same containers, and workflow finishes successfully.
Tested different container types and different container files in the transformation catalog, and planning fails as expected !
