### ISSUE TITLE
[PM-1325] Debian build with incorrect dependencies

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1439]
https://download.pegasus.isi.edu/pegasus/debian/dists/squeeze/main/binary-amd64/Packages

Pegasus 4.9.0 is incompatible with openjdk-7-jre. In [2], you can see a related error.

However, the package file has the following information:
Depends: openjdk-8-jre | openjdk-8-jre-headless | openjdk-7-jre | openjdk-7-jre-headless | openjdk-6-jre | openjdk-6-jre-headless, perl, python, python-openssl, libc6 (>= 2.14), libgcc1 (>= 1:3.0), libmariadbclient18 (>= 5.5.36), libstdc++6 (>= 4.1.1), zlib1g (>= 1:1.1.4)

Therefore, it allows the installation of an incompatible version of java.

I hope that you can forward this email to the maintainers.

Best,

[1] https://download.pegasus.isi.edu/pegasus/debian/dists/squeeze/main/binary-amd64/Packages

[2] Error: pegasus and java 1.8.0
2018-11-06 11:10:32,430    INFO:  pegasus-plan --conf /home/mosorio/workflow/soykb/conf/distributed/pegasus.conf --dir . --relative-dir wf-20181106-111027 --sites execution --output-site isi_obelix --staging isi_obelix --dax soykb.dax
Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/isi/pegasus/planner/client/CPlanner : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

[mosorio@soykb soykb]$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**Reporter:** @mayani
**Resolution:** Fixed
**Watchers:**
@rafaelfsilva
@rynge
@mayani
@rafaelfsilva
@vahi

**Comment by mayani** [comment]
**Author:** @rynge

A fix for the dependency problem was already committed:

https://github.com/pegasus-isi/pegasus/commit/6386b5dc9d72c061dc055da4ec5c09fdba77327d

However, we might also need updates to common.sh to fully fix this issue (that is, handling alternatives).

**Comment by mayani** [comment]
**Author:** @vahi

@rynge@mayanithis is fixed now. right?

**Comment by mayani** [comment]
**Author:** @rynge

Fixed
