### ISSUE TITLE
[PM-1326] singularity suffix computed incorrectly

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1440]
I just tried to do a fresh run and found a different bug. Pegasus is ok with the singularity container being called pycbc-el7:latest, but not pycbc-el7:v1.13.0

2018.11.08 13:01:52.501 EST: [FATAL ERROR]  
[1]:  Unable to instantiate Transformation Catalog  at edu.isi.pegasus.planner.catalog.transformation.TransformationFactory.loadInstance(TransformationFactory.java:172)
[2]: edu.isi.pegasus.planner.catalog.transformation.impl.Text caught edu.isi.pegasus.planner.parser.ScannerException line 1511:  at edu.isi.pegasus.planner.parser.TransformationCatalogTextParser.parse(TransformationCatalogTextParser.java:236)
[3]: Invalid suffix .13.0 determined singularity image url url -> file://localhost/cvmfs/singularity.opensciencegrid.org/pycbc/pycbc-el7:v1.13.0 , protocol -> file , host -> localhost , path -> /cvmfs/singularity.opensciencegrid.org/pycbc/pycbc-el7:v1.13.0 , url-prefix -> file://localhost at edu.isi.pegasus.planner.catalog.transformation.classes.Container.computeLFN(Container.java:196) 
ERROR while logging metrics The metrics file location is not yet initialized
2018.11.08 13:01:52.504 EST: [DEBUG]  Exiting with non-zero exit-code 2 
2018.11.08 13:01:52.504 EST: [INFO] event.pegasus.planner planner.version 4.9.1dev  (0.557 seconds) - FINISHED

**Reporter:** @duncan-brown
**Resolution:** Fixed
**Watchers:**
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

handle tagged image names for determining singularity suffixes. added test cases also
