### ISSUE TITLE
[PM-1333] amqp endpoint errors should not disable database population for multiplexed sinks

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1447]
currently, for multiplexed endpoints unable to connect to an endpoint disables the population completely. 

....
2018-11-12 13:42:36,857:INFO:Pegasus.monitoring.event_output(455): Connecting workflow event sink to amqp://friend:donatedata@msgs.pegasus.isi.edu:5672/prod/workflows
2018-11-12 13:42:36,858:ERROR:pegasus-monitord(970): Traceback (most recent call last):
  File "/cvmfs/oasis.opensciencegrid.org/osg/projects/pegasus/rhel7/4.9.0dev-20181026/bin/pegasus-monitord", line 967, in <module>
    props=props, db_type=connection.DBType.WORKFLOW, backup = backup)
  File "/cvmfs/oasis.opensciencegrid.org/osg/projects/pegasus/rhel7/4.9.0dev-20181026/lib64/python2.7/site-packages/Pegasus/monitoring/event_output.py", line 451, in create_wf_event_sink
    return MultiplexEventSink(dest, enc, prefix, sink_props, **kw)
  File "/cvmfs/oasis.opensciencegrid.org/osg/projects/pegasus/rhel7/4.9.0dev-20181026/lib64/python2.7/site-packages/Pegasus/monitoring/event_output.py", line 374, in __init__
    prefix=prefix, props=endpoint_props, multiplexed = True, **kw)
  File "/cvmfs/oasis.opensciencegrid.org/osg/projects/pegasus/rhel7/4.9.0dev-20181026/lib64/python2.7/site-packages/Pegasus/monitoring/event_output.py", line 489, in create_wf_event_sink
    raise Exception("AMQP destination selected, but cannot import AMQP library")
Exception: AMQP destination selected, but cannot import AMQP library

Can we have amqplib installed or install 4.9.0 on osg-connect 
I remember you telling me it is a dependency for the RPM

**Reporter:** @rynge
**Resolution:** Fixed
**Watchers:**
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

this was happening because i was not disabling while creating event sinks. have pushed out a fix
