### ISSUE TITLE
[PM-1334] pegasus dagman is not exiting cleanly

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1448]
I'm seeing problem with monitord not exiting cleanly after the condor_dagman process has exited. This has happened a few times, so it's not a one-off. An example is currently job 16715729.0 on sugwg-osg.phy.syr.edu. The dagman process has exited:

11/28/18 12:24:25 **** condor_scheduniv_exec.16715729.0 (condor_DAGMAN) pid 2122725 EXITING WITH STATUS 1

However, monitord has not exited:

[dbrown@sugwg-osg ~]$ ps wwwwaux | grep o1-analysis-3-v1_13_0-LOSC_16_V1-0.dag.dagman.out
dbrown   2251055 10.4  0.2 494072 245656 ?       S    11:50  17:39 /usr/bin/python2.7 /usr/bin/pegasus-monitord -N o1-analysis-3-v1_13_0-LOSC_16_V1-0.dag.dagman.out

and so pegasus-dagman has not exited:

dbrown   2122719  0.0  0.0 199784 11668 ?        Ss   09:57   0:00 /usr/bin/python2.7 /usr/bin/pegasus-dagman -p 0 -f -l . -Lockfile o1-analysis-3-v1_13_0-LOSC_16_V1-0.dag.lock -AutoRescue 1 -DoRescueFrom 0 -Dag o1-analysis-3-v1_13_0-LOSC_16_V1-0.dag -MaxPre 1 -MaxPost 20 -Suppress_notification -CsdVersion $CondorVersion: 8.6.7 Oct 29 2017 BuildID: 422776 $ -Dagman /bin/condor_dagman

I'll leave this job in the queue so Karan can investigate.

**Reporter:** @duncan-brown
**Resolution:** Fixed
**Watchers:**
@duncan-brown
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

pegasus-dagman will wait for monitord to finish to ensure the stampede database is completely populated

**Comment by mayani** [comment]
**Author:** @duncan-brown

I think monitord is off in the weeds then:

[dbrown@sugwg-osg ~]$ strace -p 2251055
strace: Process 2251055 attached
select(0, NULL, NULL, NULL, {0, 785780}) = 0 (Timeout)
stat("/usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-finalization_ID0000002.000/o1-analysis-3-v1_13_0-LOSC_16_V1-finalization-0.dag.dagman.out", {st_mode=S_IFREG|0644, st_size=17162, ...}) = 0
stat("/usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/H1L1-FOREGROUND_MINIFOLLOWUP_FULL_DATA_FULL_CUMULATIVE_CAT_12H-1128299417-1083600.000/H1L1-FOREGROUND_MINIFOLLOWUP_FULL_DATA_FULL_CUMULATIVE_CAT_12H-1128299417-1083600.dag.dagman.out", {st_mode=S_IFREG|0644, st_size=368203, ...}) = 0
stat("/usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/L1-SINGLES_MINIFOLLOWUP_FULL_DATA_NONCOINC_NONCOINC-1128299417-1083600.000/L1-SINGLES_MINIFOLLOWUP_FULL_DATA_NONCOINC_NONCOINC-1128299417-1083600.dag.dagman.out", {st_mode=S_IFREG|0644, st_size=526979, ...}) = 0
stat("/usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/H1-SINGLES_MINIFOLLOWUP_FULL_DATA_SHORTDUR_SHORTDUR-1128299417-1083600.000/H1-SINGLES_MINIFOLLOWUP_FULL_DATA_SHORTDUR_SHORTDUR-1128299417-1083600.dag.dagman.out", {st_mode=S_IFREG|0644, st_size=506047, ...}) = 0
stat("/usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/L1-SINGLES_MINIFOLLOWUP_FULL_DATA_SHORTDUR_SHORTDUR-1128299417-1083600.000/L1-SINGLES_MINIFOLLOWUP_FULL_DATA_SHORTDUR_SHORTDUR-1128299417-1083600.dag.dagman.out", {st_mode=S_IFREG|0644, st_size=436901, ...}) = 0
stat("/usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/L1-SINGLES_MINIFOLLOWUP_FULL_DATA_MEDIUMDUR_MEDIUMDUR-1128299417-1083600.000/L1-SINGLES_MINIFOLLOWUP_FULL_DATA_MEDIUMDUR_MEDIUMDUR-1128299417-1083600.dag.dagman.out", {st_mode=S_IFREG|0644, st_size=446085, ...}) = 0
stat("/usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/H1-SINGLES_MINIFOLLOWUP_FULL_DATA_MEDIUMDUR_MEDIUMDUR-1128299417-1083600.000/H1-SINGLES_MINIFOLLOWUP_FULL_DATA_MEDIUMDUR_MEDIUMDUR-1128299417-1083600.dag.dagman.out", {st_mode=S_IFREG|0644, st_size=573710, ...}) = 0
stat("/usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/L1-SINGLES_MINIFOLLOWUP_FULL_DATA_LONGDUR_LONGDUR-1128299417-1083600.000/L1-SINGLES_MINIFOLLOWUP_FULL_DATA_LONGDUR_LONGDUR-1128299417-1083600.dag.dagman.out", {st_mode=S_IFREG|0644, st_size=503754, ...}) = 0
stat("/usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/H1-SINGLES_MINIFOLLOWUP_FULL_DATA_LONGDUR_LONGDUR-1128299417-1083600.000/H1-SINGLES_MINIFOLLOWUP_FULL_DATA_LONGDUR_LONGDUR-1128299417-1083600.dag.dagman.out", {st_mode=S_IFREG|0644, st_size=592523, ...}) = 0
stat("/usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/H1-SINGLES_MINIFOLLOWUP_FULL_DATA_NONCOINC_NONCOINC-1128299417-1083600.000/H1-SINGLES_MINIFOLLOWUP_FULL_DATA_NONCOINC_NONCOINC-1128299417-1083600.dag.dagman.out", {st_mode=S_IFREG|0644, st_size=524213, ...}) = 0
stat("/usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-0.stampede.db", {st_mode=S_IFREG|0644, st_size=349973504, ...}) = 0
open("/usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-0.stampede.db", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 9
fstat(9, {st_mode=S_IFREG|0644, st_size=349973504, ...}) = 0
fstat(9, {st_mode=S_IFREG|0644, st_size=349973504, ...}) = 0
stat("/usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-0.stampede.db", {st_mode=S_IFREG|0644, st_size=349973504, ...}) = 0
lseek(9, 0, SEEK_SET)                   = 0
read(9, "SQLite format 3\0\4\0\1\1\0@  \0\2\36\31\0\0057\v"..., 100) = 100
fstat(9, {st_mode=S_IFREG|0644, st_size=349973504, ...}) = 0
stat("/usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-0.stampede.db", {st_mode=S_IFREG|0644, st_size=349973504, ...}) = 0
close(9)                                = 0
stat("/home/dbrown/.pegasus/workflow.db", {st_mode=S_IFREG|0644, st_size=534528, ...}) = 0
open("/home/dbrown/.pegasus/workflow.db", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 9
fstat(9, {st_mode=S_IFREG|0644, st_size=534528, ...}) = 0
fstat(9, {st_mode=S_IFREG|0644, st_size=534528, ...}) = 0
stat("/home/dbrown/.pegasus/workflow.db", {st_mode=S_IFREG|0644, st_size=534528, ...}) = 0
lseek(9, 0, SEEK_SET)                   = 0
read(9, "SQLite format 3\0\4\0\1\1\0@  \0\0\23\0\0\0\2\n"..., 100) = 100
fstat(9, {st_mode=S_IFREG|0644, st_size=534528, ...}) = 0
stat("/home/dbrown/.pegasus/workflow.db", {st_mode=S_IFREG|0644, st_size=534528, ...}) = 0
close(9)                                = 0
select(0, NULL, NULL, NULL, {9, 997195}) = 0 (Timeout)

**Comment by mayani** [comment]
**Author:** @duncan-brown

It just keeps stating this sub-dag files, but they finished a long time ago:

[dbrown@sugwg-osg ~]$ tail /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/H1-SINGLES_MINIFOLLOWUP_FULL_DATA_NONCOINC_NONCOINC-1128299417-1083600.000/H1-SINGLES_MINIFOLLOWUP_FULL_DATA_NONCOINC_NONCOINC-1128299417-1083600.dag.dagman.out 
11/21/18 08:54:31 Of 111 nodes total:
11/21/18 08:54:31  Done     Pre   Queued    Post   Ready   Un-Ready   Failed
11/21/18 08:54:31   ===     ===      ===     ===     ===        ===      ===
11/21/18 08:54:31   111       0        0       0       0          0        0
11/21/18 08:54:31 0 job proc(s) currently held
11/21/18 08:54:31 Wrote metrics file H1-SINGLES_MINIFOLLOWUP_FULL_DATA_NONCOINC_NONCOINC-1128299417-1083600.dag.metrics.
11/21/18 08:54:31 Reporting metrics to Pegasus metrics server(s); output is in H1-SINGLES_MINIFOLLOWUP_FULL_DATA_NONCOINC_NONCOINC-1128299417-1083600.dag.metrics.out.
11/21/18 08:54:31 Running command </usr/libexec/condor/condor_dagman_metrics_reporter -f H1-SINGLES_MINIFOLLOWUP_FULL_DATA_NONCOINC_NONCOINC-1128299417-1083600.dag.metrics -t 100>
11/21/18 08:54:31 Warning: mysin has length 0 (ignore if produced by DAGMan; see gittrac #4987, #5031)
11/21/18 08:54:31 **** condor_scheduniv_exec.16634414.0 (condor_DAGMAN) pid 3719456 EXITING WITH STATUS 0

**Comment by mayani** [comment]
**Author:** @vahi

you are right 
[vahi@sugwg-osg work]$ grep H1-SINGLES_MINIFOLLOWUP_FULL_DATA_NONCOINC_NONCOINC-1128299417-1083600 monitord.log
2018-11-28 12:15:25,473:INFO:pegasus-monitord(1289): found new workflow to track: /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/H1-SINGLES_MINIFOLLOWUP_FULL_DATA_NONCOINC_NONCOINC-1128299417-1083600.000/H1-SINGLES_MINIFOLLOWUP_FULL_DATA_NONCOINC_NONCOINC-1128299417-1083600.dag.dagman.out
2018-11-28 12:15:25,474:INFO:Pegasus.monitoring.notifications(394): loading notifications from /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/H1-SINGLES_MINIFOLLOWUP_FULL_DATA_NONCOINC_NONCOINC-1128299417-1083600.000/H1-SINGLES_MINIFOLLOWUP_FULL_DATA_NONCOINC_NONCOINC-1128299417-1083600.notify

not sure where it is getting that from

can you upload these files o1-analysis-3-v1_13_0-LOSC_16_V1-0.dag.lib.err  o1-analysis-3-v1_13_0-LOSC_16_V1-0.dag.lib.out 
and then do pegasus-remove

i will try and run monitord in replay mode to see what is happening here

**Comment by mayani** [comment]
**Author:** @duncan-brown

[dbrown@sugwg-osg ~]$ cat /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-0.dag.lib.err 
2018-11-28 09:58:02,247:ERROR:pegasus-dagman(217): monitord is not running
2018-11-28 09:58:47,284:ERROR:pegasus-dagman(217): monitord is not running
2018-11-28 10:35:48,884:ERROR:pegasus-dagman(217): monitord is not running
2018-11-28 11:03:04,813:ERROR:pegasus-dagman(217): monitord is not running
2018-11-28 11:12:50,219:ERROR:pegasus-dagman(217): monitord is not running
2018-11-28 11:14:05,282:ERROR:pegasus-dagman(217): monitord is not running
2018-11-28 11:15:20,320:ERROR:pegasus-dagman(217): monitord is not running
2018-11-28 11:18:35,458:ERROR:pegasus-dagman(217): monitord is not running
2018-11-28 11:50:06,673:ERROR:pegasus-dagman(217): monitord is not running

**Comment by mayani** [comment]
**Author:** @duncan-brown

[dbrown@sugwg-osg ~]$ cat /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-0.dag.lib.out 
Pegasus LIB /usr/lib64/python2.7/site-packages
Pegasus LIB /usr/lib64/pegasus/externals/python
Pegasus BIN_DIR /usr/bin
Pegasus DAGMAN is  /usr/bin/pegasus-dagman
2018-11-28 09:57:47,235:INFO:pegasus-dagman(138): DAGMAN_COPY_TO_SPOOL is set to false

2018-11-28 09:57:47,237:INFO:pegasus-dagman(98): Launched Dagman with Pid 2122725
2018-11-28 09:57:47,238:INFO:pegasus-dagman(123): Launched Monitord with Pid 2122726
2018-11-28 09:58:02,247:INFO:pegasus-dagman(225): next monitord launch scheduled in about 20 seconds
2018-11-28 09:58:32,273:INFO:pegasus-dagman(123): Launched Monitord with Pid 2140531
2018-11-28 09:58:47,284:INFO:pegasus-dagman(225): next monitord launch scheduled in about 54 seconds
2018-11-28 09:59:47,337:INFO:pegasus-dagman(123): Launched Monitord with Pid 2141923
2018-11-28 10:35:48,884:INFO:pegasus-dagman(225): next monitord launch scheduled in about 20 seconds
2018-11-28 10:36:18,899:INFO:pegasus-dagman(123): Launched Monitord with Pid 2186469
2018-11-28 11:03:04,813:INFO:pegasus-dagman(225): next monitord launch scheduled in about 20 seconds
2018-11-28 11:03:34,841:INFO:pegasus-dagman(123): Launched Monitord with Pid 2198401
2018-11-28 11:12:50,219:INFO:pegasus-dagman(225): next monitord launch scheduled in about 20 seconds
2018-11-28 11:13:20,242:INFO:pegasus-dagman(123): Launched Monitord with Pid 2219383
2018-11-28 11:14:05,282:INFO:pegasus-dagman(225): next monitord launch scheduled in about 54 seconds
2018-11-28 11:15:05,308:INFO:pegasus-dagman(123): Launched Monitord with Pid 2220192
2018-11-28 11:15:20,320:INFO:pegasus-dagman(225): next monitord launch scheduled in about 148 seconds
2018-11-28 11:17:50,436:INFO:pegasus-dagman(123): Launched Monitord with Pid 2221258
2018-11-28 11:18:35,458:INFO:pegasus-dagman(225): next monitord launch scheduled in about 403 seconds
2018-11-28 11:25:20,719:INFO:pegasus-dagman(123): Launched Monitord with Pid 2224024
2018-11-28 11:50:06,673:INFO:pegasus-dagman(225): next monitord launch scheduled in about 20 seconds
2018-11-28 11:50:36,700:INFO:pegasus-dagman(123): Launched Monitord with Pid 2251055
Executing condor dagman ...

**Comment by mayani** [comment]
**Author:** @duncan-brown

[dbrown@sugwg-osg ~]$ pegasus-remove /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/
Job 16715729.0 marked for removal

Result: OK

**Comment by mayani** [comment]
**Author:** @duncan-brown

[dbrown@sugwg-osg ~]$ pegasus-run /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work
ERROR: It looks like the workflow is already running! If you are sure
       that is not the case, please remove the monitord.pid file and try
       again.

**Comment by mayani** [comment]
**Author:** @vahi

monitord.pid should have been deleted

does o1-analysis-3-v1_13_0-LOSC_16_V1-0.dag.lib.* files have any info?

**Comment by mayani** [comment]
**Author:** @vahi

this run has a lot of such errors
018-11-18 00:31:44,391:WARNING:pegasus-monitord(546): cannot find job_submit_seq for job: inspiral-FULL_DATA-H1_ID8_ID0005335
2018-11-18 00:31:44,391:WARNING:pegasus-monitord(546): cannot find job_submit_seq for job: inspiral-FULL_DATA-H1_ID8_ID0004003
Traceback (most recent call last):
  File "/usr/bin/pegasus-monitord", line 1259, in <module>
    process_output = process_dagman_out(workflow_entry.wf, workflow_entry.ml_buffer[0:ml_pos])
  File "/usr/bin/pegasus-monitord", line 655, in process_dagman_out
    my_job_submit_seq = add(wf, my_jobid, my_event, sched_id=my_sched_id)
  File "/usr/bin/pegasus-monitord", line 539, in add
    my_job_submit_seq = wf.add_job(jobid, event, sched_id=sched_id)
  File "/usr/lib64/python2.7/site-packages/Pegasus/monitoring/workflow.py", line 2191, in add_job
    job_submit_dir = self.determine_job_submit_directory(jobid, self._job_info[jobid][0])
KeyError: 'inspiral-FULL_DATA-H1_ID8_ID0005428'
2018-11-18 00:31:44,601:INFO:pegasus-monitord(185): DB flushing beginning
2018-11-18 00:31:44,601:INFO:Pegasus.db.workflow_loader.WorkflowLoader(1100): Executing final flush
2018-11

the .dag file is parsed for a workflow when monitord encounters  
Parsing  ...  in the .dag.dagman.out 

11/18/18 00:31:39 WARNING: forward resolution of sugwg-osg.phy.syr.edu doesn't match 10.5.2.3!
11/18/18 00:31:39 Workflow batch-name: <o1-analysis-3-v1_13_0-LOSC_16_V1-0.dag+16181491>
11/18/18 00:31:39 Workflow accounting_group: <>
11/18/18 00:31:39 Workflow accounting_group_user: <>
11/18/18 00:31:39 DAGMAN_LOG_ON_NFS_IS_ERROR setting: False
11/18/18 00:31:39 Default node log file is: </usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/./o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.dag.nodes.log>
11/18/18 00:31:39 Warning: the version (undefined) of this DAG's HTCondor submit file (created by condor_submit_dag) is invalid; continuing because of -AllowVersionMismatch flag
11/18/18 00:31:39 Note:  DAGMAN_MAX_JOBS_IDLE has been changed from the default setting; if your submit files create multiple procs, you should probably set DAGMAN_MAX_SUBMITS_PER_INTERVAL to 1
11/18/18 00:31:39 DAG Lockfile will be written to o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.dag.lock
11/18/18 00:31:39 DAG Input file is o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.dag
11/18/18 00:31:39 Parsing 1 dagfiles
11/18/18 00:31:39 Parsing o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.dag ...
11/18/18 00:31:39 Found rescue DAG number 2; running o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.dag.rescue002 in combination with normal DAG file

In monitord.log.000
018-11-17 02:14:40,877:INFO:pegasus-monitord(765): using dag o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.dag
2018-11-17 02:14:40,878:INFO:Pegasus.monitoring.workflow(680): DAGMan starting with condor id 16409990.0
2018-11-17 02:15:38,410:INFO:pegasus-monitord(1171): workflow /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.dag.dagman.out ended
2018-11-17 02:15:38,449:INFO:Pegasus.monitoring.workflow(1118): recovery file deleted: /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/monitord.recover
2018-11-17 02:15:38,449:INFO:pegasus-monitord(1345): finishing workflow: /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.dag.dagman.out
2018-11-18 00:31:38,216:INFO:pegasus-monitord(1289): found new workflow to track: /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.dag.dagman.out
2018-11-18 00:31:38,237:INFO:Pegasus.monitoring.workflow(952): Appending to existing jobstate.log replay_mode 0 previous_processed_line 0
2018-11-18 00:31:38,237:INFO:Pegasus.monitoring.notifications(394): loading notifications from /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.no\
tiny2

Above we can see that .dag file was not parsed in this rescue dag case, as there is no info message logged saying using dag

2018-11-17 02:14:40,730:INFO:pegasus-monitord(739): DAGMan o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.dag finished with exit code 1
2018-11-17 02:14:40,874:INFO:pegasus-monitord(779): Using DAGMan version 8.6.7 80607
2018-11-17 02:14:40,874:INFO:pegasus-monitord(759): DAGMan runs at pid 2701704
2018-11-17 02:14:40,877:INFO:pegasus-monitord(765): using dag o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.dag
2018-11-17 02:14:40,878:INFO:Pegasus.monitoring.workflow(680): DAGMan starting with condor id 16409990.0
2018-11-17 02:15:38,410:INFO:pegasus-monitord(1171): workflow /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.dag.dagman.out ended
2018-11-17 02:15:38,449:INFO:Pegasus.monitoring.workflow(1118): recovery file deleted: /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/monitord.recover
2018-11-17 02:15:38,449:INFO:pegasus-monitord(1345): finishing workflow: /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.dag.dagman.out

It parsed for the previous rescue dag of that workflow. BUT  NOT for one after that!


2018-11-18 00:31:38,216:INFO:pegasus-monitord(1289): found new workflow to track: /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.dag.dagman.out
2018-11-18 00:31:38,237:INFO:Pegasus.monitoring.workflow(952): Appending to existing jobstate.log replay_mode 0 previous_processed_line 0
2018-11-18 00:31:38,237:INFO:Pegasus.monitoring.notifications(394): loading notifications from /usr1/dbrown/pycbc-tmp.V66xVjwZTR/work/o1-analysis-3-v1_13_0-LOSC_16_V1-main_ID0000001.000/o1-analysis-3-v1_13_0-LOSC_16_V1-main-0.no\
tify

**Comment by mayani** [comment]
**Author:** @vahi

I believe i have fixed the underlying issue of KeyErrors
@duncan-browncan you please update your 4.9.1 install

thanks
