### ISSUE TITLE
[PM-1343] pegasus submit problem

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1457]
Hi,When i use pegaus to submit task:
pegasus-plan        \
	--conf /home/ubuntu/pipline/pegasusrc     \
		--sites condorlocal,condorpool       \
			--output-site local        \
			--dir /home/ubuntu/pipline/dags   \
			--dax /home/ubuntu/pipline/dax_lianchuang.xml   \
			--submit

 I meet a error message below:
2019.01.16 08:21:20.837 UTC: [WARNING]  File URL (file:///home/ubuntu/pipline/worker/run.py,{site=condorpool}) not included as the site attribute is a mismatch to the site name (condorlocal) allowLocalFileURLs true 
2019.01.16 08:21:20.837 UTC: [FATAL ERROR]  
 [1] java.lang.RuntimeException: Unable to select a Physical Filename (PFN) for file with logical filename (LFN) as diamond-run-1.0 for preferred site condorlocalwith runTransferOnLocalSite - true amongst [(file:///home/ubuntu/pipline/worker/run.py,{site=condorpool})] at edu.isi.pegasus.planner.refiner.TransferEngine.getFilesFromRC(TransferEngine.java:1412) 

My excecuatable is:
    run_cmd = Executable(namespace="diamond", name="run", version="1.0", os="linux", arch="x86_64")
    run_cmd.addPFN(PFN("file://" + work_dir + '/worker/run.py', config.CONDOR_POOL_SITE))
    run_cmd.installed = False
    diamond.addExecutable(run_cmd)

My config file is:
pegasus.catalog.site=XML
pegasus.catalog.site.file=/home/ubuntu/pipline/sites.xml
#
#pegasus.dir.useTimestamp=true
pegasus.dir.storage.deep=false
pegasus.condor.logs.symlink=false
#
pegasus.data.configuration = condorio
pegasus.monitord.notifications=true

my sites.xml is:
<?xml version="1.0" encoding="UTF-8"?>
    <sitecatalog xmlns="http://pegasus.isi.edu/schema/sitecatalog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pegasus.isi.edu/schema/sitecatalog http://pegasus.isi.edu/schema/sc-4.0.xsd" version="4.0">
        <site  handle="local" arch="x86_64" os="LINUX">
            <directory type="shared-scratch" path="/home/ubuntu/pipline/work">
                <file-server operation="all" url="file:///home/ubuntu/pipline/work"/>
            </directory>
            <directory type="local-storage" path="/home/ubuntu/pipline/outputs">
                <file-server operation="all" url="file:///home/ubuntu/pipline/outputs"/>
            </directory>
        </site>
        <site  handle="condorpool" arch="x86_64" os="LINUX">
            <profile namespace="pegasus" key="style" >condor</profile>
            <profile namespace="condor" key="universe" >vanilla</profile>
        </site>
        <site  handle="condorlocal" arch="x86_64" os="LINUX">
            <profile namespace="pegasus" key="style" >condor</profile>
            <profile namespace="condor" key="universe" >local</profile>
        </site>
    </sitecatalog>
	
my dax.xml is:

<?xml version="1.0" encoding="UTF-8"?>

<adag xmlns="http://pegasus.isi.edu/schema/DAX" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pegasus.isi.edu/schema/DAX http://pegasus.isi.edu/schema/dax-3.6.xsd" version="3.6" name="diamond">
        <metadata key="name">pipline</metadata>
        <metadata key="createdby">wukan</metadata>
        <executable name="undemand_reqeust" namespace="diamond" version="1.0" arch="x86_64" os="linux">
                <pfn url="file:///home/ubuntu/pipline/ec2.sh" site="condorlocal"/>
        </executable>
        <executable name="scan" namespace="diamond" version="1.0" arch="x86_64" os="linux">
                <pfn url="file:///home/ubuntu/pipline/scaner.py" site="condorlocal"/>
        </executable>
        <executable name="wes" namespace="diamond" version="1.0" arch="x86_64" os="linux" installed="false">
                <pfn url="file:///home/ubuntu/pipline/lianchuang/worker/wes_pipeline.py" site="condorpool"/>
        </executable>
        <executable name="term" namespace="diamond" version="2.0" arch="x86_64" os="linux">
                <pfn url="file:///home/ubuntu/pipline/term.py" site="condorlocal"/>
        </executable>
        <executable name="spot_request" namespace="diamond" version="1.0" arch="x86_64" os="linux">
                <pfn url="file:///home/ubuntu/pipline/ec2_spot.sh" site="condorlocal"/>
        </executable>
        <job id="ID0000001" namespace="diamond" name="spot_request" version="1.0">
                <argument>1 eu-west-1 eu-west-1c r4.xlarge 50 /home/ubuntu/pipline/OrganizationAccountAccessRole OrganizationAccountAccessRole ami-0fbc756353d10a5ac pipline_worker</argument>
                <profile namespace="env" key="HOME">/home/ubuntu</profile>
        </job>
        <job id="ID0000002" namespace="diamond" name="wes" version="1.0">
                <argument>A2018102201 sz-hapdeliver GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102201_BH5VGHDSXX_S1_L002_R1_001.fastq.gz GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102201_BH5VGHDSXX_S1_L002_R2_001.fastq.gz role-biz-gene-data data/lianchuang/output-1 wukan 4 20 oss OrganizationAccountAccessRole</argument>
        </job>
        <job id="ID0000003" namespace="diamond" name="wes" version="1.0">
                <argument>A2018102202 sz-hapdeliver GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102202_BH5VGHDSXX_S2_L002_R1_001.fastq.gz GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102202_BH5VGHDSXX_S2_L002_R2_001.fastq.gz role-biz-gene-data data/lianchuang/output-1 wukan 4 20 oss OrganizationAccountAccessRole</argument>
        </job>
        <job id="ID0000004" namespace="diamond" name="wes" version="1.0">
                <argument>A2018102203 sz-hapdeliver GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102203_BH5VGHDSXX_S3_L002_R1_001.fastq.gz GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102203_BH5VGHDSXX_S3_L002_R2_001.fastq.gz role-biz-gene-data data/lianchuang/output-1 wukan 4 20 oss OrganizationAccountAccessRole</argument>
        </job>
        <job id="ID0000005" namespace="diamond" name="wes" version="1.0">
                <argument>A2018102204 sz-hapdeliver GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102204_BH5VGHDSXX_S4_L002_R1_001.fastq.gz GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102204_BH5VGHDSXX_S4_L002_R2_001.fastq.gz role-biz-gene-data data/lianchuang/output-1 wukan 4 20 oss OrganizationAccountAccessRole</argument>
        </job>
        <job id="ID0000006" namespace="diamond" name="wes" version="1.0">
                <argument>A2018102205 sz-hapdeliver GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102205_BH5VGHDSXX_S5_L002_R1_001.fastq.gz GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102205_BH5VGHDSXX_S5_L002_R2_001.fastq.gz role-biz-gene-data data/lianchuang/output-1 wukan 4 20 oss OrganizationAccountAccessRole</argument>
        </job>
        <job id="ID0000007" namespace="diamond" name="wes" version="1.0">
                <argument>A2018102206 sz-hapdeliver GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102206_BH5VGHDSXX_S6_L002_R1_001.fastq.gz GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102206_BH5VGHDSXX_S6_L002_R2_001.fastq.gz role-biz-gene-data data/lianchuang/output-1 wukan 4 20 oss OrganizationAccountAccessRole</argument>
        </job>
        <job id="ID0000008" namespace="diamond" name="wes" version="1.0">
                <argument>A2018102207 sz-hapdeliver GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102207_BH5VGHDSXX_S7_L002_R1_001.fastq.gz GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102207_BH5VGHDSXX_S7_L002_R2_001.fastq.gz role-biz-gene-data data/lianchuang/output-1 wukan 4 20 oss OrganizationAccountAccessRole</argument>
        </job>
        <job id="ID0000009" namespace="diamond" name="wes" version="1.0">
                <argument>A2018102208 sz-hapdeliver GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102208_BH5VGHDSXX_S8_L002_R1_001.fastq.gz GMPHP18F-02/Novaseq/HP18K003SYnova-1/A2018102208_BH5VGHDSXX_S8_L002_R2_001.fastq.gz role-biz-gene-data data/lianchuang/output-1 wukan 4 20 oss OrganizationAccountAccessRole</argument>
        </job>
</adag>               

the full content of sites.xml pegasusrc ,and  dax.xml is attached below.

**Reporter:** kan.wu (wekay102200)
**Resolution:** Won't Fix
**Watchers:**
@vahi
kan.wu (wekay102200)
**Attachments:**

**Comment by mayani** [comment]
**Author:** kan.wu (wekay102200)

below is the error message:
2019.01.17 08:13:28.573 UTC: [WARNING]  Replica Catalog is either down or connection to it was never opened  
2019.01.17 08:13:28.699 UTC: [WARNING]  File URL (file:///home/ubuntu/pipline/lianchuang/worker/wes_pipeline.py,{site=condorpool}) not included as the site attribute is a mismatch to the site name (condorlocal) allowLocalFileURLs true 
2019.01.17 08:13:28.700 UTC: [FATAL ERROR]  
 [1] java.lang.RuntimeException: Unable to select a Physical Filename (PFN) for file with logical filename (LFN) as diamond-wes-1.0 for preferred site condorlocalwith runTransferOnLocalSite - true amongst [(file:///home/ubuntu/pipline/lianchuang/worker/wes_pipeline.py,{site=condorpool})] at edu.isi.pegasus.planner.refiner.TransferEngine.getFilesFromRC(TransferEngine.java:1412)

**Comment by mayani** [comment]
**Author:** @vahi

each site you specify in the site catalog is a site that is considered physically separated from other sites.  the error is saying that your input is on site condorpool, but your file is on site condorlocal. The URL is a file URL, and cannot be staged to the site condorpool. The transfer job for this data will execute on site local . If you replace the file URL with a say http or any other non file URL it should work.

**Comment by mayani** [comment]
**Author:** kan.wu (wekay102200)

I want to submit 100 tasks to 100 condorpool machine,when i set "wes" executable property "installed" to true,the 100 tasks will assigned to 100 condorpool machine compeletely.
but when i  set "wes" executable property "installed" to false,may be 60 tasks assigned to 60 condorpool machine,and 40 tasks assigned to local machine. i found these 100 tasks will random assigned to condorpool or local machine.then will cause the problem below:
File URL (file:///home/ubuntu/pipline/lianchuang/worker/wes_pipeline.py,{site=condorpool}) not included as the site attribute is a mismatch to the site name (condorlocal) allowLocalFileURLs true 
2019.01.17 08:13:28.700 UTC: [FATAL ERROR] 
 [1] java.lang.RuntimeException: Unable to select a Physical Filename (PFN) for file with logical filename (LFN) as diamond-wes-1.0 for preferred site condorlocalwith runTransferOnLocalSite - true amongst [(file:///home/ubuntu/pipline/lianchuang/worker/wes_pipeline.py,{site=condorpool})] at edu.isi.pegasus.planner.refiner.TransferEngine.getFilesFromRC(TransferEngine.java:1412)

so why when i set "installed" to false,the behavior will change.how can I submit all 100 tasks to all condorpool machine when i  set "wes" executable property "installed" to false?

**Comment by mayani** [comment]
**Author:** kan.wu (wekay102200)

i known when i set exectable property "installed" to false,the excetable will transfered from local machine to remote machine with the excetable name diamond-wes-1.0.

**Comment by mayani** [comment]
**Author:** @vahi

if you only want to only refer to installed executables set

pegasus.catalog.transformation.mapper Installed

https://pegasus.isi.edu/documentation/properties.php#misc__props

**Comment by mayani** [comment]
**Author:** @vahi

it means that it is looking for executable named "run" in namespace diamond and version 1.0 that is installed in the TC or in the DAX where you have listed the executables.
Where have you specified your executables? In the DAX you uploaded I don't see any run executable

**Comment by mayani** [comment]
**Author:** kan.wu (wekay102200)

my excutable was locate in the manager machine. whe i submit task in the the manager machine. i want the excutable locate in the local manager machine transfer to remote worker machine.

**Comment by mayani** [comment]
**Author:** @vahi

If you want all executables to be staged then you can do

pegasus.catalog.transformation.mapper Staged

If you want a mix, then have it as

pegasus.catalog.transformation.mapper All

Only those executables are staged the ones that are described as STAGEABLE in the transformation catalog.

**Comment by mayani** [comment]
**Author:** kan.wu (wekay102200)

I have set pegasus.catalog.transformation.mapper=Staged
but it also occur error below:

2019.05.07 14:07:04.000 CST: [WARNING]  Replica Catalog is either down or connection to it was never opened  
2019.05.07 14:07:04.108 CST: [WARNING]  File URL (file:///home/wukan/run2.sh,{site=condorpool}) not included as the site attribute is a mismatch to the site name (condorlocal) allowLocalFileURLs true 
2019.05.07 14:07:04.108 CST: [FATAL ERROR]  
 [1] java.lang.RuntimeException: Unable to select a Physical Filename (PFN) for file with logical filename (LFN) as diamond-run-1.0 for preferred site condorlocalwith runTransferOnLocalSite - true amongst [(file:///home/wukan/run2.sh,{site=condorpool})] at edu.isi.pegasus.planner.refiner.TransferEngine.getFilesFromRC(TransferEngine.java:1412) 

my executable is :
        <executable name="run" namespace="diamond" version="1.0" arch="x86_64" os="linux" installed="false">
                <pfn url="file:///home/wukan/run2.sh" site="condorpool"/>
        </executable>

**Comment by mayani** [comment]
**Author:** @vahi

<pfn url="file:///home/wukan/run2.sh" site="condorpool"/> 

it seems you are using condorio mode. can you updated the site entry above to be local ?

/home/wukan/run2.sh is the path on your submit host . right?

**Comment by mayani** [comment]
**Author:** @vahi

did not get responses
