### ISSUE TITLE
[PM-26] NullPointerException when nonexistent job is used as child

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#147]
When I plan a DAX which has a child specified that doesn't exist (I forgot to add the job to the DAX), I get a NPE from the parser:

 [1] java.lang.RuntimeException: While parsing file file:///home/scec-00/scottcal/CyberShake2007/dax-generator/CyberShake_PAS.dax_39 at line 89153 at column 11 at org.griphyn.cPlanner.parser.DaxParser.startParser(DaxParser.java:293)
 [2] java.lang.NullPointerException: null at java.lang.String.<init>(String.java:144)

**Reporter:** @scallag
**Resolution:** Fixed
**Watchers:**
Gaurang Mehta (gmehta)
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

was fixed for 2.1
