### ISSUE TITLE
[PM-1464] disallow variable expansion while converting site catalog from one format to another

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1578]
**Reporter:** @vahi
**Resolution:** Fixed
**Watchers:**
@rynge
@ryantanaka
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

Even though i implemented the logic it will never work, because it breaks all our in built enums

For example lets say i have arch set to ${ARCH}
<site handle="osg" arch="${ARCH}" os="LINUX" osrelease="" osversion="" glibc="">
                
                <directory path="/tmp" type="local-scratch">
                        
                        <file-server operation="all" url="file:///tmp"/>
                </directory>

                <profile namespace="pegasus" key="style">condor</profile>
                <profile namespace="condor" key="universe">vanilla</profile>
        </site>

pegasus-sc-coverter will fail if variable expansion is turned off

2020.02.25 15:30:45.979 PST: [FATAL ERROR]  java.lang.IllegalArgumentException: No enum constant edu.isi.pegasus.planner.catalog.classes.SysInfo.Architecture.${ARCH}
	at java.lang.Enum.valueOf(Enum.java:238)
	at edu.isi.pegasus.planner.catalog.classes.SysInfo$Architecture.valueOf(SysInfo.java:51)
	

this even affects python stuff for writing out the site catalog in first place
