### ISSUE TITLE
[PM-37] NPE while populating new style kickstart records to Provenance Catalog

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#158]
A Null Pointer Exception is encountered while populating kickstart records generated by pegasus version 2.2.0 and higher. No error with records generated from previous distributions.
Appears to be related to the recent changes in XML schema done for Tangram

Trace below.
un:
20090218T153530.189: [app] will use InvocationSchema
20090218T153530.194: [app] starting to parse invocation
20090218T153530.353: [app] invocation 1 was parsed successfully
20090218T153530.361: [app] adding invocation to database
java.lang.NullPointerException
        at org.griphyn.vdl.dbschema.InvocationSchema.saveArchitecture(InvocationSchema.java:145)
        at org.griphyn.vdl.dbschema.InvocationSchema.saveInvocation(InvocationSchema.java:293)
        at org.griphyn.vdl.directive.ParseKickstart.parseFile(ParseKickstart.java:533)
        at org.griphyn.vdl.toolkit.ExitCode.main(ExitCode.java:283)
java.lang.NullPointerException: null

**Reporter:** @vahi
**Resolution:** Fixed
**Watchers:**
@deelman
Gaurang Mehta (gmehta)
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

The error is because the uname object was moved to the machine element in the XML record

Hence for the new style kickstart records the Architecture Data Object created while parsing the record is NULL.

Old Kickstart Record Snippet
 <mainjob start="2009-02-18T15:33:44.440-08:00" duration="5.890" pid="13930">
      ---    
      ---
  </mainjob>
  <cwd>/nfs/shared-scratch/vahi/exec/vahi/pegasus/montage/run0001</cwd>
  <usage utime="0.000" stime="0.006" minflt="189" majflt="1" nswap="0" nsignals="0" nvcsw="81" nivcsw="1"/>
  <uname system="linux" archmode="IA32" nodename="viz-4" release="2.6.11.7" machine="i686">#3 SMP Tue Nov 22 17:17:26 PST 2005</uname>


Newer Kickstart Record Snippet
 <mainjob start="2009-02-18T14:47:20.826-08:00" duration="0.245" pid="5912">
    ---
    ---
  </mainjob>
  <cwd>/lfs1/work/netlogger/dags/vahi/pegasus/montage/run0001</cwd>
  <usage utime="0.001" stime="0.003" minflt="0" majflt="0" nswap="0" nsignals="1" nvcsw="2" nivcsw="0"/>
  <machine page-size="4096" provider="DARWIN">
    <stamp>2009-02-18T14:47:20.825-08:00</stamp>
    <uname system="darwin" nodename="corbusier.isi.edu" release="9.6.0" machine="i386">Darwin Kernel Version 9.6.0: Mon Nov 24 17:37:00 PST 2008; root:x</uname>
     ---
     ---    
</machine>

**Comment by mayani** [comment]
**Author:** @vahi

I have checked in the fix.

The following changes were made

1) Added a converter method in the Uname data class that converts the uname object to the Architecture object

2) This method is then called in InvocationParser when the relation is set for hte machine element with the invocation element.

So now in case of newer kickstart records the memory data structure will have both the uname and architecture object populated.

**Comment by mayani** [comment]
**Author:** @vahi

The fix is incomplete as population to the PTC for clustered jobs still fails.

The reason for this is that the machine element is not created for each invocation record in a cluster but just the first. Hence, the uname information is null for the remaining jobs in the cluster.

**Comment by mayani** [comment]
**Author:** @vahi

Modified ParseKickstart.java  to cache the uname record encountered while parsing a kickstart file with multiple invocation records. The fix takes care of  cases where people concat many files into one.
Hence one may occasionally encounter different uname records while parsing the file

Additionally, the unameToArchitecture() function now assigns a default
value ( UNDEFINED ) for the archmode attribute. This is to prevent
creation of duplicate entries  in the ptc_uname table. In MySQL the
null value in a column invalidates the UNIQUE constraint.

**Comment by mayani** [comment]
**Author:** @vahi

was fixed on 19/Feb/09 5:45 PM
