### ISSUE TITLE
[PM-1541] change the pegasus-plan invocation via pegasus lite in dagman prescripts to handle new worker package organization

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1655]
in some cases, like test case  045-hierarchy-sharedfs-b

the pegasus-plan prescript invocation is failing because pegasus-db-admin is unable to update the database correctly.

[DEBUG] condor_submit_dag exited with status 0 
2020.04.30 23:50:18.230 PDT: [DEBUG] Updated environment for dagman is environment	= _CONDOR_SCHEDD_ADDRESS_FILE=/var/lib/condor/spool/.schedd_address;_CONDOR_MAX_DAGMAN_LOG=0;_CONDOR_SCHEDD_DAEMON_AD_FILE=/var/lib/condor/spool/.sch
edd_classad;_CONDOR_DAGMAN_LOG=diamond_dax-0.dag.dagman.out;PEGASUS_METRICS=true; 
2020.04.30 23:50:18.231 PDT: [INFO] event.pegasus.code.generation dax.id diamond_dax_0 (65.686 seconds) - FINISHED 
2020.04.30 23:50:18.232 PDT: [DEBUG] Executing /lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT50-T045B/pegasus/bin/pegasus-db-admin update -t master -c /lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT50-T045B/test/core
/045-hierarchy-sharedfs-b/work/bamboo/pegasus/local-hierarchy/run0001/00/00/./diamond_dax_ID0000001.000/pegasus.786021831373058811.properties 
2020.04.30 23:50:19.048 PDT: [ERROR] 2020-04-30 23:50:19,045:ERROR:Pegasus.db.admin.commands(120): /tmp/pegasus.ps55OQY4D/pegasus-5.0.0dev/bin/pegasus-version: line 9: /tmp/pegasus.ps55OQY4D/pegasus-5.0.0dev/share/pegasus/common.sh: No 
such file or directory 
2020.04.30 23:50:19.054 PDT: [ERROR] /tmp/pegasus.ps55OQY4D/pegasus-5.0.0dev/bin/pegasus-version: line 12: -Dpegasus.home=/lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT50-T045B/pegasus: No such file or directory 
2020.04.30 23:50:19.185 PDT: [DEBUG] pegasus-db-admin exited with status 1 
2020.04.30 23:50:19.186 PDT: [FATAL ERROR] java.lang.RuntimeException: Pegasus was unable to update the the worflow database file found at ~/.pegasus/workflow.db . If this file is corrupted, a solution for problem is to remove the file 
with the command: rm -f ~/.pegasus/workflow.db - but note that doing so will remove old workflows from the Pegasus Dashboard.
	at edu.isi.pegasus.planner.common.PegasusDBAdmin.checkDatabase(PegasusDBAdmin.java:193)
	at edu.isi.pegasus.planner.common.PegasusDBAdmin.checkMasterDatabaseForVersionCompatibility(PegasusDBAdmin.java:135)
	at edu.isi.pegasus.planner.client.CPlanner.checkMasterDatabaseForVersionCompatibility(CPlanner.java:1856)
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:642)
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:317)
	at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:204)

**Reporter:** @vahi
**Resolution:** Fixed
**Watchers:**
@rynge
@mayani
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

some clues here. 

2020.04.30 23:50:19.054 PDT: [ERROR] /tmp/pegasus.ps55OQY4D/pegasus-5.0.0dev/bin/pegasus-version: line 12: -Dpegasus.home=/lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT50-T045B/pegasus: No such file or directory 

we originally had to move to invoke pegasus-plan prescript to pegasus lite as a part of #1246

**Comment by mayani** [comment]
**Author:** @vahi

we need to ensure that a subwf should never be planned with a transferred worker package

**Comment by mayani** [comment]
**Author:** @vahi

the fix was incomplete, as for running pegasus-plan via pegasus lite we need to make sure that we disable complete the worker package logic of pegasus lite in addition to setting PEGASUS_HOME

else, pegasus lite detects the worker package in the submit directory, and updates the PATH accordingly, which messes up pegasus-db-admin's callout to pegasus-version

This issue is also related to #1710
