### ISSUE TITLE
[PM-1737] monitord fails on divide by 0 error while computing avg cpu utilization

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1851]
cat monitord.log
2021-03-25 00:49:53,569:INFO:Pegasus.db.connection(737): Rotating sqlite db file /web/data/qc/runs/605bddcb2d8bf/dags/605bddcb2d8bf-0.stampede.db
s/605bddcb2d8bf-0.stampede.db
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/Pegasus/cli/pegasus-monitord.py", line 1538, in <module>
    workflow_entry.wf, workflow_entry.ml_buffer[0:ml_pos]
  File "/usr/lib64/python3.6/site-packages/Pegasus/cli/pegasus-monitord.py", line 881, in process_dagman_out
    add(wf, my_jobid, "%s_SCRIPT_SUCCESS" % (my_script), status=0)
  File "/usr/lib64/python3.6/site-packages/Pegasus/cli/pegasus-monitord.py", line 732, in add
    jobid, sched_id, my_job_submit_seq, event, status, my_time, reason
  File "/usr/lib64/python3.6/site-packages/Pegasus/monitoring/workflow.py", line 2774, in update_job_state
    real_app_exitcode = self.parse_job_output(my_job, job_state)
  File "/usr/lib64/python3.6/site-packages/Pegasus/monitoring/workflow.py", line 2314, in parse_job_output
    self.db_send_task_end(my_job, "MAIN_JOB", my_task_id, record)
  File "/usr/lib64/python3.6/site-packages/Pegasus/monitoring/workflow.py", line 1939, in db_send_task_end
    kwargs["avg_cpu"] = kwargs["remote_cpu_time"] / float(kwargs["dur"])
ZeroDivisionError: float division by zero

**Reporter:** @mayani
**Resolution:** Fixed
**Watchers:**
@papajim
@rynge
@mayani
@vahi
**Attachments:**

**Comment by mayani** [comment]
**Author:** @vahi

@mayanican you confirm whether stime and utime in your job was also 0. i think an open question is what we should populate this value as, or leave it none. but maybe sql alchemy query might break?

**Comment by mayani** [comment]
**Author:** @mayani

Yes, utime and stime are 0.

**Comment by mayani** [comment]
**Author:** @mayani

- invocation: True
  version: 3.0
  start: 2021-04-05T14:18:10.373-07:00
  duration: 0.002
  interface: 
  hostaddr: 0.0.0.0
  pid: 59865
  uid: 501
  user: mayani
  gid: 20
  group: staff
  umask: 0o0022
  mainjob:
    start: 1969-12-31T16:00:00.000-08:00
    duration: 0.000
    usage:
      utime: 0.000
      stime: 0.000
      maxrss: 0
      minflt: 0
      majflt: 0
      nswap: 0
      inblock: 0
      outblock: 0
      msgsnd: 0
      msgrcv: 0
      nsignals: 0
      nvcsw: 0
      nivcsw: 0
    status:
      raw: -127
      failure_error: 2   No such file or directory
    executable:
      error: 2
      file_name: /bin/true
    argument_vector:
    procs:
  jobids:
  cwd: 
  usage:
    utime: 0.002
    stime: 0.003
    maxrss: 1288
    minflt: 510
    majflt: 0
    nswap: 0
    inblock: 0
    outblock: 0
    msgsnd: 0
    msgrcv: 0
    nsignals: 0
    nvcsw: 4
    nivcsw: 12
  machine:
    page-size: 4096
    uname_system: darwin
    uname_nodename: mayani-macbook-pro.local
    uname_release: 20.3.0
    uname_machine: x86_64
    ram_total: 33554432
    ram_avail: 7159888
    ram_active: 11316148
    ram_inactive: 9284256
    ram_wired: 3793128
    swap_total: 4194304
    swap_avail: 1187840
    swap_used: 3006464
    boot: 2021-03-09T17:14:22.722-08:00
    cpu_count: 12
    cpu_speed: 2900
    cpu_vendor: GenuineIntel
    cpu_name: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    load_min1: 3.00
    load_min5: 2.47
    load_min15: 2.49
    proc_total: 639
    proc_running: 1
    proc_sleeping: 638
  files:
    stdin:
      file_name: /dev/null
      mode: 0o20666
      size: 0
      inode: 319
      nlink: 1
      blksize: 131072
      blocks: 0
      mtime: 2021-04-05T14:18:03-07:00
      atime: 2021-04-05T03:19:56-07:00
      ctime: 2021-04-05T14:18:03-07:00
      uid: 0
      user: root
      gid: 0
      group: wheel
    stdout:
      temporary_name: /var/folders/yl/wblbv6_52n9bkz4ht93nx3x80000gn/T//ks.out.ElM84X
      descriptor: 3
      mode: 0o100600
      size: 0
      inode: 559077738
      nlink: 1
      blksize: 4096
      blocks: 0
      mtime: 2021-04-05T14:18:10-07:00
      atime: 2021-04-05T14:18:10-07:00
      ctime: 2021-04-05T14:18:10-07:00
      uid: 501
      user: mayani
      gid: 20
      group: staff
    stderr:
      temporary_name: /var/folders/yl/wblbv6_52n9bkz4ht93nx3x80000gn/T//ks.err.qSuCiY
      descriptor: 4
      mode: 0o100600
      size: 0
      inode: 559077739
      nlink: 1
      blksize: 4096
      blocks: 0
      mtime: 2021-04-05T14:18:10-07:00
      atime: 2021-04-05T14:18:10-07:00
      ctime: 2021-04-05T14:18:10-07:00
      uid: 501
      user: mayani
      gid: 20
      group: staff
    metadata:
      temporary_name: /var/folders/yl/wblbv6_52n9bkz4ht93nx3x80000gn/T//ks.meta.FBjzLT
      descriptor: 5
      mode: 0o100600
      size: 0
      inode: 559077740
      nlink: 1
      blksize: 4096
      blocks: 0
      mtime: 2021-04-05T14:18:10-07:00
      atime: 2021-04-05T14:18:10-07:00
      ctime: 2021-04-05T14:18:10-07:00
      uid: 501
      user: mayani
      gid: 20
      group: staff
    kickstart:
      error: 2
      note: ignore error - it is just a warning
      file_name: pegasus-kickstart
    logfile:
      descriptor_number: 1
      mode: 0o20620
      size: 0
      inode: 995
      nlink: 1
      blksize: 131072
      blocks: 0
      mtime: 2021-04-05T14:18:10-07:00
      atime: 2021-04-05T14:18:10-07:00
      ctime: 2021-04-05T14:18:10-07:00
      uid: 501
      user: mayani
      gid: 4
      group: tty
  environment:
    "TMPDIR": "/var/folders/yl/wblbv6_52n9bkz4ht93nx3x80000gn/T/"
    "__CFBundleIdentifier": "com.apple.Terminal"
    "XPC_FLAGS": "0x0"
    "TERM": "xterm-256color"
    "DISPLAY": "/private/tmp/com.apple.launchd.ivt1LlTLcG/org.macosforge.xquartz:0"
    "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.RkridG3xas/Listeners"
    "XPC_SERVICE_NAME": "0"
    "TERM_PROGRAM": "Apple_Terminal"
    "TERM_PROGRAM_VERSION": "440"
    "TERM_SESSION_ID": "A622B8C0-C1A0-484A-9ED0-97916771D3E8"
    "SHELL": "/bin/zsh"
    "HOME": "/Users/mayani"
    "LOGNAME": "mayani"
    "USER": "mayani"
    "PATH": "/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/mayani/.pyenv/shims:/Volumes/data/software/pegasus/default/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin"
    "SHLVL": "1"
    "PWD": "/Users/mayani"
    "OLDPWD": "/Users/mayani"
    "LIBRARY_PATH": "/usr/local/opt/openssl/lib"
    "PEGASUS_BUILD_R_MODULES": "0"
    "PYENV_VIRTUALENV_DISABLE_PROMPT": "1"
    "ZSH": "/Users/mayani/.oh-my-zsh"
    "PAGER": "less"
    "LESS": "-R"
    "LSCOLORS": "Gxfxcxdxbxegedabagacad"
    "PYENV_SHELL": "zsh"
    "PYENV_VIRTUALENV_INIT": "1"
    "LANG": "en_US.UTF-8"
    "_": "/Volumes/data/software/pegasus/default/bin/pegasus-kickstart"
    "KICKSTART_INTEGRITY_DATA": "/var/folders/yl/wblbv6_52n9bkz4ht93nx3x80000gn/T//ks.integrity.q1R85O"
    "KICKSTART_METADATA": "/var/folders/yl/wblbv6_52n9bkz4ht93nx3x80000gn/T//ks.meta.FBjzLT"
  limits:
    RLIMIT_CPU_soft: unlimited
    RLIMIT_CPU_hard: unlimited
    RLIMIT_FSIZE_soft: unlimited
    RLIMIT_FSIZE_hard: unlimited
    RLIMIT_DATA_soft: unlimited
    RLIMIT_DATA_hard: unlimited
    RLIMIT_STACK_soft: 8388608
    RLIMIT_STACK_hard: 67104768
    RLIMIT_CORE_soft: 0
    RLIMIT_CORE_hard: unlimited
    RLIMIT_AS_soft: unlimited
    RLIMIT_AS_hard: unlimited
    RLIMIT_MEMLOCK_soft: unlimited
    RLIMIT_MEMLOCK_hard: unlimited
    RLIMIT_NPROC_soft: 5568
    RLIMIT_NPROC_hard: 8352
    RLIMIT_NOFILE_soft: 256
    RLIMIT_NOFILE_hard: unlimited

**Comment by mayani** [comment]
**Author:** @vahi

assigning it to mats to explore if values should be rounded up in kickstart

**Comment by mayani** [comment]
**Author:** @papajim

By running this code on my machine 1000 times I got 0 output using the "time" command.
Check test.out file attached to this issue.

#include <stdio.h>

int main(){
  printf("Hello World!\n");
  return 0;
}

**Comment by mayani** [comment]
**Author:** @rynge

I'm considering a change to kickstart where the smallest allowable unit is 0.001. That means you would never see 0.000 in the outputs. For example:

  mainjob:
    start: 2021-04-05T14:53:46.768-07:00
    duration: 0.001
    pid: 3013320
    usage:
      utime: 0.001
      stime: 0.001


Would that be an acceptable solution for the Stampede database?

**Comment by mayani** [comment]
**Author:** @vahi

yes. but stime and utime sum cannot be more than duration. right?

**Comment by mayani** [comment]
**Author:** @rynge

Ah good point. Let me dig more

**Comment by mayani** [comment]
**Author:** @rynge

Fix committed to kickstart. stime and utime will always be >= 0.001, and duration >= 0.003.
