### ISSUE TITLE
[PM-65] Directory Path resolution for recursive / DAX 3.0 workflows with dax keyword specified

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#186]
If a user plans a dax 3.0 workflow
1) with a dax job specified in it
2) for the dax job the --dir option is a relative path e.g --dir ./dag1
3) the option passed on the command line to the outer level workflow has --relative-dir ./

then the planning process on the outer level workflow fails with the following message

[3] java.lang.RuntimeException: Parsing Error in file:///Users/vahi/Pegasus/work/dax-3.0/dags/././dag_1/dax/blackdiamond_dax.pdax at line 5 at column 14 :  at org.griphyn.cPlanner.parser.PDAXParser.startParser(PDAXParser.java:162)
2009.09.02 18:09:24.036 PDT: [INFO] event.pegasus.planner planner.version 2.4.0cvs  - FINISHED 
 [4] java.lang.StringIndexOutOfBoundsException: String index out of range: -1 at java.lang.String.substring(String.java:1762) 
2009.09.02 18:09:24.036 PDT: [WARNING]  Non-zero exit-code 1 
Java Result: 1
BUILD SUCCESSFUL (total time: 2 seconds)

The problematic dax file is attached 

The options passed to pegasus-plan for this dax are 
-Dpegasus.dir.storage=duncantest --dax two_node_dax-3.0_v5.xml --force -o local -vvvvvv --dir /Users/vahi/Pegasus/work/dax-3.0/dags --relative-dir ./ -r --cache /Users/vahi/Pegasus/work/dax-3.0/conf/test.cache

**Reporter:** @vahi
**Resolution:** Fixed
**Watchers:**
@rbolze
@vahi
**Attachments:**

**Comment by mayani** [comment]
**Author:** @vahi

The error actually occurs in the PDAX2MDag callback that the PDAX parser calls out to.

The error in the setPrescript function 
where the various directories are determined for a partition

//generate the remote working directory for the paritition
        String submit        = mClonedPOptions.getSubmitDirectory(); // like /tmp/vahi/pegasus/blackdiamond/run0001/00/PID1
        String remoteBase    = mPOptions.getRandomDir(); // like vahi/pegasus/blackdiamond/run0001
        String remoteWorkDir = submit.substring( submit.indexOf( remoteBase) ); //gets us vahi/pegasus/blackdiamond/run0001/00/PID1


The error happens because in this case 
remoteBase is set to .//./dag_1 
submit is set to /Users/vahi/Pegasus/work/dax-3.0/dags/././dag_1/00/P1

remoteBase string does not exist in submit String because of presence of an extra / in submit.

The fix needs to ensure that // are never added.

On further investigation, this incorrect assignment is happening in the PartitionAndPlan class where we try to figure out the submit directory for the dax job specified in the DAX.

**Comment by mayani** [comment]
**Author:** @vahi

Raphael i have checked in the fix for this bug.
Can you update and run your sipht setup with ./ passed as the relative-dir option to hdax.xml to confirm whether pegasus plans correctly.

**Comment by mayani** [comment]
**Author:** @vahi

Was fixed for 3.0 release 02/Sep/09 6:29 PM
