### ISSUE TITLE
[PM-1748] planner fails with NPE on empty workflow

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1862]
2021.04.14 13:17:41.528 CDT: [INFO] event.pegasus.check.cyclic-dependencies dax.id xenonnt-0  - STARTED 
2021.04.14 13:17:41.528 CDT: [FATAL ERROR]  java.lang.NullPointerException
        at edu.isi.pegasus.planner.refiner.MainEngine.runPlanner(MainEngine.java:165)
        at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:605)
        at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:322)
        at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:209)

**Reporter:** @rynge
**Resolution:** Fixed
**Watchers:**
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

I have a fix, and after that fix Pegasus will end up generating a workflow with a single noop job
I like this from the perspective of same handling for this case and a workflow with full data reuse

**Comment by mayani** [comment]
**Author:** @vahi

Putting in comments from slack

i was thinking we should throw a warning in the case an empty workflow is detected

Mats Rynge  12:39 PM
I'm wondering if the noop job is the right solution. If a user ask us to plan an empty dag, there is a good chance they made a mistake creating the wf
12:39
At the minimum, it should have a good warning in the output
12:39
But maybe we should even refuse to plan it?

Rajiv  12:47 PM
Is the workflow root or subwf?
12:47
Semantics could differ based on that




Rajiv  1:05 PM
For root or sub-wf

Karan  1:05 PM
for root

Rajiv  1:06 PM
It should be an error
New
1:06
If I don’t pass a DAX file, we don’t create a noop job. Should be the same for a root level wf

Karan  1:07 PM
fair enough
1:07
same for sub workflows then

Rajiv  1:07 PM
For sub-wf it could be dynamic so empty wf is acceptable with a warning

Karan  1:08 PM
actually yes for the recursive case

**Comment by mayani** [comment]
**Author:** @vahi

additionally per our discussions
if you now pass an empty workflow to the planner as a root workflow, it will throw an exception
 java.lang.RuntimeException: No jobs found in the Abstract Workflow

However if the planner is invoked on a sub workflow (pegasusWorkflow) job then the abstract workflow can have zero jobs in it. in that case a workflow is planned and the executable workflow has a single noop job in it
