### ISSUE TITLE
[PM-1761] pegasus-analyzer showing "failed to send files" error when root cause is exec format error

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1875]
pegasus-analyzer is showing the following error:

####################
# pegasus-analyzer #
####################
Your database is compatible with Pegasus version: 5.1.0dev

************************************Summary*************************************

Submit Directory   : /home/scitech/shared-data/pegasus-analyzer-examples/scitech/pegasus/bad-wf/run0011
Total jobs         :      9 (100.00%)
# jobs succeeded   :      3 (33.33%)
# jobs failed      :      0 (0.00%)
# jobs held        :      1 (11.11%)
# jobs unsubmitted :      6 (66.67%)

*******************************Held jobs' details*******************************

===============================test2_sh_ID0000001===============================

submit file            : test2_sh_ID0000001.sub
last_job_instance_id   : 4
reason                 :  Error from slot1@645f55a9b16e: STARTER at 127.0.0.1 failed to send file(s) to <127.0.0.1:9618>: error reading from /var/lib/condor/execute/dir_3240/xyz: (errno 2) No such file or directory; SHADOW failed to receive file(s) from <127.0.0.1:45271>

When the actual error is "execv: Exec format error". Since this error exists in the kickstart record test2_sh_ID0000001.out.000, I had expected it to show up instead of the above.

**Reporter:** @ryantanaka
**Resolution:** Fixed
**Watchers:**
@ryantanaka
@vahi
**Attachments:**

**Comment by mayani** [comment]
**Author:** @vahi

this is related to #1395 
need to investigate why that fix is not working

**Comment by mayani** [comment]
**Author:** @vahi

at my end pegasus analyzer shows the right error

(virtualenv) corbusier:run0011 vahi$ pegasus-analyzer .
2021-08-18 17:02:50,680:WARNING:Pegasus.tools.properties(260): cannot access properties file /home/scitech/shared-data/pegasus-analyzer-examples/scitech/pegasus/bad-wf/run0011/pegasus.4824839602248307396.properties... continuing...
2021-08-18 17:02:50,680:WARNING:Pegasus.tools.properties(282): no properties file parsed whatsoever!
Your database is compatible with Pegasus version: 5.0.1dev

************************************Summary*************************************

 Submit Directory   : .
 Total jobs         :      9 (100.00%)
 # jobs succeeded   :      3 (33.33%)
 # jobs failed      :      1 (11.11%)
 # jobs held        :      1 (11.11%)
 # jobs unsubmitted :      5 (55.56%)

*******************************Held jobs' details*******************************

===============================test2_sh_ID0000001===============================

submit file            : test2_sh_ID0000001.sub
last_job_instance_id   : 4
reason                 :  Error from slot1@645f55a9b16e: STARTER at 127.0.0.1 failed to send file(s) to <127.0.0.1:9618>: error reading from /var/lib/condor/execute/dir_3240/xyz: (errno 2) No such file or directory; SHADOW failed to receive file(s) from <127.0.0.1:45271>

******************************Failed jobs' details******************************

===============================test2_sh_ID0000001===============================

 last state: POST_SCRIPT_FAILED
       site: condorpool
submit file: 00/00/test2_sh_ID0000001.sub
output file: 00/00/test2_sh_ID0000001.out.000
 error file: 00/00/test2_sh_ID0000001.err.000

-------------------------------Task #1 - Summary--------------------------------

site        : condorpool
hostname    : 645f55a9b16e
executable  : /scratch/test2_sh
arguments   : -
exitcode    : 127
working dir : /scratch

---------------Task #1 - test2.sh - ID0000001 - Kickstart stderr----------------

 execv: Exec format error

**Comment by mayani** [comment]
**Author:** @vahi

@ryantanakacan you please run this again at your end and see!

**Comment by mayani** [comment]
**Author:** @vahi

actually the monitord.log had the information 

05-11 11:13:53,984:INFO:pegasus-monitord(214): DB flushing ended
Traceback (most recent call last):
  File "/home/scitech/pegasus/dist/pegasus-5.1.0dev/lib64/python3.6/site-packages/Pegasus/cli/pegasus-monitord.py", line 1538, in <module>
    workflow_entry.wf, workflow_entry.ml_buffer[0:ml_pos]
  File "/home/scitech/pegasus/dist/pegasus-5.1.0dev/lib64/python3.6/site-packages/Pegasus/cli/pegasus-monitord.py", line 893, in process_dagman_out
    wf, my_jobid, "%s_SCRIPT_FAILURE" % (my_script), status=my_exit_code
  File "/home/scitech/pegasus/dist/pegasus-5.1.0dev/lib64/python3.6/site-packages/Pegasus/cli/pegasus-monitord.py", line 732, in add
    jobid, sched_id, my_job_submit_seq, event, status, my_time, reason
  File "/home/scitech/pegasus/dist/pegasus-5.1.0dev/lib64/python3.6/site-packages/Pegasus/monitoring/workflow.py", line 2774, in update_job_state
    real_app_exitcode = self.parse_job_output(my_job, job_state)
  File "/home/scitech/pegasus/dist/pegasus-5.1.0dev/lib64/python3.6/site-packages/Pegasus/monitoring/workflow.py", line 2314, in parse_job_output
    self.db_send_task_end(my_job, "MAIN_JOB", my_task_id, record)
  File "/home/scitech/pegasus/dist/pegasus-5.1.0dev/lib64/python3.6/site-packages/Pegasus/monitoring/workflow.py", line 1939, in db_send_task_end
    kwargs["avg_cpu"] = kwargs["remote_cpu_time"] / float(kwargs["dur"])
ZeroDivisionError: float division by zero

this was fixed by #1851

**Comment by mayani** [comment]
**Author:** @ryantanaka

@vahi you can close this one out. I can confirm with latest 5.0.1dev I can see the correct error, see screenshot.

**Comment by mayani** [comment]
**Author:** @ryantanaka

issue could not be recreated in latest 5.0.1dev (5.0.1dev-x86_64_macos_10-20210819180730Z-dfe851434111de4a8ce80754387d65e622a54929). marking as resolved.
