### ISSUE TITLE
[PM-1817] pegasus-run with shell code generator

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1930]
rajiv can you investigate what it will take to get pegasus-run submit the planner generated shell code generator

also it seems our test case is erroneously showing green
https://bamboo.isi.edu/browse/PEGASUS-WT50-T6-768/log

can you please fix that too

**Reporter:** @vahi
**Resolution:** Fixed
**Watchers:**
@mayani
@vahi

**Comment by mayani** [comment]
**Author:** @mayani

[bamboo@bamboo 006-black-diamond-shell-code-generator]$ ./run-bamboo-test ; echo $?
.
.
.
2021.09.22 13:16:53.818 PDT:   Error: Running /lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT50-T6/test/core/006-black-diamond-shell-code-generator/work/submit/2021-09-22_131641/blackdiamond.sh failed with 2 
2021.09.22 13:16:53.835 PDT: [DEBUG]  Submission of workflow exited with status 2 
2021.09.22 13:16:53.836 PDT: [FATAL ERROR]  java.lang.RuntimeException: Unable to submit the workflow using pegasus-run
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:667)
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:322)
	at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:209)
 
2021.09.22 13:16:53.843 PDT: [DEBUG]  Sending Planner Metrics to [1 of 1] http://metrics.pegasus.isi.edu/metrics 
2021.09.22 13:16:54.038 PDT: [DEBUG]  Metrics succesfully sent to the server 
2021.09.22 13:16:54.038 PDT: [DEBUG]  Exiting with non-zero exit-code 1 
2021.09.22 13:16:54.038 PDT: [INFO] event.pegasus.planner planner.version 5.0.1dev  (10.893 seconds) - FINISHED 
0

Planner detects non-zero exit code from run, but still exits with the code zero.

**Comment by mayani** [comment]
**Author:** @mayani

The pegasus-exitcode statement in the generated shell is incorrect.

The below fails even though the job succeeded

+ echo 'JOB create_dir_blackdiamond_0_local Returned with 0'
JOB create_dir_blackdiamond_0_local Returned with 0
.
.
+ execute_post_script create_dir_blackdiamond_0_local /lfs1/software/bamboo/data/xml-data/build-dir/PEGASUS-WT50-T6/test/core/006-black-diamond-shell-code-generator/work/submit/2021-09-22_133644/00/00 /usr/bin/pegasus-exitcode ' -r  -l blackdiamond-0.exitcode.log -M blackdiamond-0.cache.meta  create_dir_blackdiamond_0_local.out' ''

Errors --

1.

-r is not followed by "Return code reported by DAGMan"

2.

-M blackdiamond-0.cache.meta

The file name is probably incorrect. Shouldn't it be like create_dir_blackdiamond_0_local*

**Comment by mayani** [comment]
**Author:** @vahi

@mayanii fixed the return code stuff. But i think it will still fail because of python import errors. can you take a look after pulling my latest changes!
thanks

**Comment by mayani** [comment]
**Author:** @vahi

@mayani can you check if pegasus-run on shell code generator will work with --json option , and see what changes are required. thanks

**Comment by mayani** [comment]
**Author:** @mayani

--json seems to already work.

**Comment by mayani** [comment]
**Author:** @vahi

was resolved on sept 22, 2021
