### ISSUE TITLE
[PM-1822] improve parsing of value in Mixins._to_mb(value)

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1935]
To avoid errors like the following, Mixins._to_mb should use a better regex to parse value in _to_mb(value). Example: (\d+) *([MGTPE]?B)

Traceback (most recent call last):
  File "/project/xwang787_675/software/pegasus/default/lib64/python3.6/site-packages/Pegasus/api/mixins.py", line 204, in to_mb
    return int(tokens[0])
ValueError: invalid literal for int() with base 10: '4GB'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/xwang787_675/workflow/YifanLab/src/pacbio/__main__.py", line 37, in pacbio
    generate(sub_bam, ref_genome, base_path, site)
  File "/project/xwang787_675/workflow/YifanLab/src/pacbio/_workflow.py", line 27, in generate
    wf = _generate(sub_bam, ref_genome, base_path, site)
  File "/project/xwang787_675/workflow/YifanLab/src/pacbio/_workflow.py", line 125, in _generate
    wf.add_transformation_catalog(_generate_tc(base_path, site))
  File "/project/xwang787_675/workflow/YifanLab/src/pacbio/_workflow.py", line 197, in _generate_tc
    ).add_condor_profile(request_memory="4GB")
  File "/project/xwang787_675/software/pegasus/default/lib64/python3.6/site-packages/Pegasus/api/mixins.py", line 179, in wrapped_f
    new_kw[nk] = vf(v)
  File "/project/xwang787_675/software/pegasus/default/lib64/python3.6/site-packages/Pegasus/api/mixins.py", line 221, in to_mb
    value
ValueError: value: 4GB should be a str formatted as '<int> [MB | GB | TB | PB | EB]'

**Reporter:** @ryantanaka
**Resolution:** Fixed
**Watchers:**
@mayani
@ryantanaka

**Comment by mayani** [comment]
**Author:** @ryantanaka

maybe to_mb(value) can be updated to be to_mb(value: int, unit: Literal["mb", "gb", "tb", ….]), then value can be passed in as scientific notation, binary, or hex without issues

**Comment by mayani** [comment]
**Author:** @ryantanaka

better way to approach, (rajiv's suggestion)
(.*)([MGTE]B) - Part 1 should be int parseable and latter is optional

**Comment by mayani** [comment]
**Author:** @mayani

Made the changes and added the necessary test cases
