### ISSUE TITLE
[PM-1830] Globus Online transfers required GO consent

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1943]
I tried configuring my workflows to use GO as the transfer protocol.  I had no issues creating a directory on Summit, but when the local directory creation job tried to run using the CARC endpoint, I got the following error:

Traceback (most recent call last):
          File "/home/shock-ssd/scottcal/pegasus/default/lib64/python3.6/site-packages/Pegasus/cli/pegasus-globus-online.py", line 202, in mkdir
            transfer_client.operation_mkdir(request["endpoint"], path)
          File "/home/shock-ssd/scottcal/pegasus/default/lib64/pegasus/externals/python/globus_sdk/transfer/client.py", line 964, in operation_mkdir
            return self.post(resource_path, json_body=json_body, params=params)
          File "/home/shock-ssd/scottcal/pegasus/default/lib64/pegasus/externals/python/globus_sdk/base.py", line 214, in post
            retry_401=retry_401)
          File "/home/shock-ssd/scottcal/pegasus/default/lib64/pegasus/externals/python/globus_sdk/base.py", line 387, in _request
            raise self.error_class(r)
        globus_sdk.exc.TransferAPIError: (403, 'ConsentRequired', 'Missing required data_access consent', 'uJMrBxANz')

I had previously authenticated using the Globus website to both the OLCF DTN and the USC CARC User Directories endpoints, and then ran pegasus-globus-online-init, went to the website, and entered the code.  (BTW, I ran into an error in pegasus-globus-online-init.py; config.set() expects strings but some of the values were ints, so I just wrapped them all in str()).  However, it seems like the authentication isn't working for some reason.  Since the example on the documentation uses the hash notation, I used the extremely human-readable "u_aieoitmpvnbchfh6dhsxvaiarq#b92e5d86-0d7b-11eb-8938-0a5521ff3f4b" for the CARC endpoint (it's the 'Legacy Name' on the endpoint info page).  This particular job is /home/shock/scottcal/runs/USC_Integrated_dax/run_7218/dags/scottcal/pegasus/CyberShake_Integrated_USC/20211113T234036-0800/create_dir_CyberShake_Integrated_USC_0_local.sub.

Thanks for your help!

**Reporter:** @scallag
**Resolution:** Fixed
**Watchers:**
@papajim
@scallag
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

Ok, so this is pretty annoying. It comes down to being logged in is not enough - the endpoint can have extra consent options. Here is an example session with the globus cli:

(globus-cli) ✔ [rynge@workflow:~/software/globus-cli/bin] $ globus session show 
For information on your primary identity or full identity set see 
 globus whoami                                                                                      
                                                                                                    
Username      | ID                                   | Auth Time            
------------- | ------------------------------------ | -------------------- 
rynge@usc.edu | 8cc20f7c-5516-470e-99e3-6630e66247d8 | 2021-11-17 10:23 PST 
(globus-cli) ✔ [rynge@workflow:~/software/globus-cli/bin] $ globus ls 56569ec1-af41-4745-a8d1-851423
1c7a6d 
The collection you are trying to access data on requires you to grant consent for the Globus CLI to 
access it. 
message: Missing required data_access consent 

Please run 

 globus session consent 'urn:globus:auth:scope:transfer.api.globus.org:all[*https://auth.globus.org
/scopes/56569ec1-af41-4745-a8d1-8514231c7a6d/data_access]' 

to login with the required scopes 
(globus-cli) ✘-4 [rynge@workflow:~/software/globus-cli/bin] $ globus session consent 'urn:globus:aut
h:scope:transfer.api.globus.org:all[*https://auth.globus.org/scopes/56569ec1-af41-4745-a8d1-8514231c
7a6d/data_access]' 
Please authenticate with Globus here: 
------------------------------------ 
https://auth.globus.org/v2/oauth2/authorize?client_id=65185b0e-4c7b-4a36-8c3f-5c4aeebb667d&redirect_
uri=https%3A%2F%2Fauth.globus.org%2Fv2%2Fweb%2Fauth-code&scope=urn%3Aglobus%3Aauth%3Ascope%3Atransfe
r.api.globus.org%3Aall%5B%2Ahttps%3A%2F%2Fauth.globus.org%2Fscopes%2F56569ec1-af41-4745-a8d1-8514231
c7a6d%2Fdata_access%5D+openid+profile+email+urn%3Aglobus%3Aauth%3Ascope%3Aauth.globus.org%3Aview_ide
ntity_set&state=_default&response_type=code&access_type=offline&prompt=login 
------------------------------------ 

Enter the resulting Authorization Code here: 

You have successfully updated your CLI session. 

(globus-cli) ✔ [rynge@workflow:~/software/globus-cli/bin] $ globus ls 56569ec1-af41-4745-a8d1-851423
1c7a6d 
git/ 
notifications/ 
software/ 
test-jobs/ 
old-main.py 
test.py

This extra step is obviously an issue as we can't have the workflow jobs hit this at runtime - we need to catch it before starting the workflow. I will have to explore how to properly discover and implement this. This point is that it is not going to be a quick easy fix.

**Comment by mayani** [comment]
**Author:** @papajim

Would you like me to take a look at this? I think we can get a simple solution by updating our globus sdk support.

**Comment by mayani** [comment]
**Author:** @scallag

Sure, if you have a minute.  My current solution is OK but has poor error management and recovery, and I'd like to move to something more robust.

**Comment by mayani** [comment]
**Author:** @papajim

@scallag What's a good way for me to test things? Do I / Should I have access to the USC globus endpoint you are using?

**Comment by mayani** [comment]
**Author:** @scallag

I'm using the CARC endpoint ("USC CARC User Directories") to transfer to/from the /project filesystem there.  I think you should have access, if you have a USC CARC account.

**Comment by mayani** [comment]
**Author:** @papajim

A new option "-e | --endpoints" has been added to "pegasus-globus-online-init".
With this option you can now add the endpoints that require data consent during initialization of your globus tokens.

Changes have been pushed to the 5.0 branch and master branch.

Also globus-sdk was bumped to version 3. Now pegasus externals ship with globus-sdk v.3.5.0. globus-sdk only supports python versions 3.6+

@rynge will test this out

**Comment by mayani** [comment]
**Author:** @vahi

@ryngeplease test and close
