### ISSUE TITLE
[PM-1832] extraneous whitespace in arguments for sub workflow job with java generator

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#1945]
type: "job"
  name: "GenSGTDax"
  namespace: "scec"
  version: "1.0"
  id: "GenSGTDax_TEST"
  profiles:
    hints:
      executionPool: "local"
  arguments:
   - "-r 7214"
   - " "
   - "-gf gridout_TEST"
   - " "
   - "-o AWP_SGT_TEST.dax"
   - " "
   - "-sr moment.usc.edu"
   - " "
   - "-sp 0.2"
   - " "
   - "-mv 500.0"
  uses:
   -
    lfn: "gridout_TEST"
    type: "input"
    stageOut: true
    registerReplica: true
   -
    lfn: "AWP_SGT_TEST.dax"
    type: "output"
    stageOut: false
    registerReplica: false
 -
  type: "pegasusWorkflow"
  file: "AWP_SGT_TEST.dax"
  id: "AWP_SGT_TEST"
  arguments:
   - "--force"
   - " "
   - "--basename AWP_SGT_TEST"
   - " "
   - "--cleanup inplace"
  uses: []

this causes the planner to fail while planning for the sub workflow job with but now I get the error:

2021.10.29 14:41:42.187 PDT: [DEBUG]  Arguments passed to SUBDAX Generator are --force   --basename AWP_SGT_TEST   --cleanup inplace AWP_SGT_TEST.dax
2021.10.29 14:41:42.188 PDT: [INFO] event.pegasus.code.generation dax.id CyberShake_Integrated_TEST-0  (0.079 seconds) - FINISHED
2021.10.29 14:41:42.188 PDT: [FATAL ERROR]  java.lang.RuntimeException: Unable to generate code
at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:641)
at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:322)
at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:209)
Caused by: java.lang.RuntimeException: Unparsed component "" of the command line argument string:  --force   --basename AWP_SGT_TEST   --cleanup inplace AWP_SGT_TEST.dax
at edu.isi.pegasus.planner.client.CPlanner.parseCommandLineArguments(CPlanner.java:958)
at edu.isi.pegasus.pl

**Reporter:** @scallag
**Resolution:** Fixed
**Watchers:**
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

this is related to how arguments were padded for writing out to the XML dax'es in the API. the argument padding should happen only in toXML() methods when serializing arguments.

**Comment by mayani** [comment]
**Author:** @vahi

was fixed nov 19, 2021
