### ISSUE TITLE
[PM-80] Null pointer exception in prejob when using pegasus.transfer.proxy = true i.e. Handling the transfer of proxies in case of Second Level Staging.

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#201]
In attachement all the pegasus configuration files needed (tc.data, rc.data,DAX and properties file and command line to call pegasus-plan)

Also, you can find all this files in the svn here:
https://pegasus.isi.edu/svn/page/trunk/QC-workflow/

Here is the error message that I got:

2009.12.03 15:28:39.329 PST: [DEBUG]  Trying to get TCEntries for pegasus::dirmanager on resource wind of type INSTALLED 
2009.12.03 15:28:39.329 PST: [DEBUG]  Creating a default TC entry for pegasus::dirmanager at site wind 
2009.12.03 15:28:39.330 PST: [INFO] event.pegasus.generate.workdir-nodes dax.id pageQC_0  - FINISHED 
2009.12.03 15:28:39.330 PST: [INFO] event.pegasus.generate.cleanup-wf dax.id pageQC_0  - STARTED 
2009.12.03 15:28:39.333 PST: [DEBUG]  Trying to get TCEntries for pegasus::dirmanager on resource wind of type INSTALLED 
2009.12.03 15:28:39.334 PST: [INFO] event.pegasus.generate.cleanup-wf dax.id pageQC_0  - FINISHED 
2009.12.03 15:28:39.334 PST: [INFO] event.pegasus.refinement dax.id pageQC_0  - FINISHED 
2009.12.03 15:28:39.399 PST: [DEBUG]  Condor Version as string 7.0.1 
2009.12.03 15:28:39.399 PST: [DEBUG]  Condor Version detected is 70001 
2009.12.03 15:28:39.400 PST: [INFO]  Generating codes for the concrete workflow 
2009.12.03 15:28:39.419 PST: [DEBUG]  Condor logs directory to be used is null 
2009.12.03 15:28:39.419 PST: [DEBUG] event.pegasus.code.generation dax.id pageQC_0  - STARTED 
2009.12.03 15:28:39.424 PST: [DEBUG]  Enabling job for worker node execution read_initial_data_ID000001 
2009.12.03 15:28:39.431 PST: [DEBUG]  Trying to get TCEntries for pegasus::transfer on resource wind of type INSTALLED 
2009.12.03 15:28:39.432 PST: [DEBUG]  Unquoted Prejob is  /bin/bash -c "chmod 600 null/x509up_u1039 && /nfs/software/pegasus/default/bin/transfer base mnt /nfs/home/rbolze/devel/PAGE/QC-workflow/sls_read_initial_data_ID000001.in" 
2009.12.03 15:28:39.433 PST: [DEBUG]  Quoted Prejob is  /bin/bash -c 'chmod 600 null/x509up_u1039 && /nfs/software/pegasus/default/bin/transfer base mnt /nfs/home/rbolze/devel/PAGE/QC-workflow/sls_read_initial_data_ID000001.in' 
2009.12.03 15:28:39.461 PST: [FATAL ERROR]  
 [1] java.lang.RuntimeException: Unable to generate code at org.griphyn.cPlanner.toolkit.CPlanner.executeCommand(CPlanner.java:515)
 [2] java.lang.NullPointerException: null at java.io.Writer.write(Writer.java:140) 
2009.12.03 15:28:39.461 PST: [WARNING]  Non-zero exit-code 1 
2009.12.03 15:28:39.461 PST: [INFO] event.pegasus.code.generation dax.id pageQC_0  - FINISHED

**Reporter:** @rbolze
**Resolution:** Fixed
**Watchers:**
@vahi
**Attachments:**

**Comment by mayani** [comment]
**Author:** @vahi

The NPE is thrown because if the transfer.proxy is set for SLS, the headnode directory becomes null.
Looking at the code , this is because pegasus explicitly removes the directory from the job description if it detects transfer of proxy is set to true.
This is true for the FIRST LEVEL STAGING scenario but not for SLS, where we need to generate the the urls for the SLS files we need to know the head node directory.

To remove the NPE, we need to remove the directory only if worker node execution / SLS is disabled.

**Comment by mayani** [comment]
**Author:** @vahi

fter fixing the NPE, I notice that the compute jobs did not have the X509_USER_PROXY environment variable set if pegasus.transfer.proxy is set to true in case of worker node execution. 
Also the environment variable was incorrect for third party transfer jobs that execute on the local host. This is also now fixed.

**Comment by mayani** [comment]
**Author:** @vahi

The fix for the bug results in NPE if you turn on clustering for the workflows in the case when you running on teh shared filesystem.
The NPE was because the function getDirectoryKey in Kickstart.java was called in the beginning.

This is because during clustering , the constituent jobs are enabled . However at that point the directory is not set in condor profiles for the job.

The handling of the following VDS profile keys should only be done if the enabling is being done in the code generation module, not when done as part of the clustered job.

VDS.CHANGE_DIR_KEY
VDS.CREATE_AND_CHANGE_DIR_KEY 
VDS.TRANSFER_PROXY_KEY

**Comment by mayani** [comment]
**Author:** @vahi

resolved for 3.0 release
