### ISSUE TITLE
[PM-1898] File dependencies for sub workflow jobs - differentiate inputs for planner use and those for sub workflow

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#2011]
With the 5.0 release, we allow users to specify inputs for their sub workflow jobs

For example, as in this example
https://github.com/pegasus-isi/hierarichal-sample-wf 

- type: pegasusWorkflow
  file: inner_diamond_workflow.yml
  id: diamond_subworkflow
  arguments:
  - --conf
  - inner_diamond_workflow.pegasus.properties
  - --output-sites
  - local
  - -vvv
  - --basename
  - inner
  uses:
  - lfn: pegasus.html
    type: input
  - lfn: f.d
    type: output
    stageOut: true
    registerReplica: true
  - lfn: sites.yml
    type: input
  - lfn: inner_diamond_workflow_tc.yml
    type: input
  - lfn: inner_diamond_workflow.yml
    type: input
  - lfn: inner_diamond_workflow.pegasus.properties
    type: input

the diamond sub workflow has 4 input dependenices

1. pegasus.html
2.  inner_diamond_workflow_tc.yml
3.  inner_diamond_workflow.yml
4.   inner_diamond_workflow.pegasus.properties

Of these dependencies in pegasus.html is an input file that is required by a job in diamond sub workflow while it runs, whereas the remaining files are required to plan the sub workflow. 

In Pegasus the planning of the sub workflow only happens on the submit host, and hence the files need to be brought down to the submit host. 

The pegasus.html file on the other hand is required by a compute job in the sub workflow diamond, and should be pulled down only when the compute job is run.

Currently, since there is no way to differentiate these files the planner always setups all the inputs for the sub workflow to be pulled down to the submit host, even though the file (pegasus.html in this case) needs to be pulled down only when the sub workflow runs.  this duplicate transfer to submit host can create problems on 2 fronts
- extra files downloaded to the submit host that are not required. 
- if using globus online for workflows, usually there is no local endpoint for submit host, and the workflow ends up failing. 

We need a way in the API to differentiate a file that is for planner use in the sub workflow to avoid this.

**Reporter:** @vahi
**Resolution:** Fixed
**Watchers:**
@papajim
@rynge
@mayani
@scallag
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

Scott ran into this issue, when doing recent production runs 

Hello,

I ran into another issue.  When trying to plan one of my sub-workflows, I get the following error:

2022-12-17 16:11:23: PegasusLite: version 5.0.3
2022-12-17 16:11:23: Executing on host shock.hpc.usc.edu IP=68.181.40.23

########################[Pegasus Lite] Setting up workdir ########################
2022-12-17 16:11:23: Checking /tmp for potential use as work space...
2022-12-17 16:11:23:   Workdir is /tmp/pegasus.bSNCqFX9s - 38G available
2022-12-17 16:11:23: Changing cwd to /tmp/pegasus.bSNCqFX9s

###################### Staging in input data and executables ######################
2022-12-17 16:11:24,045    INFO:  Reading URL pairs from stdin
2022-12-17 16:11:24,046    INFO:  4 transfers loaded
2022-12-17 16:11:24,046    INFO:  PATH=/home/shock-ssd/scottcal/java/default/bin:/home/shock-ssd/scottcal/pegasus/default/bin:/sbin:/bin:/usr/sbin:/usr/bin
2022-12-17 16:11:24,046    INFO:  LD_LIBRARY_PATH=
2022-12-17 16:11:24,096    INFO:  --------------------------------------------------------------------------------
2022-12-17 16:11:24,096    INFO:  Starting transfers - attempt 1
Traceback (most recent call last):
  File "/home/shock-ssd/scottcal/pegasus/default/lib64/python3.6/site-packages/Pegasus/cli/pegasus-transfer.py", line 5436, in <module>
    main()
  File "/home/shock-ssd/scottcal/pegasus/default/lib64/python3.6/site-packages/Pegasus/cli/pegasus-transfer.py", line 5352, in main
    ts = SimilarWorkSet(t_list, completed_q, failed_q)
  File "/home/shock-ssd/scottcal/pegasus/default/lib64/python3.6/site-packages/Pegasus/cli/pegasus-transfer.py", line 4403, in __init__
    % (src_proto, dst_proto)
RuntimeError: Unable to find handlers for 'go' to 'file' transfers
2022-12-17 16:11:24: Last command exited with 1
2022-12-17 16:11:24: /tmp/pegasus.bSNCqFX9s cleaned up
PegasusLite: exitcode 1

I looked at the *.pre.sh script, and I see the problematic file transfers:

[
 { "type": "transfer",
   "linkage": "input",
   "lfn": "SABD.modelbox",
   "id": 1,
   "src_urls": [
     { "site_label": "local", "url": "go://56569ec1-af41-4745-a8d1-8514231c7a6d/scratch2/scottcal/cybershake/execdir/scottcal/pegasus/CyberShake_Integrated_SABD/20221217T160409-0800/./SABD.modelbox", "checkpoint": "false" }
   ],
   "dest_urls": [
     { "site_label": "local", "url": "file://$PWD/SABD.modelbox" }
   ] }
 ,

I checked my site catalog, and I have GO endpoints listed for site 'local', so I'm not sure why it's using the file protocol.  Do you have ideas on how to force it to use GO?  Thanks!

-Scott

**Comment by mayani** [comment]
**Author:** @vahi

the planner now internally track a boolean flag with each file that indicates whether it is for planner use or not. defaults to false. for dax versions >= 5.0.4 we check for this flag, to determine if an input file needs to be pulled down when planning a sub workflow as part of the prescript.

setting of this flag still needs to be exposed in the workflow generation API's.
