### ISSUE TITLE
[PM-1905] file dependencies between sub workflow and compute jobs broken

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#2018]
The test is that we can use a file produced in a subworkflow as the input to a job. This worked previously, but seems to be leading to this planning error now.

Planner invoked with following arguments --conf /home/runner/work/pycbc/pycbc/examples/workflow/generic/simple_subworkflow_data/pycbc-tmp_rvc_2r3l/work/pegasus.2602818085757992491.properties --dir /home/runner/work/pycbc/pycbc/examples/workflow/generic/simple_subworkflow_data/pycbc-tmp_rvc_2r3l --relative-dir work/./sub1.dax_sub1 --relative-submit-dir work/././sub1.dax_sub1 --basename sub1 --sites condorpool_symlink,local --staging-site condorpool_symlink=local,local=local, --cache /home/runner/work/pycbc/pycbc/examples/workflow/generic/simple_subworkflow_data/pycbc-tmp_rvc_2r3l/work/./pegasus-plan_sub1.cache --inherited-rc-files /home/runner/work/pycbc/pycbc/examples/workflow/generic/simple_subworkflow_data/pycbc-tmp_rvc_2r3l/work/cont.dax-0.replica.store --cluster label,horizontal --output-map /home/runner/work/pycbc/pycbc/examples/workflow/generic/simple_subworkflow_data/pycbc-tmp_rvc_2r3l/work/./pegasus-plan_sub1.output.map --output-sites local --cleanup inplace --verbose --verbose --verbose --deferred /home/runner/work/pycbc/pycbc/examples/workflow/generic/simple_subworkflow_data/sub1.dax

..
2023.02.20 19:17:20.206 UTC: [CONFIG]  Transfer Refiner loaded is           [Balanced Cluster Transfer Refiner( round robin distribution at file level)] 
2023.02.20 19:17:20.206 UTC: [CONFIG]  ReplicaSelector loaded is            [Regex] 
2023.02.20 19:17:20.207 UTC: [CONFIG]  Submit Directory Mapper loaded is    [Relative Submit Directory Mapper] 
2023.02.20 19:17:20.207 UTC: [CONFIG]  Staging Mapper loaded is             [Flat Directory Staging Mapper] 
2023.02.20 19:17:20.209 UTC: [DEBUG]  SRM Server map is {} 
2023.02.20 19:17:20.209 UTC: [DEBUG]  SRM Server map is {} 
2023.02.20 19:17:20.209 UTC: [DEBUG]  Directory for job exe1_ID0_ID0000001 is exe1 
2023.02.20 19:17:20.209 UTC: [DEBUG]   
2023.02.20 19:17:20.209 UTC: [DEBUG]  Job being traversed is exe1_ID0_ID0000001 
2023.02.20 19:17:20.209 UTC: [DEBUG]  To be run at condorpool_symlink 
2023.02.20 19:17:20.209 UTC: [DEBUG]  Parents of job:{} 
2023.02.20 19:17:20.211 UTC: [FATAL ERROR]  edu.isi.pegasus.planner.mapper.MapperException: [Replica] Unable to retrive location from Mapper Replica Backend for lfn test_output.txt.2 for site local and operation put
	at edu.isi.pegasus.planner.mapper.output.Replica.mapAll(Replica.java:247)
	at edu.isi.pegasus.planner.transfer.generator.StageOut.constructFileTX(StageOut.java:431)
	at edu.isi.pegasus.planner.transfer.generator.StageOut.constructFileTX(StageOut.java:298)
	at edu.isi.pegasus.planner.refiner.TransferEngine.addTransferNodes(TransferEngine.java:284)
	at edu.isi.pegasus.planner.refiner.MainEngine.r

**Reporter:** @spxiwh
**Resolution:** Fixed
**Watchers:**
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

from @spxiwh
I took over from Alex following this up while Alex is travelling. I’ll send the requested tar balls by email, but think I’ve spotted the problem. In 5.0.3 there is an output map file for each of the workflows, which is sent when planning that workflow. 5.0.3 stages this file in correctly. 5.0.5 does not stage this file in and then things fail. Strangely it does not report that the file does not exist, but fails because it can’t find it.
Not sure if that is clear, but the place to see the difference is by diff ing the file called pegasus-plan_sub1.pre.sh in the tarballs I am sending you. The 5.0.5 file does not do a necessary transfer.
It may be the case that this isn’t the right way to do it, but I think we’re doing what was recommended after discussing this last year. Our basic example which raises this failure is here:
https://github.com/gwastro/pycbc/tree/master/examples/workflow/generic/multilevel_subworkflow_data and this can be run on any machine with pycbc (2.0.5) installed and pegasus/condor etc.

**Comment by mayani** [comment]
**Author:** @vahi

this bug is artifact of #2011 the planner does not set the forPlanning flag for the output map files that it wants the sub workflow job to use

**Comment by mayani** [comment]
**Author:** @vahi

@spxiwh i looked at it a bit more, in the submit directory that Ian shared with me. in your test abstract workflow you have
- type: pegasusWorkflow
 file: sub1.dax
 id: sub1
 arguments:
 - -Dpegasus.dir.storage.mapper.replica.file=sub1.map
 - --basename
 - sub1
 - --cluster
 - label,horizontal
 - --output-sites
 - local
 - --staging-site
 - local=local,condorpool_symlink=local
 - --cleanup
 - inplace
 - -vvv
 uses:
 - lfn: sub1.map
  type: input
 - lfn: sub1.dax
  type: input
 - lfn: test_output.txt.2
  type: output
  stageOut: true
  registerReplica: true
the sub1.map file when adding to the sub workflow as an input  should have the for_planning attribute set to true.
For example see this
https://github.com/pegasus-isi/hierarichal-sample-wf/blob/cf80f2f8488fddf453f1859400f6959537b84a3f/workflow_generator.py#L158 (edited)

**Comment by mayani** [comment]
**Author:** @vahi

from @spxiwhApologies, I’m not sure this has solved the problem in all cases. We do have some examples where the dax file for a subworkflow is generated during the parent workflow. In this case the dax file is transferred around and needs to be staged in to the planner job. However, this file is currently not being staged in:
If I see the code here, I don’t see any way that I can add the necessary flag because the self.file that is sent to add_inputs will always be a string. How do I ensure that the dax file in a SubWorkflow gets the for_planning attribute?

**Comment by mayani** [comment]
**Author:** @vahi

i did review our code , and the planner internally makes sure that the daxLFN has the setForPlanning attribute set to true. can you share you failed test submit dir with me please. unless in your abstract workflow, the dax file lfn appears in the uses tag also?

**Comment by mayani** [comment]
**Author:** @vahi

i have updated the python workflow API to also generate the for_planning attribute and set it to true for the workflow file corresponding to the SubWorkflow job. The file mentioned in the file attribute, will now have forPlanning rendered to True in the uses tag 

- type: pegasusWorkflow 
  file: inner_diamond_workflow.yml 
  id: diamond_subworkflow 
  arguments: [--conf, inner_diamond_workflow.pegasus.properties, --output-sites, local, 
    -vvv, --basename, inner] 
  uses: 
  - {lfn: inner_diamond_workflow_rc.yml, forPlanning: true, type: input} 
  - {lfn: inner_diamond_workflow.yml, forPlanning: true, type: input} 
  - {lfn: inner_diamond_workflow.pegasus.properties, forPlanning: true, type: input} 
  - {lfn: inner_diamond_workflow_tc.yml, forPlanning: true, type: input} 
  - {lfn: sites.yml, forPlanning: true, type: input} 

Additionally, i have coded in a failsafe in the planner to ensure that the forPlanning attribute is set to True for the workflow file referred to by the file attribute
