### ISSUE TITLE
[PM-1939] Planner complains on http transfers if the user does not have a credentials file setup

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#2052]
Discovered a potential change in the behavior of Pegasus 5.0.7 and 5.0.6 that is causing our workflows to fail after the update. At the moment, we think they might potentially be related to this change (#2048). The error our jobs are reporting is
 
2024.02.22 14:45:27.057 UTC: [FATAL ERROR] java.lang.RuntimeException: Unable to generate code at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:641) at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:328) at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:206) Caused by: java.lang.RuntimeException: Unable to verify credential of type http for job stage_worker_local_gw-main.dax_0_local.

**Reporter:** @spxiwh
**Resolution:** Fixed
**Watchers:**
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

@spxiwh can you confirm if doing touch ~/.pegasus/credentials.conf makes the error goes away

**Comment by mayani** [comment]
**Author:** @vahi

resolved and added unit tests
