### ISSUE TITLE
[PM-1941] illegal state exception while using inplace cleanup

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#2054]
I am having a weird issue when using pegasus:
 
2024.02.19 15:31:02.889 EST: [FATAL ERROR] java.lang.IllegalStateException at java.base/java.util.HashMap$HashIterator.remove(HashMap.java:1617) at edu.isi.pegasus.planner.refiner.cleanup.InPlace.addCleanUpJobs(InPlace.java:158) at edu.isi.pegasus.planner.refiner.cleanup.InPlace.addCleanupJobs(InPlace.java:60) at edu.isi.pegasus.planner.refiner.CleanupEngine.addCleanupJobs(CleanupEngine.java:51) at edu.isi.pegasus.planner.refiner.MainEngine.runPlanner(MainEngine.java:255) at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:603) at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:322) at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:209)
This is the executable
 
./pegasus-plan_gw-main.pre.sh -Dpegasus.log.*=/path/to/pegasus-plan_gw-main.pre.log -Dpegasus.workflow.root.uuid=1a2ba953-26fe-43a8-9e7b-a5b23794529b -Dpegasus.dir.storage.mapper.replica.file=gw-main.map -Dpegasus.dir.storage.mapper.replica.file=gw-main.map --conf pegasus.5949411531374299041.properties --dir pycbc-tmp_zmx8la4l --relative-dir gw-main.dax_gw-main --relative-submit-dir gw-main.dax_gw-main --basename gw-main --sites condorpool_shared,condorpool_symlink,condorpool_copy,local --staging-site condorpool_shared=condorpool_shared,condorpool_symlink=local,condorpool_copy=local,local=local, --cache pegasus-plan_gw-main.input.cache --inherited-rc-files gw.dax-0.replica.store --cluster label,horizontal --output-sites local --cleanup inplace --verbose --verbose --verbose --deferred gw-main.dax

**Reporter:** @spxiwh
**Resolution:** Fixed
**Watchers:**
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

https://github.com/kkacanja/JAVA_Error/

**Comment by mayani** [comment]
**Author:** @vahi

pushed out a fix and has been confirmed that it works by keinci
