### ISSUE TITLE
[PM-1943] mixed binary/conda installs broken

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#2056]
However, using `export PEGASUS_UPDATE_PYTHONPATH=0` as suggested here [https://pegasus.isi.edu/documentation/user-guide/installation.html#mixing-environments-system-venv-conda] hits some issues:
  * First, I needed to install the complete pegasus-wms package. pegasus-wms.api (as we use currently) does not work because Pegasus.db is not installed, and seems required if setting this option (although Pegasus.db exists in the systemwide install, we no longer use it). We can add the bigger package if needed though.
  * Then, when submitting a workflow (using pegasus.api to plan and submit a workflow at generation time) the PEGASUS_UPDATE_PYTHONPATH=0 variable is not passed to the running workflow and when pegasus-plan is invoked to run subworkflows, it will fail. If I stop the workflow, and then restart again with pegasus-run, the variable *is* picked up. It would definitely be good to figure out a fix to this one as "plan and submit when generating a workflow" is now our default use case.
 * Finally we then see failures in jobs mid-workflow that look something like "Integrity check: No checksum in the meta data for H1L1V1-BANK2HDF-1186740100-3400.hdf". Indeed there is no checksum in the metadata for that file (or any of the other inputs). The test workflow is definitely a bit weird, as we look to test a number of features rather than do something sensible, and I think this is probably related to using many different "sites" for various jobs.

**Reporter:** @spxiwh
**Resolution:** Fixed
**Watchers:**
@vahi
**Attachments:**

**Comment by mayani** [comment]
**Author:** @vahi

The PEGASUS_UPDATE_PYTHONPATH not being passed down to DAGMan is related to change in dagman behavior, which was discussed in #2023. 

part of the fix for this is to add PEGASUS_UPDATE_PYTHONPATH to the list of variables that get specified in the the environment classed (specified just before the queue command) of the generated .dag.condor.sub file by Pegasus.

I suspect PEGASUS_UPDATE_PYTHONPATH gets sometime passed through because of this in .dag.condor.sub

 

```java

getenv      = CONDOR_CONFIG,_CONDOR_*,PATH,PYTHONPATH,PERL*,PEGASUS_*,TZ,HOME,USER,LANG,LC_ALL,BEARER_TOKEN,BEARER_TOKEN_FILE,XDG_RUNTIME_DIR
```

We should make it explicit by always setting PEGASUS_UPDATE_PYTHONPATH if detected that it is set .

**Comment by mayani** [comment]
**Author:** @vahi

@spxiwh at our end, if i do a clean conda env with dependencies via virtualenv, i hit into the error earlier, while planning the first sub workflow in the prescript 

  

ail -n 200 pegasus-plan_gw-main.pre.log.000 

```java

File "/usr/lib64/python3.6/site-packages/Pegasus/db/admin/__init__.py", line 1, in <module> 
2024.05.30 13:31:32.472 PDT: [ERROR]      from Pegasus.db.admin.admin_loader import * 
2024.05.30 13:31:32.477 PDT: [ERROR]    File "/usr/lib64/python3.6/site-packages/Pegasus/db/admin/admin_loader.py", line 32, in <module> 
2024.05.30 13:31:32.483 PDT: [ERROR]      from Pegasus.db.schema import * 
2024.05.30 13:31:32.488 PDT: [ERROR]    File "/usr/lib64/python3.6/site-packages/Pegasus/db/schema.py", line 44, in <module> 
2024.05.30 13:31:32.493 PDT: [ERROR]      from Pegasus.db.ensembles import Ensemble as _Ensemble 
2024.05.30 13:31:32.498 PDT: [ERROR]    File "/usr/lib64/python3.6/site-packages/Pegasus/db/ensembles.py", line 7, in <module> 
2024.05.30 13:31:32.503 PDT: [ERROR]      from flask import url_for 
2024.05.30 13:31:32.509 PDT: [ERROR]    File "/usr/lib64/pegasus/externals/python/flask/__init__.py", line 14, in <module> 
2024.05.30 13:31:32.514 PDT: [ERROR]      from jinja2 import escape 
2024.05.30 13:31:32.519 PDT: [ERROR]    File "/usr/lib64/pegasus/externals/python/jinja2/__init__.py", line 6, in <module> 
2024.05.30 13:31:32.524 PDT: [ERROR]      from markupsafe import escape 
2024.05.30 13:31:32.529 PDT: [ERROR]    File "/usr/lib64/python3.6/site-packages/markupsafe/__init__.py", line 13, in <module> 
2024.05.30 13:31:32.535 PDT: [ERROR]      from collections import Mapping 
2024.05.30 13:31:32.540 PDT: [ERROR]  ImportError: cannot import name 'Mapping' from 'collections' (/scitech/shared/projects/LIGO/test-wf/env/lib/python3.10/collections/__init__.py) 
2024.05.30 13:31:32.545 PDT: [DEBUG]  pegasus-db-admin exited with status 1 
2024.05.30 13:31:32.546 PDT: [FATAL ERROR]  java.lang.RuntimeException: /usr/bin/pegasus-db-admin update -t master -c /scitech/nas/home/bamboo/test/vahi/ligo-search/pycbc/examples/search/output/pycbc-tmp.M2Y3V9T6cC/work/././gw-main.dax_gw-main.000/pegasus.8752603151459610282.properties failed with status 1 . Pegasus was unable to update the the worflow database file found at ~/.pegasus/workflow.db . If this file is corrupted, a solution for problem is to remove the file with the command: rm -f ~/.pegasus/workflow.db  - but note that doing so will remove old workflows from the Pegasus Dashboard.
at edu.isi.pegasus.planner.common.PegasusDBAdmin.checkDatabase(PegasusDBAdmin.java:262)
at edu.isi.pegasus.planner.common.PegasusDBAdmin.checkMasterDatabaseForVersionCompatibility(PegasusDBAdmin.java:142)
at edu.isi.pegasus.planner.client.CPlanner.checkMasterDatabaseForVersionCompatibility(CPlanner.java:1961)
at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:657)
at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:333)
at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:207)
 

```

 I am curious, why you did not run into this issue? 

In my env , i have

 

```java

(base) [bamboo@bamboo work]$ env | grep PEGASUS_
PEGASUS_UPDATE_PYTHONPATH=0

```

**Comment by mayani** [comment]
**Author:** @vahi

[^dagman_prescript_env.tgz]

^The environment corruption is happening in pegasus-dagman. the attached tar file indicates that in the *dag.condor.sub file if the executable is condor_dagman then the prescript gets PEGASUS_UPDATE_PYTHONPATH variable. If executable is pegasus-dagman, then it does not^

@rynge if u have the chance to take a look at it , please do

**Comment by mayani** [comment]
**Author:** @vahi

pegasus-dagman explicily removes the PEGASUS environment variables
 
https://github.com/pegasus-isi/pegasus/blob/cfc3828730c412028e631fb173fc5711bc76df96/packages/pegasus-python/src/Pegasus/cli/pegasus-dagman.py#L88
 
This is related to the fix we did for LIGO
#1850
 
Enabling pass through of PEGASUS_UPDATE_PYTHONPATH might fix this. will try
