### ISSUE TITLE
[PM-1949] NPE while planning a sub workflow

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#2062]
ever, I'm getting a planning failure on the subworkflow.  In the log file I see:
 
2024.05.02 12:33:31.834 PDT: [FATAL ERROR]  
 [1] java.lang.RuntimeException: Unable to generate code at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:646)
 [2] java.lang.NullPointerException: null at edu.isi.pegasus.planner.code.gridstart.Kickstart.enable(Kickstart.java:637)
 
The err file shows a successful transfer and then the Pegasus Lite record.  I don't see anything obviously wrong with the abstract workflow file.
 
My working directory is on shock-carc at /home/shock/scottcal/runs/SFF22_SGT_dax/run_10672/dags/scottcal/pegasus/CyberShake_SGT_SFF22.dax/20240502T122756-0700 .  The pre script is pegasus-plan_AWP_SGT_SFF22.pre.sh and the log and error files are pegasus-plan_AWP_SGT_SFF22.pre.log.002 and
pegasus-plan_AWP_SGT_SFF22.pre.err.002.  Thanks for your help!

**Reporter:** @scallag
**Resolution:** Fixed
**Watchers:**
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

the issue here was that the user had an incomplete tc entry that they were trying to override profiles from

 
in your TC you have
 
#Adding this to try to pick up correct account for frontier

        site frontier {

                profile pegasus "nodes" "1"

                profile globus "maxwalltime" "60"

                profile globus "project" "GE0156"

        }

 

for pegasus transfer, and not defined the PFN

resolving this for time being. not clear if we want to support this case or not
