### ISSUE TITLE
[PM-1983] AWS Batch Error:  ClientException:   Maximum number of jobs supported is  100

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#2086]
On a user workflow running on AWS Batch, we noticed Exception : Maximum number of jobs supported is  100 

```java

 2024-10-01 16:34:06.234 ERROR [Synch] Unknown Exception 
software.amazon.awssdk.services.batch.model.ClientException: Error executing request, Exception : Maximum number of jobs supported is  100 ., RequestId: 509000be-0a78-483b-8685-64f5e5b6f3f8 (Service: null; Status Code: 400; Error Code: ClientException; Re
quest ID: 509000be-0a78-483b-8685-64f5e5b6f3f8)
	at software.amazon.awssdk.http.pipeline.stages.HandleResponseStage.handleErrorResponse(HandleResponseStage.java:119) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:70) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:56) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:41) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:203) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.ExceptionReportingStage.execute(ExceptionReportingStage.java:41) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.ExceptionReportingStage.execute(ExceptionReportingStage.java:30) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.TimerExceptionHandlingStage.execute(TimerExceptionHandlingStage.java:40) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.TimerExceptionHandlingStage.execute(TimerExceptionHandlingStage.java:30) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:187) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:144) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:78) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:52) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:203) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.StreamManagingStage.execute(StreamManagingStage.java:61) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.StreamManagingStage.execute(StreamManagingStage.java:45) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.AfterCallbackStage.execute(AfterCallbackStage.java:47) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.AfterCallbackStage.execute(AfterCallbackStage.java:35) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.ClientExecutionTimedStage.executeWithTimer(ClientExecutionTimedStage.java:74) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.ClientExecutionTimedStage.execute(ClientExecutionTimedStage.java:57) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.ClientExecutionTimedStage.execute(ClientExecutionTimedStage.java:41) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:203) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:450) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.client.ClientHandlerImpl.doInvoke(ClientHandlerImpl.java:219) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.client.ClientHandlerImpl.invoke(ClientHandlerImpl.java:201) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.client.ClientHandlerImpl.execute(ClientHandlerImpl.java:104) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.client.SdkClientHandler.execute(SdkClientHandler.java:41) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.services.batch.DefaultBatchClient.describeJobs(DefaultBatchClient.java:649) ~[batch-2.0.0-preview-2.jar:?]
	at edu.isi.pegasus.aws.batch.impl.Synch.monitor(Synch.java:620) ~[pegasus-aws-batch.jar:?]
	at edu.isi.pegasus.aws.batch.impl.Synch.lambda$monitor$2(Synch.java:487) ~[pegasus-aws-batch.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
R 
```

Even though it is not a mentioned limit, 

[https://docs.aws.amazon.com/batch/latest/userguide/service_limits.html]

**Reporter:** @vahi
**Resolution:** Fixed
**Watchers:**
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

Looking at the stack trace it seems the error is being encountered when monitoring for the various job status at 

```java

software.amazon.awssdk.services.batch.DefaultBatchClient.describeJobs(DefaultBatchClient.java:649) ~[batch-2.0.0-preview-2.jar:?] at edu.isi.pegasus.aws.batch.impl.Synch.monitor(Synch.java:620) ~[pegasus-aws-batch.jar:?] at edu.isi.pegasus.aws.batch.impl.Synch.lambda$monitor$2(Synch.java:487) ~[pegasus-aws-batch.jar:?]
```

**Comment by mayani** [comment]
**Author:** @vahi

as part of this, we also moved away from using the listJobs method and in the monitoring thread loop we only use the describeJobs limit for the jobs in the workflow.

 

the listJobs method we were using to query for successful and failed jobs in a job queue was not binned to a workflow, and also had 1000 response limit. 

[https://docs.aws.amazon.com/batch/latest/APIReference/API_ListJobs.html#API_ListJobs_RequestSyntax]
