### ISSUE TITLE
[PM-1991] pegasus-aws-batch fails while interacting with a bucket in us-east-1

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#2087]
this seems to be similar to #2084 , and also if affecting the Java planner code when trying to run aws batch jobs in us-east-1

**Reporter:** @vahi
**Resolution:** Fixed
**Watchers:**
@mayani
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

the error encountered in job log file only when running in us-east-1 is 

```java

2024-10-29 16:45:45.838 WARN  [S3SignerProvider] Failed to parse the endpoint https://titan2d-blm-emulator-useast1vahi2-user.s3.amazonaws.com, and skip r
e-assigning the signer region
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1931) ~[?:1.8.0_432]
	at software.amazon.awssdk.util.AwsHostNameUtils.parseStandardRegionName(AwsHostNameUtils.java:157) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.util.AwsHostNameUtils.parseRegion(AwsHostNameUtils.java:82) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.util.AwsHostNameUtils.parseRegionName(AwsHostNameUtils.java:57) ~[core-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.services.s3.auth.S3SignerProvider.getSigner(S3SignerProvider.java:47) [s3-2.0.0-preview-2.jar:?]
	at software.amazon.awssdk.http.pipeline.stages.SigningStage.newSigner(SigningStage.java:75) [core-2.0.0-preview-2.jar:?]
 
```

the root cause seems to be raised here

https://github.com/aws/aws-sdk-java-v2/issues/81

some potential workaround to explore

[https://stackoverflow.com/questions/68005239/how-do-you-configure-the-endpoint-for-amazon-s3-by-using-the-aws-sdk-v2]

**Comment by mayani** [comment]
**Author:** @vahi

another idiosyncrasy of us-east-1 region 

[https://stackoverflow.com/questions/35356838/error-bucketalreadyownedbyyou-your-previous-request-to-create-the-named-buck]

 
 
[http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html]
> BucketAlreadyOwnedByYou
> 
> Your previous request to create the named bucket succeeded and you already own it. You get this error in all AWS regions except US East (N. Virginia) region, us-east-1. In us-east-1 region, you will get 200 OK, but it is no-op (if bucket exists it Amazon S3 will not do anything).
Because of this error not being thrown for us-east-1 pegasus-aws-batch things the bucket is job specific and deletes while the job is finished. however this causes the workflow to fail, as same bucket is used for all jobs in the workflow. 

as a fix, when us-east-1 is used, in the our code we have to disable deletion of the buckets

**Comment by mayani** [comment]
**Author:** @vahi

tested on renette's setup
