### ISSUE TITLE
[PM-144] NPE when using label-based clustering on bag-of-tasks (null mLogger in org.griphyn.cPlanner.cluster.Abstract)

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#264]
When I do label-based clustering on a bag-of-tasks workflow I get this exception:

2010.07.02 08:42:33.773 PDT: [INFO]  Starting Graph Traversal - DONE 
2010.07.02 08:42:33.773 PDT: [DEBUG]  Partition is [ID0000078, ID0000079, ID0000076, ID0000077, ID0000074, ID0000075, ID0000072, ID0000073, ID0000071, ID0000070, ID0000087, ID0000088, ID0000089, ID0000083, ID0000084, ID0000085, ID0000086, ID0000001, ID0000002, ID0000009, ID0000080, ID0000007, ID0000082, ID0000008, ID0000081, ID0000005, ID0000006, ID0000003, ID0000004, ID0000096, ID0000097, ID0000094, ID0000095, ID0000098, ID0000099, ID0000010, ID0000011, ID0000012, ID0000013, ID0000014, ID0000015, ID0000016, ID0000017, ID0000018, ID0000093, ID0000019, ID0000092, ID0000091, ID0000090, ID0000020, ID0000023, ID0000024, ID0000021, ID0000022, ID0000027, ID0000028, ID0000025, ID0000026, ID0000029, ID0000039, ID0000038, ID0000037, ID0000036, ID0000035, ID0000034, ID0000033, ID0000032, ID0000031, ID0000030, ID0000048, ID0000047, ID0000049, ID0000044, ID0000043, ID0000046, ID0000045, ID0000040, ID0000042, ID0000041, ID0000100, ID0000059, ID0000058, ID0000053, ID0000052, ID0000051, ID0000050, ID0000057, ID0000056, ID0000055, ID0000054, ID0000069, ID0000062, ID0000061, ID0000064, ID0000063, ID0000066, ID0000065, ID0000068, ID0000067, ID0000060] corresponding to label small_0 
2010.07.02 08:42:33.775 PDT: [FATAL ERROR]  
 [1] java.lang.RuntimeException: null at org.griphyn.cPlanner.engine.MainEngine.runPlanner(MainEngine.java:213)
 [2] java.lang.NullPointerException: null at org.griphyn.cPlanner.cluster.Abstract.determineClusters(Abstract.java:193) 
2010.07.02 08:42:33.775 PDT: [WARNING]  Non-zero exit-code 1 

It looks like the mLogger instance in Abstract.java is null (the call to set it in the constructor is commented out). Horizontal.java seems to have the correct constructor, but Vertical.java does not. I get Vertical when I do label-based clustering.

To fix this in my copy I just replaced the commented line in the Abstract.java constructor with the corresponding line in the Horizontal.java constructor. I had to add an import to Abstract.java for the factory.

**Reporter:** @juve
**Resolution:** Fixed

**Comment by mayani** [comment]
**Author:** @vahi

fixed both in 2.4 and 3.0
for 3.0 i still need to see why horizontal cluster does not extend the abstract cluster.

**Comment by mayani** [comment]
**Author:** @vahi

this is fixed
