### ISSUE TITLE
[PM-201] pegasus-run barfs some python warnings

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#321]
...

ubmitting job(s).
Logging submit event(s).
1 job(s) submitted to cluster 26.
Traceback (most recent call last):
  File "/usr/lib64/python2.4/logging/__init__.py", line 731, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.4/logging/__init__.py", line 617, in format
    return fmt.format(record)
  File "/usr/lib64/python2.4/logging/__init__.py", line 408, in format
    s = self._fmt % record.__dict__
KeyError: 'funcName'

Your Workflow has been started and runs in base directory given below

...

**Reporter:** @voeckler
**Resolution:** Fixed

**Comment by mayani** [comment]
**Author:** @voeckler

Also appears to apply for monitord.log:

Traceback (most recent call last):
  File "/usr/lib64/python2.4/logging/__init__.py", line 731, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.4/logging/__init__.py", line 617, in format
    return fmt.format(record)
  File "/usr/lib64/python2.4/logging/__init__.py", line 408, in format
    s = self._fmt % record.__dict__
KeyError: 'funcName'

**Comment by mayani** [comment]
**Author:** Gaurang Mehta (gmehta)

Its a monitord problem.. Assigning it to fabio. Fabio seems like it barfs on 2.4 python.

**Comment by mayani** [comment]
**Author:** @fabiolsilva

Should be fixed now.

**Comment by mayani** [comment]
**Author:** @fabiolsilva

This Python 2.4 compatibility problem is fixed.
