### ISSUE TITLE
[PM-243] examples/grid-blackdiamond-java fails with mystery npe

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#362]
When trying to submit the examples/grid-blackdiamond-java:

2010.10.29 17:24:56.626 PDT: [DEBUG]  Written Submit file : clean_up_stage_inter_local_dagman_j2_0.sub 
2010.10.29 17:24:56.626 PDT: [DEBUG]  Written Submit file : dagman_j2.sub 
2010.10.29 17:24:56.651 PDT: [DEBUG]  Condor Version as string 7.5.3 
2010.10.29 17:24:56.652 PDT: [DEBUG]  Condor Version detected is 70503 
2010.10.29 17:24:56.654 PDT: [DEBUG]  Arguments passed to SUBDAX Generator are  --site local 
2010.10.29 17:24:56.656 PDT: [FATAL ERROR]  
 [1] java.lang.RuntimeException: Unable to generate code at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:546)
 [2] java.lang.NullPointerException: null at java.io.File.<init>(File.java:222) 

Karan, can you take a look? Thanks!

**Reporter:** @rynge
**Resolution:** Fixed

**Comment by mayani** [comment]
**Author:** @vahi

the source of the error is that right now pegasus for dax job expects the dax file to appear in the uses section
this is a leftover from old dax format . will fix

e.g. 
this works


<dax id="ID000002" file="black.dax"  >

    <argument>-Xmx1024 -Xms512 -Dpegasus.dir.storage=duncan
    -Dpegasus.dir.exec=test -o local --dir ./dag_1   -vvvvv --force -s dax_site --basename base-dir-1</argument>
    
  </dax>

this fails
<dax id="ID000002" file="black.dax"  >

    <argument>-Xmx1024 -Xms512 -Dpegasus.dir.storage=duncan
    -Dpegasus.dir.exec=test -o local --dir ./dag_1   -vvvvv --force -s dax_site --basename base-dir-1</argument>
    
  </dax>

**Comment by mayani** [comment]
**Author:** @vahi

Please test and close

**Comment by mayani** [comment]
**Author:** @rynge

Works with correct "uses"
