### ISSUE TITLE
[PM-293] pegasus-tc-client does not work with the Text Mode backend

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#412]
[pegasus@pegasus pegasus-wms]$ pegasus-tc-client -Dpegasus.user.properties=config/properties -q -P -l diamond::analyze:2.0
Exception in thread "main" java.lang.ClassCastException: edu.isi.pegasus.planner.catalog.transformation.TransformationCatalogEntry cannot be cast to [Ljava.lang.String;
        at edu.isi.pegasus.planner.catalog.transformation.client.TCQuery.getPfn(TCQuery.java:170)
        at edu.isi.pegasus.planner.catalog.transformation.client.TCQuery.doQuery(TCQuery.java:70)
        at edu.isi.pegasus.planner.client.TCClient.executeCommand(TCClient.java:278)
        at edu.isi.pegasus.planner.client.TCClient.main(TCClient.java:413)

**Reporter:** @vahi
**Resolution:** Fixed

**Comment by mayani** [comment]
**Author:** Gaurang Mehta (gmehta)

Fix in Trunk..

**Comment by mayani** [comment]
**Author:** Gaurang Mehta (gmehta)

Fix in trunk. Tested with File and Text. Assigning to Prasanth for testing DB

**Comment by mayani** [comment]
**Author:** Gaurang Mehta (gmehta)

Prasanth can you please test the query displayed above using the DB implementation of TC. I have tested with File and Text

**Comment by mayani** [comment]
**Author:** Gaurang Mehta (gmehta)

Tested Database also. Fixed pretty printing. Closing issue.

**Comment by mayani** [comment]
**Author:** @vahi

Prasanth please close after you have tested the fix against the DB backend
