### ISSUE TITLE
[PM-297] pegasus plan fails when SRM setup is enabled.

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#416]
Britta reported

home/ligo/S6-TESTS/LIGO_CIT-3.0-test/submit-dir/H1L1-s6_lowmass_ihope-949449543-86400.XEUWbX
/subdax_inspiral_hipe_playground.PLAYGROUND_ID000002.pre.log.002

amongst[(gsiftp://osg-ce.ligo.caltech.edu/home/ligo/ligo-ihope/H1L1-s6_lowmass_ihope-949449543-86400.XEUWbX/./datafind/L-L1_LDAS_C02_L2-949497600-128.gwf,{pool=LIGO_CIT})]
2010.12.01 13:12:14.306 PST: [FATAL ERROR]  java.lang.StringIndexOutOfBoundsException: String index out of range: -1
     at java.lang.String.substring(String.java:1937)
     at edu.isi.pegasus.planner.refiner.TransferEngine.getFilesFromRC(TransferEngine.java:1135)
     at edu.isi.pegasus.planner.refiner.TransferEngine.processParents(TransferEngine.java:590)
     at edu.isi.pegasus.planner.refiner.TransferEngine.addTransferNodes(TransferEngine.java:392)
     at edu.isi.pegasus.planner.refiner.MainEngine.runPlanner(MainEngine.java:224)
     at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:499)
     at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:277)
     at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:222)

She was trying to plan the workflow for site LIGO_CIT

and had this specified

pegasus.transfer.srm.LIGO_CIT.service.url=srm\://osg-se.ligo.caltech.edu\:10443/srm/v2/server?SFN\=/mnt/hadoop
pegasus.transfer.srm.LIGO_CIT.service.mountpoint=/mnt/hadoop

**Reporter:** @vahi
**Resolution:** Fixed
**Watchers:**
@bdaudert
@rynge
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

The code was not handling correctly, if the URL did not start with the URL prefix specified in the proeprties.

In this case , the URL gsiftp://osg-ce.ligo.caltech.edu/home/ligo/ligo-ihope/H1L1-s6_lowmass_ihope-949449543-86400.XEUWbX/./datafind/L-L1_LDAS_C02_L2-949497600-128.gwf did not start with
srm\://osg-se.ligo.caltech.edu\:10443/srm/v2/server?SFN\=/mnt/hadoop

**Comment by mayani** [comment]
**Author:** @vahi

checked in the bug fix.

**Comment by mayani** [comment]
**Author:** @vahi

also with 3.0 we have an additional debug level called trace

pegasus will log a message to trace level if it substitutes any srm url;s

example

2010.12.01 16:46:03.191 PST: [TRACE]  Replaced pfn srm://osg-se.ligo.caltech.edu:10443/srm/v2/server?SFN/mnt/hadoop/blah/test.f.a with file:///mnt/hadoop/karantest/blah/test/f.a
