### ISSUE TITLE
[PM-323] pegasus dagman wrapper around condor dagman

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#442]
In order to manage monitord via condor, we want a pegasus dagman wrapper script that pegasus-run refers to

This script will launch monitord and submit the dag.

https://confluence.pegasus.isi.edu/display/pegasus/Monitord+Management+via+Condor#MonitordManagementviaCondor-Wrapperaroundcondordagman

The condor submit file for the dagman job will refer to the executable as pegasus_dagman instead of condor dagman.
The pegasus_dagman script will launch monitord and condor dagman.

**Reporter:** @vahi
**Resolution:** Fixed
**Watchers:**
@fabiolsilva
@rynge
@vahi
@voeckler

**Comment by mayani** [comment]
**Author:** @vahi

With the latest checkout, pegasus-status goes awry a bit

Here is a workflow with pegasus 3.1.0cvs
vahi@obelix:/data/scratch/vahi/examples/condor-blackdiamond$ pegasus-status /data/scratch/vahi/examples/condor-blackdiamond/work/vahi/pegasus/blackdiamond/20110421T160550-0700# Running /opt/condor/default/bin/condor_q -dag -constraint (pegasus_wf_name=="blackdiamond-0")&&(pegasus_wf_time=="20110421T160550-0700") vahi 


-- Submitter: obelix.isi.edu : <128.9.136.58:44672> : obelix.isi.edu
 ID      OWNER/NODENAME   SUBMITTED     RUN_TIME ST PRI SIZE CMD               
22528.0    |-stage_in_re  4/21 16:06   0+00:00:09 H  700 0.2  kickstart -n pegas

We are missing the dag job in the queue.

For a workflow with 3.0.3cvs we do see the dag job too
pegasus-status /data/scratch/vahi/examples/condor-blackdiamond/work/vahi/pegasus/blackdiamond/20110421T163713-0700
# Running /opt/condor/default/bin/condor_q -dag -constraint (pegasus_wf_name=="blackdiamond-0")&&(pegasus_wf_time=="20110421T163713-0700") vahi 

-- Submitter: obelix.isi.edu : <128.9.136.58:44672> : obelix.isi.edu
 ID      OWNER/NODENAME   SUBMITTED     RUN_TIME ST PRI SIZE CMD               
22529.0   vahi            4/21 16:37   0+00:06:50 R  0   17.1 condor_dagman -f -
22531.0    |-stage_in_re  4/21 16:37   0+00:00:02 H  700 0.2  kickstart -n pegas

The reason being, that for 3.0.3cvs dag job we have the extra pegasus classads
vahi@obelix:/data/scratch/vahi/examples/condor-blackdiamond$ condor_q -long 22529.0 | grep pegasus_wf
pegasus_wf_time = "20110421T163713-0700"
pegasus_wf_name = "blackdiamond-0"

For the 3.1.0cvs no such classads are inserted by pegasus_dagman from the braindump file

vahi@obelix:/data/scratch/vahi/examples/condor-blackdiamond$ condor_q -long 22526.0 | grep pegasus_
returns empty

**Comment by mayani** [comment]
**Author:** @vahi

Also pegasus-status -l now always reports that workflow has failed even though workflow maybe running without any errors.

This maybe related to previous comment

**Comment by mayani** [comment]
**Author:** @vahi

pegasus-remove does not work any longer too as the dagid is not in the condor log line
vahi@obelix:/data/scratch/vahi/examples/condor-blackdiamond$ pegasus-remove /data/scratch/vahi/examples/condor-blackdiamond/work/vahi/pegasus/blackdiamond/20110421T160550-0700/
ERROR: Error: You need to provide either a dagid or dagdirectory to remove the workflow

Usage: pegasus-remove -d <dagid> | dagdir
 Pegasus_remove helps remove your your entire workflow.. 
 -d|--dagid N    The id of the dag to be removed
 -v|--verbose   Enter verbose mode, default is not
 -V|--version   Print version number and exit.
 dagdir         The directory for the dag that you want removed
vahi@obelix:/data/scratch/vahi/examples/condor-blackdiamond$ 

It is unable to determine the dagman id

3.1.0cvs dagman.out file
 more /data/scratch/vahi/examples/condor-blackdiamond/work/vahi/pegasus/blackdiamond/20110421T160550-0700/*dagman.out
04/21/11 16:05:51 ******************************************************
04/21/11 16:05:51 ** condor_dagman (CONDOR_DAGMAN) STARTING UP
04/21/11 16:05:51 ** /opt/condor/7.5.3/bin/condor_dagman


3.0.3cvs dagman.out file
more  /data/scratch/vahi/examples/condor-blackdiamond/work/vahi/pegasus/blackdiamond/20110421T163713-0700/*dagman.out
4/21/11 16:37:14 ** condor_scheduniv_exec.22529.0 (CONDOR_DAGMAN) STARTING UP

**Comment by mayani** [comment]
**Author:** @vahi

With the latest check out the pegasus-status problem also went away


vahi@obelix:/data/scratch/vahi/examples/grid-montage$ pegasus-status -l /data/scratch/vahi/examples/grid-montage/work/2011-04-22_134252/work/vahi/pegasus/montage/20110422T134326-0700
montage-0.dag is running.
04/22/11 13:44:37  Done     Pre   Queued    Post   Ready   Un-Ready   Failed
04/22/11 13:44:37   ===     ===      ===     ===     ===        ===      ===
04/22/11 13:44:37     5       0        8       1       0         43        0

WORKFLOW STATUS : RUNNING | 5/57 ( 9% ) | (condor processing workflow)
vahi@obelix:/data/scratch/vahi/examples/grid-montage$ pwd
/data/scratch/vahi/examples/grid-montage
vahi@obelix:/data/scratch/vahi/examples/grid-montage$ pwd
/data/scratch/vahi/examples/grid-montage
vahi@obelix:/data/scratch/vahi/examples/grid-montage$ pegasus-status -l /data/scratch/vahi/examples/grid-montage/work/2011-04-22_134252/work/vahi/pegasus/montage/20110422T134326-0700
montage-0.dag succeeded
04/22/11 13:48:37  Done     Pre   Queued    Post   Ready   Un-Ready   Failed
04/22/11 13:48:37   ===     ===      ===     ===     ===        ===      ===
04/22/11 13:48:37    57       0        0       0       0          0        0

WORKFLOW STATUS : COMPLETED | 57/57 ( 100% ) | (all jobs finished successfully)

Gaurang refer to JIRA item when doing a commit.

**Comment by mayani** [comment]
**Author:** Prasanth Thomas (prasanth)

While trying to run the blackdiamond example in the trunk . I am getting the following error.

diamond-0.dag.lib.err
::::::::::::::
Traceback (most recent call last):
  File "/lfs1/prasanth/grid-setup/pegasus/3.1.0/bin/pegasus-dagman", line 35, in <module>
    from Pegasus.tools.utils import find_exec
  File "/lfs1/prasanth/grid-setup/pegasus/3.1.0/lib/python/Pegasus/tools/utils.py", line 40, in <module>
    for i, c in zip(xrange(256), str(bytearray(xrange(256)))):
NameError: name 'bytearray' is not defined

Also in this case pegasus status incorrectly states workflow has  finished

-- Submitter: butterfly.isi.edu : <128.9.128.226:35336> : butterfly.isi.edu
 ID      OWNER/NODENAME   SUBMITTED     RUN_TIME ST PRI SIZE CMD               
butterfly 49% pegasus-status -l .
WORKFLOW STATUS : COMPLETED | 0/0 ( 0% ) | (all jobs finished successfully)

python version is Python 2.5.1 (r251:54863, Jun 15 2008, 18:24:56)

**Comment by mayani** [comment]
**Author:** Gaurang Mehta (gmehta)

Works reasonable well and tested
