### ISSUE TITLE
[PM-438] Missing javascript dir in distribution

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#556]
$ pegasus-plots `pwd`
2011-07-13 14:51:47,628:pegasus-plots:main:383: INFO: pegasus-plots : initializing...
2011-07-13 14:51:47,653:properties.py:new:240: INFO: processing properties file /home/rynge/src/pegasus/pegasus/examples/grid-blackdiamond-python/work/rynge/pegasus/diamond/20110713T143608-0700/pegasus.7039007294681927489.properties... 
2011-07-13 14:51:47,713:utils.py:create_directory:115: INFO: Creating directory... /tmp/tmp9idV2Y/gantt_chart
2011-07-13 14:51:47,713:utils.py:create_directory:115: INFO: Creating directory... /tmp/tmp9idV2Y/gantt_chart/js
2011-07-13 14:51:47,713:utils.py:create_directory:115: INFO: Creating directory... /tmp/tmp9idV2Y/gantt_chart/images/
Traceback (most recent call last):
  File "/home/rynge/Pegasus/install/trunk/bin/pegasus-plots", line 418, in <module>
    main()
  File "/home/rynge/Pegasus/install/trunk/bin/pegasus-plots", line 411, in main
    create_charts(submit_dir, output_dir,options.config_properties, options.log_level)
  File "/home/rynge/Pegasus/install/trunk/bin/pegasus-plots", line 283, in create_charts
    pegasus_gantt.setup(submit_dir,gantt_chart_output_dir ,log_level)
  File "/home/rynge/Pegasus/install/trunk/lib/python/Pegasus/plots_stats/plots/pegasus_gantt.py", line 951, in setup
    plot_utils.copy_files(src_js_path , dest_js_path)
  File "/home/rynge/Pegasus/install/trunk/lib/python/Pegasus/plots_stats/utils.py", line 123, in copy_files
    for file in os.listdir(src):
OSError: [Errno 2] No such file or directory: '/home/rynge/Pegasus/install/trunk/lib/javascript'

**Reporter:** @rynge
**Resolution:** Fixed

**Comment by mayani** [comment]
**Author:** Prasanth Thomas (prasanth)

Changed the build to copy the javascript library and share for generating of the distribution
