### ISSUE TITLE
[PM-534] pegasus-plots does not plot

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#652]
I am working through the tutorial-vm and attempting to run a pegasus-plots on a black diamond on a CentOS 5.7. Neither python 2.4 nor 2.6 are working: 

pegasus-wms $ python26 /opt/pegasus/default/bin/pegasus-plots -p all dags/tutorial/pegasus/blackdiamond/run0001
2011-12-12 15:08:02,414:utils.py:create_directory:123: WARNING: Deleting existing directory. Deleting... /home/tutorial/pegasus-wms/dags/tutorial/pegasus/blackdiamond/run0001/plots
2011-12-12 15:08:02,554:pegasus-plots:main:598: WARNING: Traceback (most recent call last):
  File "/opt/pegasus/default/bin/pegasus-plots", line 596, in main
    create_charts(submit_dir, output_dir,options.config_properties, log_level_str)
  File "/opt/pegasus/default/bin/pegasus-plots", line 426, in create_charts
    populate.populate_job_instance_details(wf_stats, wf_info)
  File "/opt/pegasus/default/lib/python/Pegasus/plots_stats/plots/populate.py", line 251, in populate_job_instance_details
    job_states_list =  workflow_stats.get_job_states()
  File "/opt/pegasus/default/lib/python/netlogger/analysis/workflow/stampede_statistics.py", line 778, in get_job_states
    return q.all()
  File "/opt/pegasus/default/lib/python/sqlalchemy/orm/query.py", line 1492, in all
    return list(self)
  File "/opt/pegasus/default/lib/python/sqlalchemy/orm/query.py", line 1604, in __iter__
    return self._execute_and_instances(context)
  File "/opt/pegasus/default/lib/python/sqlalchemy/orm/query.py", line 1609, in _execute_and_instances
    mapper=self._mapper_zero_or_none())
  File "/opt/pegasus/default/lib/python/sqlalchemy/orm/session.py", line 701, in execute
    clause, params or {})
  File "/opt/pegasus/default/lib/python/sqlalchemy/engine/base.py", line 1194, in execute
    params)
  File "/opt/pegasus/default/lib/python/sqlalchemy/engine/base.py", line 1274, in _execute_clauseelement
    return self.__execute_context(context)
  File "/opt/pegasus/default/lib/python/sqlalchemy/engine/base.py", line 1305, in __execute_context
    context.parameters[0], context=context)
  File "/opt/pegasus/default/lib/python/sqlalchemy/engine/base.py", line 1404, in _cursor_execute
    context)
  File "/opt/pegasus/default/lib/python/sqlalchemy/engine/base.py", line 1397, in _cursor_execute
    context)
  File "/opt/pegasus/default/lib/python/sqlalchemy/engine/default.py", line 299, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such function: group_concat u'SELECT job.job_id AS job_job_id, job_instance.job_instance_id AS job_instance_job_instance_id, job_instance.job_submit_seq AS job_instance_job_submit_seq, job.exec_job_id AS job_name, job_instance.site AS job_instance_site, (SELECT host.hostname \nFROM host \nWHERE host.host_id = job_instance.host_id) AS host_name, CAST((SELECT min(jobstate.timestamp) AS min_1 \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id) AS FLOAT) AS "jobS", CAST((SELECT max(jobstate.timestamp) - min(jobstate.timestamp) AS anon_1 \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id) AS FLOAT) AS "jobDuration", CAST((SELECT jobstate.timestamp \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id AND jobstate.state IN (?)) AS FLOAT) AS pre_start, CAST((SELECT jobstate.timestamp \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id AND jobstate.state IN (?)) - (SELECT jobstate.timestamp \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id AND jobstate.state IN (?)) AS FLOAT) AS pre_duration, CAST((SELECT jobstate.timestamp \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id AND jobstate.state IN (?)) AS FLOAT) AS condor_start, CAST((SELECT jobstate.timestamp \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id AND jobstate.state IN (?)) - (SELECT jobstate.timestamp \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id AND jobstate.state IN (?)) AS FLOAT) AS condor_duration, CAST((SELECT jobstate.timestamp \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id AND jobstate.state IN (?, ?)) AS FLOAT) AS grid_start, CAST((SELECT min(jobstate.timestamp) AS min_2 \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id AND jobstate.state IN (?)) - (SELECT jobstate.timestamp \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id AND jobstate.state IN (?, ?)) AS FLOAT) AS grid_duration, CAST((SELECT max(jobstate.timestamp) AS max_1 \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id AND jobstate.state IN (?, ?)) AS FLOAT) AS exec_start, CAST((SELECT jobstate.timestamp \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id AND jobstate.state IN (?)) - (SELECT max(jobstate.timestamp) AS max_1 \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id AND jobstate.state IN (?, ?)) AS FLOAT) AS exec_duration, CAST((SELECT min(invocation.start_time) AS min_3 \nFROM invocation \nWHERE invocation.job_instance_id = job_instance.job_instance_id AND invocation.wf_id = job.wf_id AND invocation.task_submit_seq >= ? GROUP BY invocation.job_instance_id) AS FLOAT) AS kickstart_start, CAST((SELECT sum(invocation.remote_duration) AS sum_1 \nFROM invocation \nWHERE invocation.job_instance_id = job_instance.job_instance_id AND invocation.wf_id = job.wf_id AND invocation.task_submit_seq >= ? GROUP BY invocation.job_instance_id) AS FLOAT) AS kickstart_duration, CAST((SELECT max(jobstate.timestamp) AS max_2 \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id AND jobstate.state IN (?, ?)) AS FLOAT) AS post_start, CAST((SELECT jobstate.timestamp \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id AND jobstate.state IN (?)) - (SELECT max(jobstate.timestamp) AS max_2 \nFROM jobstate \nWHERE jobstate.job_instance_id = job_instance.job_instance_id AND jobstate.state IN (?, ?)) AS FLOAT) AS post_duration, (SELECT group_concat(distinct(invocation.transformation)) AS group_concat_1 \nFROM invocation \nWHERE invocation.wf_id IN (?) AND invocation.job_instance_id = job_instance.job_instance_id AND invocation.transformation != ? AND invocation.transformation != ?) AS transformation \nFROM job, job_instance \nWHERE job_instance.job_id = job.job_id AND job.wf_id IN (?) ORDER BY job_instance.job_submit_seq' ('PRE_SCRIPT_STARTED', 'PRE_SCRIPT_TERMINATED', 'PRE_SCRIPT_STARTED', 'SUBMIT', 'JOB_TERMINATED', 'SUBMIT', 'GRID_SUBMIT', 'GLOBUS_SUBMIT', 'EXECUTE', 'GRID_SUBMIT', 'GLOBUS_SUBMIT', 'EXECUTE', 'SUBMIT', 'JOB_TERMINATED', 'EXECUTE', 'SUBMIT', 0, 0, 'POST_SCRIPT_STARTED', 'JOB_TERMINATED', 'POST_SCRIPT_TERMINATED', 'POST_SCRIPT_STARTED', 'JOB_TERMINATED', 1, 'dagman::post', 'dagman::pre', 1)

**Reporter:** @voeckler
**Resolution:** Fixed
**Watchers:**
@fabiolsilva
@montegoode
@vahi
**Attachments:**

**Comment by mayani** [comment]
**Author:** @fabiolsilva

Compiling SQLAlchemy in Python 2.4 and running in Python 2.6 doesn't work. Jens, could you please post the error that shows up when you run this with Python 2.4? Let's see if we can fix that one.

**Comment by mayani** [comment]
**Author:** @voeckler

You are not escaping that easily ;-)

pegasus-wms $ pegasus-plots -p all /home/tutorial/pegasus-wms/dags/tutorial/pegasus/blackdiamond/run0001
2011-12-12 20:50:48,523:pegasus-plots:598: WARNING: Traceback (most recent call last):
  File "/opt/pegasus/3.1/bin/pegasus-plots", line 596, in main
    create_charts(submit_dir, output_dir,options.config_properties, log_level_str)
  File "/opt/pegasus/3.1/bin/pegasus-plots", line 417, in create_charts
    setup(dag_graph_output_dir)
  File "/opt/pegasus/3.1/bin/pegasus-plots", line 76, in setup
    shutil.copytree (src_img_path, dest_img_path)
  File "/usr/lib64/python2.4/shutil.py", line 111, in copytree
    os.mkdir(dst)
OSError: [Errno 2] No such file or directory: '/home/tutorial/pegasus-wms/dags/tutorial/pegasus/blackdiamond/run0001/plots/dag_graph/images/'

**Comment by mayani** [comment]
**Author:** @voeckler

all the files, workdir, etc.

**Comment by mayani** [comment]
**Author:** @voeckler

And I am also unable to compile branch 3.1 on the machine from source using python 2.4:

$ ant dist
...
     [exec] building 'pysqlite2._sqlite' extension
     [exec] creating build/temp.linux-x86_64-2.4
     [exec] creating build/temp.linux-x86_64-2.4/src
     [exec] creating build/temp.linux-x86_64-2.4/amalgamation
     [exec] gcc -pthread -fno-strict-aliasing -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fPIC -DMODULE_NAME="pysqlite2.dbapi2" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_OMIT_LOAD_EXTENSION=1 -Iamalgamation -I/usr/include/python2.4 -c src/module.c -o build/temp.linux-x86_64-2.4/src/module.o
     [exec] In file included from src/module.c:24:
     [exec] src/connection.h:26:20: error: Python.h: No such file or directory
     [exec] src/connection.h:27:22: error: pythread.h: No such file or directory
     [exec] src/connection.h:28:26: error: structmember.h: No such file or directory
     [exec] In file included from src/connection.h:30,
     [exec]                  from src/module.c:24:
     [exec] src/cache.h:34: error: expected specifier-qualifier-list before

**Comment by mayani** [comment]
**Author:** @voeckler

However, I *was* able to compile branch 3.1 with some evil trickery THAT WILL NOT DO: 

$ mkdir ~/bin
$ ln -s /usr/bin/python26 ~/bin/python
$ export PATH=$HOME/bin:$PATH
$ ant clean dist
...

In other words, that evil trickery is not acceptable as solution to close this bug.  Unless the RPM is made to depend on python26, and installs all Pegasus python code to point to "#!/usr/bin/env python26".

**Comment by mayani** [comment]
**Author:** @voeckler

Installing python-devel.x86_64 helps with the middle part where I compile Pegasus 3.1 from branch src on the target platform. 

However, pegasus-plots still bombs, with the same as the original message. (It does work when doing the 2.6 hack.)

**Comment by mayani** [comment]
**Author:** @vahi

fabio fixed this on 13/Dec/11 5:47 PM
