### ISSUE TITLE
[PM-570] Updating stampede.db fails on RHEL5/32bit system

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#688]
I am trying to follow the instructions on http://pegasus.isi.edu/wms/docs/4.0/useful_tips.php#id644312

However, regardless of which python I am using it. I get a blurb of errors (of course, synthale.isi.edu is a CentOS 5.4 32 bit system that hasn't been upgraded in years, and nobody wants to do that): 

python26 /opt/pegasus/default/share/pegasus/sql/schema_tool.py -c connString=sqlite:/home/voeckler/page/upload/submit/voeckler/pegasus/page-clean/run0004/page-clean-0.stampede.db                                                                 
Traceback (most recent call last):                                              
  File "/opt/pegasus/default/share/pegasus/sql/schema_tool.py", line 75, in <module>                                                                            
    main()                                                                      
  File "/opt/pegasus/default/share/pegasus/sql/schema_tool.py", line 63, in main
    conn = ConnHandle(**init)
  File "/opt/pegasus/pegasus-4.0.0/lib/pegasus/python/netlogger/analysis/schema/schema_check.py", line 36, in __init__
    SQLAlchemyInit.__init__(self, connString, initializeToPegasusDB, **_kw)
  File "/opt/pegasus/pegasus-4.0.0/lib/pegasus/python/netlogger/analysis/modules/_base.py", line 126, in __init__
    self.db = create_engine(connString, echo=self._dbg, pool_recycle=True)
  File "/opt/pegasus/pegasus-4.0.0/lib/pegasus/externals/python/sqlalchemy/engine/__init__.py", line 244, in create_engine
    return strategy.create(*args, **kwargs)
  File "/opt/pegasus/pegasus-4.0.0/lib/pegasus/externals/python/sqlalchemy/engine/strategies.py", line 44, in create
    u = url.make_url(name_or_url)
  File "/opt/pegasus/pegasus-4.0.0/lib/pegasus/externals/python/sqlalchemy/engine/url.py", line 164, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/opt/pegasus/pegasus-4.0.0/lib/pegasus/externals/python/sqlalchemy/engine/url.py", line 205, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name)
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'sqlite:/home/voeckler/page/upload/submit/voeckler/pegasus/page-clean/run0004/page-clean-0.stampede.db'

I'll downgrade to Pegasus 3.1 for now...

**Reporter:** @voeckler
**Resolution:** Won't Fix

**Comment by mayani** [comment]
**Author:** @vahi

gaurang can you take a look?

I think it might have to do with the number of / that Jens used

Jens, with sqllite backed and for running new workflows, you can don't need to upgrade your database

**Comment by mayani** [comment]
**Author:** @voeckler

No, pegasus-plots (4.0) specifically told me to run the upgrade tool on my (3.1) workflow database. It didn't say what I needed to run, which means I looked up the link above, and followed those instructions. 

Damn, sorry, bash-tab-completion deleted my slashes!!!
