### ISSUE TITLE
[PM-581] Pegasus does not pick up profiles specified as property on the command line

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#699]
Gideon noticed the following,

Any profile specified on the command line example other than the pegasus namespace is not used by the planner.

For example the planner does not associate a profile with the job if specified as follows

pegasus-plan -Devn.SSH_KEY=/path/to/key  <args>

However if the same property is specified in the properties file, then it is picked up.

**Reporter:** @vahi
**Resolution:** Fixed
**Watchers:**
@juve
@vahi
@voeckler

**Comment by mayani** [comment]
**Author:** @vahi

This has got to do with how the matchingSubset function is implemented in the CommonProperties.java. It is called by the planner to retrieve the properties matching on the profile namespace values.

The function does not look at System properties while determining the set of keys specified.
However, while returning a value for a property it does prefer a property specified at the System level.

One fix will be to enumerate through both the internal properties object and the system properties object.

**Comment by mayani** [comment]
**Author:** @vahi

checked in the fix.

**Comment by mayani** [comment]
**Author:** @vahi

please try now.

**Comment by mayani** [comment]
**Author:** @juve

This still doesn't work for me. If I run:

pegasus-plan -Denv.SSH_PRIVATE_KEY=/Users/juve/.ssh/bband_dsa -Dpegasus.catalog.site.file=etc/sites.xml -Dpegasus.catalog.replica.file=/var/bbportal/submit/asdfasdfasdfa/rc.dat -Dpegasus.catalog.transformation.file=etc/tc.dat -Dpegasus.dir.storage=/var/bbportal/submit/asdfasdfasdfa/outputs -Dpegasus.dir.exec=bdd184a9-eed8-47f1-9f3c-ee1fab0b7d7f --conf etc/properties --dax /var/bbportal/submit/asdfasdfasdfa/broadband.dax --dir /var/bbportal/submit/asdfasdfasdfa/dags --nocleanup --force -s cloud -o local --submit

Then I still get:

2012.04.27 18:46:52.621 PDT: [FATAL ERROR]  
 [1] java.lang.RuntimeException: Unable to generate code at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:627)
 [2] edu.isi.pegasus.planner.code.generator.condor.CondorStyleException: Unable to find required credential for file transfers. Please make sure SSH_PRIVATE_KEY is set either in the site catalog or your environment. at edu.isi.pegasus.planner.code.generator.condor.style.Abstract.applyCredentialsForRemoteExec(Abstract.java:173) 
2012.04.27 18:46:52.621 PDT: [WARNING]  Non-zero exit-code 1

I also tried with -Dpegasus.env.SSH_PRIVATE_KEY and got the same result.

**Comment by mayani** [comment]
**Author:** @vahi

Currently, the credential interface in the planner does not support keys specified in profiles in places other than site catalog or properties 

Gideon we implemented credential handling to pick up only from the local site catalog entry or from the environment. If we need to extend it to also pick up from the properties, it should be straightforward.. To be able to specify it in profiles say in DAX, then we need to change our interfaces for the module.

Looking at the code , specifying the variable SSH_PRIVATE_KEY in the environment should work.

**Comment by mayani** [comment]
**Author:** @vahi

there is an unresovled part here that we will do for 4.2
