### ISSUE TITLE
[PM-618] planner hits NPE when doing staging of executables in PegasusLite mode with hints specified in the DAX for the execution site

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#736]
Pegasus hits into NPE when planning a workflow with Pegasus Lite turned on , and the DAX having an executionPool specified as a hints profile.

pegasus-plan --conf ./conf/properties --dax orca.dax -s condorpool --staging-site local -o local --dir dags -vvv
...

2.06.15 14:25:40.112 PDT: [TRACE]  For job orca_create_ID0000001 updating profiles from site local 
2012.06.15 14:25:40.112 PDT: [DEBUG]  Trying to get TCEntries for orca::orca_create:0.1 on resource ALL of type ALL 
2012.06.15 14:25:40.112 PDT: [DEBUG]  Random TC Record selected is 2 amongst 2 possible 
2012.06.15 14:25:40.112 PDT: [DEBUG]  Mapping Job orca_delete_ID0000002 
2012.06.15 14:25:40.112 PDT: [TRACE]  For job orca_delete_ID0000002 updating profiles from site local 
2012.06.15 14:25:40.113 PDT: [DEBUG]  Trying to get TCEntries for orca::orca_delete:0.1 on resource ALL of type ALL 
2012.06.15 14:25:40.113 PDT: [DEBUG]  Random TC Record selected is 1 amongst 2 possible 
2012.06.15 14:25:40.114 PDT: [FATAL ERROR]  java.lang.RuntimeException: Entry for null does not exist in the Site Catalog
2012.06.15 14:25:40.114 PDT: [INFO] event.pegasus.siteselection dax.id orca_0  - FINISHED 
        at edu.isi.pegasus.planner.catalog.site.classes.SiteStore.getInternalWorkDirectory(SiteStore.java:588)
        at edu.isi.pegasus.planner.catalog.site.classes.SiteStore.getInternalWorkDirectory(SiteStore.java:526)
        at edu.isi.pegasus.planner.refiner.InterPoolEngine.incorporateProfiles(InterPoolEngine.java:514)
        at edu.isi.pegasus.planner.refiner.InterPoolEngine.scheduleJobs(InterPoolEngine.java:309)
        at edu.isi.pegasus.planner.refiner.InterPoolEngine.determineSites(InterPoolEngine.java:241)
        at edu.isi.pegasus.planner.refiner.MainEngine.runPlanner(MainEngine.java:199)
        at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:561)
        at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:307)

**Reporter:** @vahi
**Resolution:** Fixed
**Watchers:**
@rynge
**Attachments:**

**Comment by mayani** [comment]
**Author:** @vahi

the error is hit when a stageable transformation catalog entry is associated with a job and the hint profile is picked up from the DAX For the job.

In that case, the planner needs to transfer the executable from the staging site to the place where the job runs.

In this particular case, when planner tries to figure out the transfer, the staging site is unset. Hence the NPE

**Comment by mayani** [comment]
**Author:** @vahi

checked in fix both to 4.0 branch and trunk
