### ISSUE TITLE
[PM-637] pegasus-analyzer fails with AttributeError: 'module' object has no attribute 'uses_query'

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#755]
pegasus-analyzer fails in newer versions of python with:

$ pegasus-analyzer --help
Traceback (most recent call last):
  File "/usr/bin/pegasus-analyzer", line 62, in <module>
    from netlogger.analysis.workflow import stampede_statistics
  File "/usr/lib/pegasus/python/netlogger/analysis/workflow/stampede_statistics.py", line 158, in <module>
    from netlogger.analysis.modules._base import SQLAlchemyInit
  File "/usr/lib/pegasus/python/netlogger/analysis/modules/_base.py", line 12, in <module>
    from netlogger.nllog import DoesLogging, TRACE
  File "/usr/lib/pegasus/python/netlogger/nllog.py", line 15, in <module>
    from netlogger import nlapi
  File "/usr/lib/pegasus/python/netlogger/nlapi.py", line 418, in <module>
    urlparse.uses_query.append(scheme)
AttributeError: 'module' object has no attribute 'uses_query' 

The problems seems to be that uses_query was removed in Python 2.7:

http://hg.python.org/cpython/rev/79e6ff3d9afd

This bug was reported via the Debian bug tracking system:

http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=682148

**Reporter:** @rynge
**Resolution:** Fixed
**Watchers:**
@rynge
@rynge

**Comment by mayani** [comment]
**Author:** @rynge

Fix commited
