### ISSUE TITLE
[PM-741] NPE with new leaf cleanup and file:// / pegasus.transfer.*.remote.sites

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#859]
I'm running a workflow with:

pegasus.transfer.*.remote.sites = execution

and the remote execution site has only file:// accessible URLs:

        <directory type="shared-scratch" path="/scratch/00384/rynge/workflow-runs">
            <file-server operation="all" url="file:///scratch/00384/rynge/workflow-runs"/>
        </directory>
        <directory type="local-storage" path="/work/00384/rynge/workflow-outputs">
            <file-server operation="all" url="file:///work/00384/rynge/workflow-outputs"/>
        </directory>

With the new leaf cleanup code, I get:

2014.03.10 11:50:28.570 PDT: [FATAL ERROR]  java.lang.NullPointerException
        at edu.isi.pegasus.planner.refiner.RemoveDirectory.makeRemoveDirJob(RemoveDirectory.java:445)
        at edu.isi.pegasus.planner.refiner.RemoveDirectory.makeRemoveDirJob(RemoveDirectory.java:419)
        at edu.isi.pegasus.planner.refiner.RemoveDirectory.addRemoveDirectoryNodes(RemoveDirectory.java:263)
        at edu.isi.pegasus.planner.refiner.RemoveDirectory.addRemoveDirectoryNodes(RemoveDirectory.java:204)
        at edu.isi.pegasus.planner.refiner.MainEngine.runPlanner(MainEngine.java:276)
        at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:646)
        at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:366)
        at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:254)

**Reporter:** @rynge
**Resolution:** Fixed
**Watchers:**
@rynge
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

is this in sharedfs mode?

**Comment by mayani** [comment]
**Author:** @rynge

Yes

**Comment by mayani** [comment]
**Author:** @vahi

pushed out a fix. please try when you get the chance.

**Comment by mayani** [comment]
**Author:** @rynge

This is working for my usecase now.
