### ISSUE TITLE
[PM-799] Planner is not validating the value for pegasus.data.configuration

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#917]
Hassan had a workflow with:

pegasus.data.configuration = nonsharedfa

And the planner happily accepted that value and threw a NPE in some random place in the code.

**Reporter:** Hassan Nawaz [X] (hassan)
**Resolution:** Fixed
**Watchers:**
@juve

**Comment by mayani** [comment]
**Author:** @juve

This is the stack trace where it failed:

java.lang.NullPointerException
	at edu.isi.pegasus.planner.refiner.createdir.Minimal.addCreateDirectoryNodes(Minimal.java:184)
	at edu.isi.pegasus.planner.refiner.createdir.Minimal.addCreateDirectoryNodes(Minimal.java:90)
	at edu.isi.pegasus.planner.refiner.CreateDirectory.addCreateDirectoryNodes(CreateDirectory.java:170)
	at edu.isi.pegasus.planner.refiner.MainEngine.runPlanner(MainEngine.java:250)
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:631)
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:358)
	at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:239)
