### ISSUE TITLE
[PM-800] No amount of verbose flags results in a full stack trace

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#918]
We were getting an NPE, but adding a bunch of "-v" flags did not show us the stack trace. We had to go get the stack trace from the metrics server. We should show a stack trace for errors if the verbosity is set to DEBUG.

**Reporter:** @juve
**Resolution:** Fixed
**Watchers:**
@juve
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

the planner does this currently

No verbose flag passed

2014.11.26 13:46:01.515 PST: [FATAL ERROR]  
 [1] java.lang.RuntimeException: null at edu.isi.pegasus.planner.refiner.MainEngine.runPlanner(MainEngine.java:208)
 [2]: No matching partitioner found for clustering technique horizontal1 at edu.isi.pegasus.planner.cluster.ClustererFactory.loadPartitioner(ClustererFactory.java:112) 


At the trace level ( with -vvvv)
2014.11.26 13:50:24.240 PST: [FATAL ERROR]  java.lang.RuntimeException
	at edu.isi.pegasus.planner.refiner.MainEngine.runPlanner(MainEngine.java:208)
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:631)
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:358)
	at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:239)
Caused by: edu.isi.pegasus.planner.cluster.ClustererFactoryException: No matching partitioner found for clustering technique horizontal1
	at edu.isi.pegasus.planner.cluster.ClustererFactory.loadPartitioner(ClustererFactory.java:112)
	at edu.isi.pegasus.planner.refiner.NodeCollapser.cluster(NodeCollapser.java:205)
	at edu.isi.pegasus.planner.refiner.NodeCollapser.cluster(NodeCollapser.java:143)
	at edu.isi.pegasus.planner.refiner.MainEngine.runPlanner(MainEngine.java:205)
	... 3 more

**Comment by mayani** [comment]
**Author:** @juve

I think trace is too sensitive. I think one -v should be enough to trigger a stack trace.
