### ISSUE TITLE
[PM-809] Print helpful error message if pegasus.catalog.site.file is not set

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#927]
We had a user request help on the Pegasus mailing list saying that he was getting the following error:

$ pegasus-plan --conf pegasus.conf -d metqc.dax --sites local -vvvv
2014.12.30 13:57:17.896 GMT-05:00: [INFO]  Planner invoked with following arguments --conf pegasus.conf -d metqc.dax --sites local -vvvv
2014.12.30 13:57:17.900 GMT-05:00: [DEBUG]  All sites will be loaded from the site catalog
2014.12.30 13:57:17.908 GMT-05:00: [FATAL ERROR]
 [1]: Unable to instantiate Site Catalog  at edu.isi.pegasus.planner.catalog.site.SiteFactory.loadInstance(SiteFactory.java:227)
 [2]: edu.isi.pegasus.planner.catalog.site.impl.XML caught java.lang.RuntimeException Unable to connect to site catalog implementation at edu.isi.pegasus.planner.catalog.site.SiteFactory.loadInstance(SiteFactory.java:224)
ERROR while logging metrics The metrics file location is not yet initialized
2014.12.30 13:57:17.915 GMT-05:00: [WARNING]  Non-zero exit-code 2
2014.12.30 13:57:17.918 GMT-05:00: [INFO] event.pegasus.planner planner.version 4.4.0  (0.031 seconds) - FINISHED

It turned out that he had a typo in his config file such that pegasus.catalog.site.file was not being set properly. We should have a more helpful error message in that case.

**Reporter:** @juve
**Resolution:** Fixed
**Watchers:**
@juve
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

The exception throw will now mention the property that needs to be set.
2015.01.05 11:07:19.844 PST: [FATAL ERROR]  
 [1]: Unable to instantiate Site Catalog  at edu.isi.pegasus.planner.catalog.site.SiteFactory.loadInstance(SiteFactory.java:227)
 [2]: edu.isi.pegasus.planner.catalog.site.impl.XML caught edu.isi.pegasus.planner.catalog.site.SiteCatalogException Please specify the property pegasus.catalog.site.file in your properties file  at edu.isi.pegasus.planner.catalog.site.impl.XML.connect(XML.java:115)
