### ISSUE TITLE
[PM-815] pegasus.catalog.site = XML4 causes an error

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#933]
I realize this parameter is not required and can be auto detected.  It works if no setting is provided.

2015.01.13 18:16:04.336 EST: [FATAL ERROR]  
 [1]: Unable to instantiate Site Catalog  at edu.isi.pegasus.planner.catalog.site.SiteFactory.loadInstance(SiteFactory.java:227)
 [2]: Unable to dynamically load edu.isi.pegasus.planner.catalog.site.impl.XML4 at java.net.URLClassLoader$1.run(URLClassLoader.java:366) 
2015.01.13 18:16:04.653 EST: [WARNING]  Non-zero exit-code 2

**Reporter:** Steven Clark [X] (clarks)
**Resolution:** Fixed
**Watchers:**
Steven Clark [X] (clarks)
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

Fixed.  We load the right class if XML4 is specified. We had removed the value in 4.3. However, should have put in backward support in the Factory.

However,  do update your configuration to have 

pegasus.catalog.site XML 

or not specify the property.
