### ISSUE TITLE
[PM-824] Unable to find path to pegasus-db-admin

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#942]
When I run pegasus-plan from my dist/pegasus-4.5.0cvs/bin, I get this:

2015.02.06 13:49:40.314 PST: [FATAL ERROR]  java.lang.RuntimeException: Unable to find path to pegasus-db-admin
	at edu.isi.pegasus.planner.client.CPlanner.checkForDatabaseCompatibility(CPlanner.java:1863)
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:678)
	at edu.isi.pegasus.planner.client.CPlanner.executeCommand(CPlanner.java:360)
	at edu.isi.pegasus.planner.client.CPlanner.main(CPlanner.java:241)

When I add dist/pegasus-4.5.0cvs/bin to my PATH it goes away. I think the planner should find this without using PATH.

**Reporter:** @juve
**Resolution:** Fixed
**Watchers:**
@juve
@rafaelfsilva
@vahi

**Comment by mayani** [comment]
**Author:** @vahi

PEGASUS_BIN_DIR  should be used in the discovery mechanism.

**Comment by mayani** [comment]
**Author:** @vahi

PEGASUS_BIN_DIR is looked first now when planner discovers paths to executables.
