### ISSUE TITLE
[PM-845] pegasus-plan addCreateDirectoryNodes error

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#963]
2015.03.10 22:31:20.853 EDT: [WARNING]  --output option is deprecated. Replaced by --output-site  
2015.03.10 22:31:21.420 EDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.10 22:31:21.424 EDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.10 22:31:21.425 EDT: [WARNING]  unknown profile condor.whentotransferoutput,  using anyway 
2015.03.10 22:31:21.857 EDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.10 22:31:21.858 EDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.10 22:31:21.859 EDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.10 22:31:21.860 EDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.10 22:31:21.916 EDT: [FATAL ERROR]  
 [1] java.lang.NullPointerException: null at edu.isi.pegasus.planner.refiner.createdir.Minimal.addCreateDirectoryNodes(Minimal.java:184) 
2015.03.10 22:31:22.101 EDT: [WARNING]  Non-zero exit-code 1

**Reporter:** Steven Clark [X] (clarks)
**Resolution:** Fixed
**Watchers:**
Steven Clark [X] (clarks)
@vahi
**Attachments:**

**Comment by mayani** [comment]
**Author:** @vahi

can you attach dax, properties, catlog files and how the planner was invoked?

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

Here is plan command.  Other files are attached.

pegasus-plan --conf /home/nanohub/clarksm/Submit/RegressionTests/Remote/Sweep/Serial/Unnamed/Arbitrary/Args/Test04/00167084/00167084.pegasusrc \
             --sites DiaGrid,rossmann \
             --dir /pegtmp/1426055457_00167084 \
             --relative-dir scratch \
             --relative-submit-dir work \
             --output local \
             --dax /home/nanohub/clarksm/Submit/RegressionTests/Remote/Sweep/Serial/Unnamed/Arbitrary/Args/Test04/00167084/00167084.dax \
             --submit < /dev/null

I am using 4.5.0 downloaded Mar 10 at 11:33

**Comment by mayani** [comment]
**Author:** @vahi

i think you have the wrong version setup

corbusier:#963 vahi$ pegasus-version -f
4.5.0cvs-x86_64_macos_10-20150311215439Z
corbusier:#963 vahi$ pegasus-plan --conf ./conf/pegasusrc --sites DiaGrid,rossmann --dir ./dags --relative-dir scratch --relative-submit-dir work --output local --dax 00167084.dax 
2015.03.11 15:11:05.678 PDT: [WARNING]  --output option is deprecated. Replaced by --output-site  
2015.03.11 15:11:05.987 PDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.11 15:11:05.990 PDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.11 15:11:05.991 PDT: [WARNING]  unknown profile condor.whentotransferoutput,  using anyway 
2015.03.11 15:11:06.262 PDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.11 15:11:06.263 PDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.11 15:11:06.263 PDT: [WARNING]  unknown profile condor.whentotransferoutput,  using anyway 
2015.03.11 15:11:06.264 PDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.11 15:11:06.264 PDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.11 15:11:06.265 PDT: [WARNING]  unknown profile condor.whentotransferoutput,  using anyway 
2015.03.11 15:11:07.217 PDT: [ERROR]  Can't open directory "/Users/condor/config" as PRIV_UNKNOWN, errno: 2 (No such file or directory) 
2015.03.11 15:11:07.221 PDT:    
2015.03.11 15:11:07.223 PDT: [ERROR]  Cannot open /Users/condor/config: No such file or directory 
2015.03.11 15:11:07.227 PDT:   ----------------------------------------------------------------------- 
2015.03.11 15:11:07.229 PDT: [ERROR]  Can't open directory "/opt/condor/8.2.3/local.corbusier/config" as PRIV_UNKNOWN, errno: 2 (No such file or directory) 
2015.03.11 15:11:07.233 PDT:   File for submitting this DAG to Condor           : 00167084-0.dag.condor.sub 
2015.03.11 15:11:07.234 PDT: [ERROR]  Cannot open /opt/condor/8.2.3/local.corbusier/config: No such file or directory 
2015.03.11 15:11:07.238 PDT:   Log of DAGMan debugging messages                 : 00167084-0.dag.dagman.out 
2015.03.11 15:11:07.244 PDT:   Log of Condor library output                     : 00167084-0.dag.lib.out 
2015.03.11 15:11:07.249 PDT:   Log of Condor library error messages             : 00167084-0.dag.lib.err 
2015.03.11 15:11:07.255 PDT:   Log of the life of condor_dagman itself          : 00167084-0.dag.dagman.log 
2015.03.11 15:11:07.261 PDT:    
2015.03.11 15:11:07.278 PDT:   ----------------------------------------------------------------------- 
2015.03.11 15:11:08.382 PDT:   Your database is compatible with the current Pegasus version: 4.5.0. 
2015.03.11 15:11:08.388 PDT:   


I have concretized your abstract workflow. The workflow has been entered 
into the workflow database with a state of "planned". The next step is 
to start or execute your workflow. The invocation required is


pegasus-run  /lfs1/work/pegasus-features/#963/dags/work

 
2015.03.11 15:11:08.458 PDT:   Time taken to execute is 2.76 seconds

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

I have -

$ pegasus-version -f 
4.5.0cvs-x86_64_deb_7-20150310154115Z

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

I am downloading from 
     https://download.pegasus.isi.edu/pegasus/4.5.0cvs/

**Comment by mayani** [comment]
**Author:** @vahi

i have added code to catch the NPE and throw a runtime exception .
https://github.com/pegasus-isi/pegasus/commit/5cd38cc0337a938d0716704f7b5c3af569bf6534

mesasge will be similar to the one below
Create dir site XXXX for job stage_in_local_local_0_1 is not present in staging sites for workflow [rossmann, local]

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

OK.  I will pick up the change at the next download.

It is still curious how the error happened in the first place.  We may never know.

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

The new error works as expected.    Here is the reported error:

2015.03.13 14:29:09.672 EDT: [WARNING]  --output option is deprecated. Replaced by --output-site  
2015.03.13 14:29:10.329 EDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.13 14:29:10.332 EDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.13 14:29:10.334 EDT: [WARNING]  unknown profile condor.whentotransferoutput,  using anyway 
2015.03.13 14:29:10.666 EDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.13 14:29:10.668 EDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.13 14:29:10.668 EDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.13 14:29:10.722 EDT: [FATAL ERROR]  
 [1] java.lang.RuntimeException: Create dir site local for job chmod_00167151_02.sh_00167151_02_0 is not present in staging sites for workflow [rossmann] at edu.isi.pegasus.planner.refiner.createdir.Minimal.addCreateDirectoryNodes(Minimal.java:182) 
2015.03.13 14:29:10.910 EDT: [WARNING]  Non-zero exit-code 1

This is interesting because I have

    pegasus.transfer.disable.chmod.sites = rossmann

in the resources file so I wouldn't expect a chmod job to be created for something on rossmann.

**Comment by mayani** [comment]
**Author:** @vahi

I have had a hard time recreating your error. however, looking at the code, i have pushed a potential fix.

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

I find that the error is not totally reproducible.  I will get the error on a couple of attempts and then it will run.

**Comment by mayani** [comment]
**Author:** @vahi

can you deploy the fix that i did on friday?

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

I will download the updated revision.  I wasn't sure how long it takes updates to propagate to the download page.

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

Similar but different exception:

2015.03.17 00:30:25.228 EDT: [WARNING]  --output option is deprecated. Replaced by --output-site  
2015.03.17 00:30:25.929 EDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.17 00:30:25.932 EDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.17 00:30:25.934 EDT: [WARNING]  unknown profile condor.whentotransferoutput,  using anyway 
2015.03.17 00:30:26.318 EDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.17 00:30:26.320 EDT: [WARNING]  unknown profile condor.kill_sig,  using anyway 
2015.03.17 00:30:26.387 EDT: [FATAL ERROR]  
 [1] java.lang.NullPointerException: null at edu.isi.pegasus.planner.refiner.RemoveDirectory.addRemoveDirectoryNodes(RemoveDirectory.java:284) 
2015.03.17 00:30:26.643 EDT: [WARNING]  Non-zero exit-code 1

**Comment by mayani** [comment]
**Author:** @vahi

have pushed out a fix... weird, it never happens at my end.

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

Yes.  These types of problems are such a pain.  It doesn't happen for me every time either.

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

2015.03.23 23:51:09.141 EDT: [ERROR]  INFO:Pegasus.tools.properties:processing properties file /pegtmp/1427183440_00170673_01/work/pegasus.3587293556465648882.properties...  
2015.03.23 23:51:09.154 EDT: [ERROR]  ERROR:Pegasus.tools.db_utils:Unable to find database file in /pegtmp/1427183440_00170673_01/work 
2015.03.23 23:51:09.232 EDT: [ERROR]  Your database is NOT compatible with the current Pegasus version. 
2015.03.23 23:51:09.504 EDT: [FATAL ERROR]  
 [1] java.lang.RuntimeException: pegasus-db-admin failed with non zero exit status /apps/share64/debian7/pegasus/pegasus-4.5.0cvs/bin/pegasus-db-admin check /pegtmp/1427183440_00170673_01/work at edu.isi.pegasus.planner.client.CPlanner.checkForDatabaseCompatibility(CPlanner.java:1906) 
2015.03.23 23:51:10.003 EDT: [WARNING]  Non-zero exit-code 1

**Comment by mayani** [comment]
**Author:** @vahi

you need to run  pegasus-db-admin update on the command line


for 4.5.0 the database needs to be upgraded, and that has to be done manually by the user on the command line

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

I'd swear that I did that earlier.  I've been using 4.5.0 exclusively for some time now.

Is it safe to run pegasus-db-admin update at any time?

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

2015.03.24 09:26:47.961 EDT: [FATAL ERROR]  
 [1] java.lang.RuntimeException: Mismatched file transfer created 00170951_03.sh any
#DiaGrid
 file:///home/nanohub/clarksm/Submit/RegressionTests/Remote/Sweep/Serial/Unnamed/Arbitrary/Args/Test04/00170951/03/00170951_03.sh
# local
  file:///pegtmp/1427217969_00170951/scratch/00170951_03.sh for job 00170951_03.sh_00170951_03 at edu.isi.pegasus.planner.refiner.TransferEngine.runTransferRemotely(TransferEngine.java:308) 
2015.03.24 09:26:48.471 EDT: [WARNING]  Non-zero exit-code 1

**Comment by mayani** [comment]
**Author:** @vahi

this is correct. and is related to JIRA #947 
the planner earlier never complained about it . 

your test is slightly misconfigured. if the stage in job is going to run locally and is going to use a source file url, then it should be associated with site local.

**Comment by mayani** [comment]
**Author:** @vahi

yes. and yes you ran it earlier. but we are making more changes to schema as part of the development. so internally the tool is able to recognize the fact that your db is out of date even though you are on 4.5.0cvs

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

I have specified site != local to indicate where the job should run.  This was based on earlier discussion of small vs. large resource request.   I my case this means DiaGrid or PBS.   Did I misinterpret?   I have definitions like -

<executable name="00170951_01.sh" arch="x86_64" os="linux" installed="false">
		<pfn url="file:///home/nanohub/clarksm/Submit/RegressionTests/Remote/Sweep/Serial/Unnamed/Arbitrary/Args/Test04/00170951/01/00170951_01.sh" site="DiaGrid"/>

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

I now recall that statements like

job.addProfile(Profile(Namespace.HINTS, key='executionPool', value='PBScluster')) 

should be used to direct a job to site.  The site given in the executable pfn should be "local"

**Comment by mayani** [comment]
**Author:** @vahi

[~clarks] does the fix work for you. can we mark this resolved?

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

Yes this can be marked as resolved.  I of course can start a new issue if necessary.
