### ISSUE TITLE
[PM-849] memory allocation error with shell code generator

### ISSUE THREAD

**Issue by mayani** [pegasus-isi/pegasus#967]
This error happens for some runs:

2015.03.13 18:03:15.227 EDT: [WARNING]  --output option is deprecated. Replaced by --output-site  
2015.03.13 18:03:15.232 EDT: [WARNING]  --nocleanup option is deprecated. Use --cleanup none   
2015.03.13 18:03:15.829 EDT: [ERROR]  IOException while creating symbolic links  class java.io.IOException: Cannot run program "chmod": java.io.IOException: error=12, Cannot allocate memory 
2015.03.13 18:03:15.904 EDT: [ERROR]  IOException while executing pegasus-db-admin class java.io.IOException: Cannot run program "/apps/share64/debian7/pegasus/pegasus-4.5.0cvs/bin/pegasus-db-admin": java.io.IOException: error=12, Cannot allocate memory 
2015.03.13 18:03:15.905 EDT: [FATAL ERROR]  
 [1] java.lang.RuntimeException: IOException while executing /apps/share64/debian7/pegasus/pegasus-4.5.0cvs/bin/pegasus-db-admin check at edu.isi.pegasus.planner.client.CPlanner.checkForDatabaseCompatibility(CPlanner.java:1909)
 [2] java.io.IOException: Cannot run program "/apps/share64/debian7/pegasus/pegasus-4.5.0cvs/bin/pegasus-db-admin": java.io.IOException: error=12, Cannot allocate memory at java.lang.ProcessBuilder.start(ProcessBuilder.java:494)
 [3] java.io.IOException: java.io.IOException: error=12, Cannot allocate memory at java.lang.UNIXProcess.<init>(UNIXProcess.java:164)

**Reporter:** Steven Clark [X] (clarks)
**Resolution:** Fixed
**Watchers:**
Steven Clark [X] (clarks)
@rynge
@vahi
**Attachments:**

**Comment by mayani** [comment]
**Author:** @vahi

hi steven
this probably indicates there is not enough memory on the host you are running.

Also, what is the shell code generator used for.
IT is mainly for demonstration purposes. It does not have monitoring setup

**Comment by mayani** [comment]
**Author:** @vahi

i ran your example on a debian host running debian 7
so probably an issue with your setup.

vahi@obelix:/tmp/FRED_copy$ cat /etc/debian_version 
7.8


vahi@obelix:/tmp/FRED_copy$ pegasus-version -f
4.5.0cvs-x86_64_deb_7-20150316021259Z

vahi@obelix:/tmp/FRED_copy$ pegasus-plan --conf 00167201.pegasusrc --sites local --dir /tmp/ --relative-dir scratch --relative-submit-dir work --dax 00167201.dax  --nocleanup --quiet --submit 
2015.03.16 09:49:50.546 PDT: [WARNING]  --nocleanup option is deprecated. Use --cleanup none   
2015.03.16 09:49:52.431 PDT:   Your database is compatible with the current Pegasus version: 4.5.0. 
2015.03.16 09:49:52.528 PDT:   Executing JOB /usr/bin/../bin/pegasus-kickstart  -n pegasus::dirmanager -N null -R local -L 00167201 -T 2015-03-16T09:48:56-07:00 /usr/bin/../bin/pegasus-create-dir  --site local -u file:///tmp/RegressionTests/Local/Sweep/Serial/Named/FRED/scratch 
2015.03.16 09:49:52.701 PDT:   JOB create_dir_00167201_0_local Returned with 0 
2015.03.16 09:49:52.706 PDT:   Executing POSTSCRIPT /usr/bin/pegasus-exitcode   /tmp/work/create_dir_00167201_0_local.out 
2015.03.16 09:49:52.770 PDT:   POSTSCRIPT FOR JOB create_dir_00167201_0_local Returned with 0 
2015.03.16 09:49:52.778 PDT:   Executing JOB /usr/bin/../bin/pegasus-kickstart  -n 00167201_02.sh -N FRED_02 -R local -L 00167201 -T 2015-03-16T09:48:56-07:00 /bin/date  
2015.03.16 09:49:52.913 PDT:   JOB 00167201_02.sh_FRED_02 Returned with 0 
2015.03.16 09:49:52.918 PDT:   Executing POSTSCRIPT /usr/bin/pegasus-exitcode   /tmp/work/00167201_02.sh_FRED_02.out 
2015.03.16 09:49:52.981 PDT:   POSTSCRIPT FOR JOB 00167201_02.sh_FRED_02 Returned with 0 
2015.03.16 09:49:52.988 PDT:   Executing JOB /usr/bin/../bin/pegasus-kickstart  -n 00167201_01.sh -N FRED_01 -R local -L 00167201 -T 2015-03-16T09:48:56-07:00 /bin/date  
2015.03.16 09:49:53.024 PDT:   JOB 00167201_01.sh_FRED_01 Returned with 0 
2015.03.16 09:49:53.029 PDT:   Executing POSTSCRIPT /usr/bin/pegasus-exitcode   /tmp/work/00167201_01.sh_FRED_01.out 
2015.03.16 09:49:53.087 PDT:   POSTSCRIPT FOR JOB 00167201_01.sh_FRED_01 Returned with 0 
2015.03.16 09:49:53.145 PDT:   Time taken to execute is 2.594 seconds

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

The shell code generator can be used by tool developers as an aid in building a workflow.

Yes apparently by environment does not have enough memory.  I notice problem when I have two pegasus-plan operations running simultaneously.  It looks like running the shell code workflow requires a steady 4G of memory.  Starting a second plan requires another 4G with possible higher peak demand. My machine has about 11G available.  4G per plan seems like a lot of memory.

**Comment by mayani** [comment]
**Author:** @vahi

this is related to how we automatically set the java heapmax settings. 

you can set this environment variable JAVA_HEAPMAX 

that will be refer to amount of memory you want to use in MB. you can set it to 512 for your shell code example.

**Comment by mayani** [comment]
**Author:** @vahi

[~clarks] did the env variable fix things for you?

**Comment by mayani** [comment]
**Author:** Steven Clark [X] (clarks)

Yes.  Setting the limit to 512 did the trick.

**Comment by mayani** [comment]
**Author:** @vahi

setting JAVA_HEAPMAX did the trick
